/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRMediaShelfView.h"
#import "AppleTV-Structs.h"


__attribute__((visibility("hidden")))
@interface BRActionShelfControl : BRMediaShelfView {
@private
	int _style;	// 272 = 0x110
	long _previousIndex;	// 276 = 0x114
}
@property(assign) int actionControlStyle;	// G=0x36678241; S=0x36678231; converted property
// converted property getter: - (int)actionControlStyle;	// 0x36678241
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x36678125
// converted property setter: - (void)setActionControlStyle:(int)style;	// 0x36678231
@end

