/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRType.h"


@interface BRAccountType : BRType {
}
+ (id)airTunes;	// 0x36579159
+ (id)cupid;	// 0x365798d9
+ (id)dotMac;	// 0x36579519
+ (id)dotMacSecondary;	// 0x36579609
+ (id)flagstaff;	// 0x365799c9
+ (id)flickr;	// 0x36579429
+ (id)homeShare;	// 0x36579339
+ (id)iTunes;	// 0x36579249
+ (id)iTunesSandbox;	// 0x36579abd
+ (id)sedona;	// 0x365797e9
+ (id)youTube;	// 0x365796f9
- (id)description;	// 0x36733a8d
@end

