/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRDataStore.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface BRAggregateDataStore : BRDataStore {
@private
	NSArray *_dataStores;	// 40 = 0x28
}
- (id)initWithDataStores:(id)dataStores;	// 0x36734a39
- (void)dealloc;	// 0x36734ad1
- (id)loadData;	// 0x36734b6d
- (void)purge;	// 0x36734b1d
- (void)setUseLocalProvidersOnly:(BOOL)only;	// 0x36734c09
- (BOOL)storeAppliesToObject:(id)object;	// 0x36734c89
@end

