//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRAlignmentAdjustingTextControl, BRDividerControl, BRHeaderControl, BRImageControl, BRReflectionControl, BRTextControl;

@interface BRAlertControl : BRControl
{
    BRHeaderControl *_header;
    BRDividerControl *_divider;
    int _type;
    BRTextControl *_primary;
    BRAlignmentAdjustingTextControl *_secondary;
    BRImageControl *_image;
    BRReflectionControl *_reflection;
}

+ (id)alertForError:(id)arg1;
+ (id)alertOfType:(int)arg1;
+ (id)alertOfType:(int)arg1 titled:(id)arg2 primaryText:(id)arg3 secondaryText:(id)arg4;
- (id)_controlsForType:(int)arg1;
- (void)_layoutSubcontrolsForAlert;
- (void)_layoutSubcontrolsForInfo;
- (id)_primaryTextAttibutesForType:(int)arg1;
- (id)accessibilityLabel;
- (void)controlWasActivated;
- (void)dealloc;
- (id)image;
- (id)init;
- (id)initWithType:(int)arg1;
- (id)initWithType:(int)arg1 titled:(id)arg2 primaryText:(id)arg3 secondaryText:(id)arg4;
- (BOOL)isAccessibilityElement;
- (void)layoutSubcontrols;
- (id)primaryText;
- (id)secondaryText;
- (void)setImage:(id)arg1;
- (void)setPrimaryText:(id)arg1;
- (void)setPrimaryText:(id)arg1 withAttributes:(id)arg2;
- (void)setSecondaryText:(id)arg1;
- (void)setSecondaryText:(id)arg1 withAttributes:(id)arg2;
- (void)setTitle:(id)arg1;
- (void)setType:(int)arg1;
- (id)title;

@end

