//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRTextControl.h"

@interface BRAlignmentAdjustingTextControl : BRTextControl
{
    int _singleLineAlignment;
    int _multiLineAlignment;
}

- (void)_updateAttributes;
- (id)init;
- (void)layoutSubcontrols;
@property int multiLineAlignment; // @synthesize multiLineAlignment=_multiLineAlignment;
- (void)setAttributedString:(id)arg1;
@property int singleLineAlignment; // @synthesize singleLineAlignment=_singleLineAlignment;

@end

