/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface BRApplianceBrowserControlFactory : NSObject {
}
+ (id)factory;	// 0x3667bd45
- (id)_applianceNameTextAttributes;	// 0x3667bed1
- (id)_categoryNameTextAttributes;	// 0x3667bfbd
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x3667bd8d
@end

