/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"

@class BRControllerStack, BRWindow;

@interface BRApplicationStackManager : BRSingleton {
@private
	BRControllerStack *_stack;	// 4 = 0x4
	BRWindow *_window;	// 8 = 0x8
}
@property(readonly, retain) BRControllerStack *stack;	// G=0x36723bdd; converted property
@property(readonly, retain) BRWindow *window;	// G=0x36723bcd; converted property
+ (void)setSingleton:(id)singleton;	// 0x36723ab9
+ (id)singleton;	// 0x36723aa9
- (id)init;	// 0x36723ac9
- (void)show;	// 0x36723bad
// converted property getter: - (id)stack;	// 0x36723bdd
// converted property getter: - (id)window;	// 0x36723bcd
@end

