/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSMutableDictionary;

@interface BRApplianceCategory : NSObject {
@private
	NSMutableDictionary *_info;	// 4 = 0x4
}
@property(retain) id action;	// G=0x36643e8d; S=0x36643e65; converted property
@property(retain) id identifier;	// G=0x36643e3d; S=0x36643e15; converted property
@property(assign) BOOL isDefaultCategory;	// G=0x36643dd5; S=0x36643d81; converted property
@property(assign) BOOL isStoreCategory;	// G=0x36643f09; S=0x36643eb5; converted property
@property(assign) BOOL isStoreDependent;	// G=0x36644031; S=0x36643fdd; converted property
@property(retain) id name;	// G=0x36643cc5; S=0x36643c9d; converted property
@property(assign) float preferredOrder;	// G=0x36643d41; S=0x36643ced; converted property
@property(assign) BOOL shouldDisplayOnStartup;	// G=0x366440c5; S=0x36644071; converted property
@property(retain) id textEntryHistoryDisplayBehaviors;	// G=0x3664424d; S=0x36644219; converted property
@property(retain) id textEntryHistoryDisplayClients;	// G=0x366441f1; S=0x366441bd; converted property
@property(retain) id textEntryHistoryStorageBehavior;	// G=0x36644195; S=0x36644161; converted property
@property(retain) id textEntryHistoryStorageClient;	// G=0x36644139; S=0x36644105; converted property
+ (id)categoryWithName:(id)name identifier:(id)identifier preferredOrder:(float)order;	// 0x36643ad1
- (id)init;	// 0x36643b5d
// converted property getter: - (id)action;	// 0x36643e8d
- (void)dealloc;	// 0x36643bc1
- (id)description;	// 0x36643c0d
- (BOOL)followsStoreCateogry;	// 0x36643f9d
// converted property getter: - (id)identifier;	// 0x36643e3d
// converted property getter: - (BOOL)isDefaultCategory;	// 0x36643dd5
// converted property getter: - (BOOL)isStoreCategory;	// 0x36643f09
// converted property getter: - (BOOL)isStoreDependent;	// 0x36644031
// converted property getter: - (id)name;	// 0x36643cc5
// converted property getter: - (float)preferredOrder;	// 0x36643d41
// converted property setter: - (void)setAction:(id)action;	// 0x36643e65
- (void)setFollowsStoreCategory:(BOOL)category;	// 0x36643f49
// converted property setter: - (void)setIdentifier:(id)identifier;	// 0x36643e15
// converted property setter: - (void)setIsDefaultCategory:(BOOL)category;	// 0x36643d81
// converted property setter: - (void)setIsStoreCategory:(BOOL)category;	// 0x36643eb5
// converted property setter: - (void)setIsStoreDependent:(BOOL)dependent;	// 0x36643fdd
// converted property setter: - (void)setName:(id)name;	// 0x36643c9d
// converted property setter: - (void)setPreferredOrder:(float)order;	// 0x36643ced
// converted property setter: - (void)setShouldDisplayOnStartup:(BOOL)displayOnStartup;	// 0x36644071
// converted property setter: - (void)setTextEntryHistoryDisplayBehaviors:(id)behaviors;	// 0x36644219
// converted property setter: - (void)setTextEntryHistoryDisplayClients:(id)clients;	// 0x366441bd
// converted property setter: - (void)setTextEntryHistoryStorageBehavior:(id)behavior;	// 0x36644161
// converted property setter: - (void)setTextEntryHistoryStorageClient:(id)client;	// 0x36644105
// converted property getter: - (BOOL)shouldDisplayOnStartup;	// 0x366440c5
// converted property getter: - (id)textEntryHistoryDisplayBehaviors;	// 0x3664424d
// converted property getter: - (id)textEntryHistoryDisplayClients;	// 0x366441f1
// converted property getter: - (id)textEntryHistoryStorageBehavior;	// 0x36644195
// converted property getter: - (id)textEntryHistoryStorageClient;	// 0x36644139
@end

