/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRProvider.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface BRApplianceCategoryProvider : NSObject <BRProvider> {
@private
	NSArray *_categories;	// 4 = 0x4
}
@property(retain) NSArray *categories;	// G=0x3667c53d; S=0x3667c451; converted property
// converted property getter: - (id)categories;	// 0x3667c53d
- (long)categoryIndexForIdentifier:(id)identifier;	// 0x3667c5c1
- (id)controlFactory;	// 0x3667c649
- (id)dataAtIndex:(long)index;	// 0x3667c685
- (long)dataCount;	// 0x3667c665
- (void)dealloc;	// 0x3667c405
- (long)defaultCategoryIndex;	// 0x3667c54d
- (id)hashForDataAtIndex:(long)index;	// 0x3667c6a5
// converted property setter: - (void)setCategories:(id)categories;	// 0x3667c451
@end

