//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



@class BRAsyncTaskContext, NSString, NSThread;

@interface BRAsyncTask : NSObject
{
    NSThread *_callingThread;
    id _target;
    SEL _selector;
    id _object;
    id _result;
    BRAsyncTaskContext *_context;
    int _state;
    NSString *_identifier;
}

+ (void)_runTaskBlock:(CDUnknownBlockType)arg1;
+ (void)initialize;
+ (id)taskWithBlock:(CDUnknownBlockType)arg1;
+ (id)taskWithContext:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
+ (id)taskWithSelector:(SEL)arg1 onTarget:(id)arg2 withObject:(id)arg3;
+ (id)taskWithSelector:(SEL)arg1 onTarget:(id)arg2 withObject:(id)arg3 withContext:(id)arg4;
+ (id)voidReturnValue;
- (id)_initWithSelector:(SEL)arg1 onTarget:(id)arg2 withObject:(id)arg3 withContext:(id)arg4;
- (id)callingThread;
- (void)cancel;
- (id)context;
- (void)dealloc;
- (id)description;
- (id)identifier;
- (id)invoke;
- (id)object;
- (id)result;
- (void)run;
- (SEL)selector;
- (void)setIdentifier:(id)arg1;
- (void)setState:(int)arg1;
- (int)state;
- (id)target;

@end

