/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, NSAttributedString, BRMarqueeTextControl;

__attribute__((visibility("hidden")))
@interface BRAutoScrollingTextControl : BRControl {
@private
	NSAttributedString *_text;	// 48 = 0x30
	BRMarqueeTextControl *_scrollingTextControl;	// 52 = 0x34
	BRTextControl *_textControl;	// 56 = 0x38
	BOOL _crossfadeEnabled;	// 60 = 0x3c
	BOOL _autoScrollEnabled;	// 61 = 0x3d
	BOOL _displaysText;	// 62 = 0x3e
	BOOL _useAlphaFadeMask;	// 63 = 0x3f
	BOOL _animationUsesDelay;	// 64 = 0x40
}
@property(assign) BOOL animationUsesDelay;	// G=0x36677a05; S=0x366779f5; converted property
@property(retain) id attributedString;	// G=0x366778d9; S=0x3667781d; converted property
@property(assign) BOOL autoScrollEnabled;	// G=0x36677939; S=0x36677909; converted property
@property(assign) BOOL crossfadeEnabled;	// G=0x366778f9; S=0x366778e9; converted property
@property(assign) BOOL displaysText;	// G=0x366779e5; S=0x36677949; converted property
@property(assign) BOOL useAlphaFadeMask;	// G=0x36677a25; S=0x36677a15; converted property
- (id)init;	// 0x366776f1
- (void)_removeMarqueeControl;	// 0x366780dd
- (void)_removeTextControl;	// 0x36678095
// converted property getter: - (BOOL)animationUsesDelay;	// 0x36677a05
// converted property getter: - (id)attributedString;	// 0x366778d9
// converted property getter: - (BOOL)autoScrollEnabled;	// 0x36677939
// converted property getter: - (BOOL)crossfadeEnabled;	// 0x366778f9
- (void)dealloc;	// 0x36677735
// converted property getter: - (BOOL)displaysText;	// 0x366779e5
- (void)layoutSubcontrols;	// 0x36677a35
- (id)preferredActionForKey:(id)key;	// 0x36677f91
// converted property setter: - (void)setAnimationUsesDelay:(BOOL)delay;	// 0x366779f5
// converted property setter: - (void)setAttributedString:(id)string;	// 0x3667781d
// converted property setter: - (void)setAutoScrollEnabled:(BOOL)enabled;	// 0x36677909
// converted property setter: - (void)setCrossfadeEnabled:(BOOL)enabled;	// 0x366778e9
// converted property setter: - (void)setDisplaysText:(BOOL)text;	// 0x36677949
- (void)setText:(id)text withAttributes:(id)attributes;	// 0x366777a9
// converted property setter: - (void)setUseAlphaFadeMask:(BOOL)mask;	// 0x36677a15
// converted property getter: - (BOOL)useAlphaFadeMask;	// 0x36677a25
@end

