//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRMarqueeTextControl, BRTextControl, NSAttributedString;

__attribute__((visibility("hidden")))
@interface BRAutoScrollingTextControl : BRControl
{
    NSAttributedString *_text;
    BRMarqueeTextControl *_scrollingTextControl;
    BRTextControl *_textControl;
    BOOL _crossfadeEnabled;
    BOOL _autoScrollEnabled;
    BOOL _displaysText;
    BOOL _useAlphaFadeMask;
    BOOL _animationUsesDelay;
}

- (void)_removeMarqueeControl;
- (void)_removeTextControl;
- (BOOL)animationUsesDelay;
- (id)attributedString;
- (BOOL)autoScrollEnabled;
- (BOOL)crossfadeEnabled;
- (void)dealloc;
- (BOOL)displaysText;
- (id)init;
- (void)layoutSubcontrols;
- (id)preferredActionForKey:(id)arg1;
- (void)setAnimationUsesDelay:(BOOL)arg1;
- (void)setAttributedString:(id)arg1;
- (void)setAutoScrollEnabled:(BOOL)arg1;
- (void)setCrossfadeEnabled:(BOOL)arg1;
- (void)setDisplaysText:(BOOL)arg1;
- (void)setText:(id)arg1 withAttributes:(id)arg2;
- (void)setUseAlphaFadeMask:(BOOL)arg1;
- (BOOL)useAlphaFadeMask;

@end

