//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



#import "BRMediaLoading-Protocol.h"
#import "BRMediaProvider-Protocol.h"

@interface BRBaseMediaProvider : NSObject <BRMediaProvider, BRMediaLoading>
{
    int _providerStatus;
    BOOL _passwordProtected;
}

+ (id)errorStateOfProvider:(id)arg1;
+ (id)mediaProvider;
- (BOOL)autoload;
- (long)countOfObjectsWithMediaType:(id)arg1;
- (void)dealloc;
- (int)errorCodeForProvider;
- (void)flush;
- (BOOL)isPasswordProtected;
- (int)load;
- (int)loadWithUsername:(id)arg1 password:(id)arg2;
- (id)mediaForEntityName:(id)arg1;
- (id)mediaTypes;
- (id)objectsWithEntityName:(id)arg1 qualifiedByPredicate:(id)arg2 sortDescriptors:(id)arg3 error:(id *)arg4;
- (id)objectsWithEntityName:(id)arg1 qualifiedByPredicate:(id)arg2 sortDescriptors:(id)arg3 excludeHiddenObjects:(BOOL)arg4 error:(id *)arg5;
- (id)providerID;
- (id)providerName;
- (void)reset;
- (void)setIsPasswordProtected:(BOOL)arg1;
- (void)setStatus:(int)arg1;
- (int)status;
- (int)unload;

@end

