/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


@interface BRBaseMenuItemLayerPopulator : NSObject {
@private
	id _object;	// 4 = 0x4
	id _delegate;	// 8 = 0x8
	unsigned _matchOrder;	// 12 = 0xc
}
@property(readonly, assign) unsigned matchOrder;	// G=0x366ed95d; converted property
+ (BOOL)canHandleObject:(id)object;	// 0x366e50ed
- (id)init;	// 0x366e50f1
- (void)dealloc;	// 0x366e519d
- (id)dividerLayer;	// 0x366e5309
- (id)lowerCenteredString;	// 0x366e5389
- (id)lowerLeftString;	// 0x366e5385
- (id)lowerRightImage;	// 0x366e5395
// converted property getter: - (unsigned)matchOrder;	// 0x366ed95d
- (id)menuItem;	// 0x366e52ed
- (id)menuItemForObject:(id)object delegate:(id)delegate;	// 0x366e51e9
- (float)menuItemHeightForObject:(id)object delegate:(id)delegate;	// 0x366e5249
- (id)rightJustifiedText;	// 0x366e537d
- (void)setObject:(id)object;	// 0x366e52ad
- (BOOL)shouldUseMultilineItem:(id)item;	// 0x366e5399
- (id)subtitle;	// 0x366e5381
- (id)thumbnailImage;	// 0x366e538d
- (id)title;	// 0x366e5379
- (id)titleForObject:(id)object delegate:(id)delegate;	// 0x366e524d
- (id)upperRightImage;	// 0x366e5391
@end

