//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRSingleton.h"

@class NSTimer;

@interface BRBackgroundTaskManager : BRSingleton
{
    int _numberOfCurrentBackgroundProcesses;
    double _lastUserActivity;
    NSTimer *_backgroundProcessSuppressionTimer;
    NSTimer *_heavyBackgroundProcessSuppresionTimer;
}

+ (BOOL)backgroundTasksRunning;
+ (void)finishedBackgroundProcessing;
+ (void)finishedFileCopy:(id)arg1;
+ (void)finishedMediaSyncing;
+ (void)holdOffBackgroundTasks;
+ (BOOL)mediaSyncInProgress;
+ (BOOL)okToDoBackgroundProcessing;
+ (void)setSingleton:(id)arg1;
+ (id)singleton;
+ (void)startedFileCopy:(id)arg1;
+ (void)startingBackgroundProcessing;
+ (void)startingMediaSyncing;
+ (double)timeSinceLastUserAction;
- (BOOL)_backgroundTasksRunning;
- (void)_finishedBackgroundProcessing;
- (void)_holdOffBackgroundTasks;
- (void)_holdOffHeavyBackgroundTasks;
- (BOOL)_okToDoBackgroundProcessing;
- (void)_sendResumeBackgroundProcessingNotification;
- (void)_sendResumeHeavyBackgroundProcessingNotification;
- (void)_sendStopBackgroundProcessingNotification;
- (void)_sendStopHeavyBackgroundProcessingNotification;
- (void)_setOKToDoBackgroundProcessing:(id)arg1;
- (void)_setOKToDoHeavyBackgroundProcessing:(id)arg1;
- (void)_startingBackgroundProcessing;
- (double)_timeSinceLastUserAction;
- (void)_updateActivity:(id)arg1;
- (void)dealloc;
- (id)init;

@end

