/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRMediaProvider.h"
#import "BRMediaLoading.h"


@interface BRBaseMediaProvider : NSObject <BRMediaProvider, BRMediaLoading> {
@private
	int _providerStatus;	// 4 = 0x4
	BOOL _passwordProtected;	// 8 = 0x8
}
@property(assign) BOOL isPasswordProtected;	// G=0x36733f39; S=0x36733f49; converted property
@property(assign) int status;	// G=0x36733db1; S=0x36733dd9; converted property
+ (id)errorStateOfProvider:(id)provider;	// 0x36733afd
+ (id)mediaProvider;	// 0x36733b3d
- (BOOL)autoload;	// 0x36733f21
- (long)countOfObjectsWithMediaType:(id)mediaType;	// 0x36733f75
- (void)dealloc;	// 0x36733b79
- (int)errorCodeForProvider;	// 0x36733dd5
- (void)flush;	// 0x36733f71
// converted property getter: - (BOOL)isPasswordProtected;	// 0x36733f39
- (int)load;	// 0x36733ef1
- (int)loadWithUsername:(id)username password:(id)password;	// 0x36733f01
- (id)mediaForEntityName:(id)entityName;	// 0x36733c05
- (id)mediaTypes;	// 0x36733be9
- (id)objectsWithEntityName:(id)entityName qualifiedByPredicate:(id)predicate sortDescriptors:(id)descriptors error:(id *)error;	// 0x36733c21
- (id)objectsWithEntityName:(id)entityName qualifiedByPredicate:(id)predicate sortDescriptors:(id)descriptors excludeHiddenObjects:(BOOL)objects error:(id *)error;	// 0x36733c51
- (id)providerID;	// 0x36733bd5
- (id)providerName;	// 0x36733bd9
- (void)reset;	// 0x36733f25
// converted property setter: - (void)setIsPasswordProtected:(BOOL)aProtected;	// 0x36733f49
// converted property setter: - (void)setStatus:(int)status;	// 0x36733dd9
// converted property getter: - (int)status;	// 0x36733db1
- (int)unload;	// 0x36733f11
@end

