//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

#import "BRMetadataPopulator.h"

__attribute__((visibility("hidden")))
@interface BRBaseMetadataPopulator : NSObject <BRMetadataPopulator>
{
}

- (void)_populateMetadataLabels:(id *)arg1 andValues:(id *)arg2 forAsset:(id)arg3;
- (id)axMetadataFromAsset:(id)arg1;
- (id)copyrightForAsset:(id)arg1;
- (void)populateLayer:(id)arg1 fromAsset:(id)arg2;
- (void)populateLongDescriptionLayer:(id)arg1 fromAsset:(id)arg2;
- (void)populateMetadataLabels:(id *)arg1 andValues:(id *)arg2 forAsset:(id)arg3;
- (id)ratingForAsset:(id)arg1;
- (id)starRatingForAsset:(id)arg1;
- (id)summaryForAsset:(id)arg1;
- (id)titleForAsset:(id)arg1;

@end

