//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

@class BRDropShadowControl, BRListControl;

__attribute__((visibility("hidden")))
@interface BRBoxListControl : BRControl
{
    BRListControl *_list;
    BRDropShadowControl *_shadow;
}

- (void)dealloc;
- (id)init;
- (void)layoutSubcontrols;
- (float)listHeightToMaximum:(float)arg1;
- (id)providers;
- (void)setProvider:(id)arg1;
- (void)setProviders:(id)arg1;

@end

