//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



@class NSDate, NSString;

@interface BRChapter : NSObject
{
    NSString *_name;
    NSString *_description;
    NSString *_identifier;
    double _startTime;
    double _endTime;
    NSDate *_startDate;
    NSDate *_endDate;
}

+ (id)chapterWithAssetID:(id)arg1 startDate:(id)arg2 endDate:(id)arg3;
+ (id)chapterWithAssetID:(id)arg1 startTime:(double)arg2 endTime:(double)arg3;
- (BOOL)containsDate:(id)arg1;
- (BOOL)containsTime:(double)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSString *description; // @synthesize description=_description;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property(nonatomic) double endTime; // @synthesize endTime=_endTime;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)imageProxy;
- (id)initWithAssetID:(id)arg1 startDate:(id)arg2 endDate:(id)arg3;
- (id)initWithAssetID:(id)arg1 startTime:(double)arg2 endTime:(double)arg3;
- (void)invalidate;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;

@end

