/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, BRImageControl, BRMarqueeTextControl;
@protocol BRImageProxy;

@interface BRComboMenuItemLayer : BRControl {
@private
	BRControl *_background;	// 48 = 0x30
	BRImageControl *_thumbnailLayer;	// 52 = 0x34
	id<BRImageProxy> _imageProxy;	// 56 = 0x38
	BRMarqueeTextControl *_titleLayer;	// 60 = 0x3c
	BRTextControl *_subtitleLayer;	// 64 = 0x40
	BRTextControl *_leftTextLayer;	// 68 = 0x44
	BRTextControl *_middleTextLayer;	// 72 = 0x48
	BRImageControl *_bottomRightImageLayer;	// 76 = 0x4c
	BRImageControl *_topRightImageLayer;	// 80 = 0x50
	float _thumbnailPaddingFactor;	// 84 = 0x54
	float _thumbnailLayerAspect;	// 88 = 0x58
}
@property(retain) id subtitle;	// G=0x3677c9d1; S=0x3677c8a9; converted property
@property(assign) float thumbnailLayerAspectRatio;	// G=0x3677ce05; S=0x3677cd8d; converted property
@property(assign) float thumbnailPaddingFactor;	// G=0x3677cd7d; S=0x3677cd41; converted property
@property(retain) id title;	// G=0x3677c871; S=0x3677c749; converted property
- (id)init;	// 0x3677c419
- (void)_artworkAssetLoadedNotification:(id)notification;	// 0x3677dac5
- (id)_comboMenuItemSubtitleTextAttributes;	// 0x3677da81
- (id)_comboMenuItemTitleTextAttributes;	// 0x3677da41
- (void)_setThumbnail:(id)thumbnail;	// 0x3677d9e5
- (id)accessibilityLabel;	// 0x3677d925
- (id)axSelectedItemText;	// 0x3677d7f5
- (void)controlWasActivated;	// 0x3677c655
- (void)controlWasDeactivated;	// 0x3677c6c5
- (void)controlWasFocused;	// 0x3677cf8d
- (void)controlWasUnfocused;	// 0x3677cfdd
- (void)dealloc;	// 0x3677c539
- (float)defaultRowHeight;	// 0x3677c715
- (CGRect)focusCursorFrame;	// 0x3677d02d
- (BOOL)isAccessibilityElement;	// 0x3677d921
- (void)layoutSubcontrols;	// 0x3677d0c1
- (void)setBottomRightImage:(id)image;	// 0x3677ce15
- (void)setLeftText:(id)text;	// 0x3677ca09
- (void)setMiddleText:(id)text;	// 0x3677cb31
// converted property setter: - (void)setSubtitle:(id)subtitle;	// 0x3677c8a9
- (void)setThumbnailImageProxy:(id)proxy;	// 0x3677cc59
// converted property setter: - (void)setThumbnailLayerAspectRatio:(float)ratio;	// 0x3677cd8d
// converted property setter: - (void)setThumbnailPaddingFactor:(float)factor;	// 0x3677cd41
// converted property setter: - (void)setTitle:(id)title;	// 0x3677c749
- (void)setTopRightImage:(id)image;	// 0x3677ced1
// converted property getter: - (id)subtitle;	// 0x3677c9d1
// converted property getter: - (float)thumbnailLayerAspectRatio;	// 0x3677ce05
// converted property getter: - (float)thumbnailPaddingFactor;	// 0x3677cd7d
// converted property getter: - (id)title;	// 0x3677c871
@end

