/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSTimer, BRImage;
@protocol BRImageProxy;

__attribute__((visibility("hidden")))
@interface BRCoverArtImageLayer : BRControl {
@private
	id<BRImageProxy> _imageProxy;	// 48 = 0x30
	BRImage *_image;	// 52 = 0x34
	BOOL _deletterboxImage;	// 56 = 0x38
	BOOL _showsDefaultCoverArt;	// 57 = 0x39
	BOOL _showsBorder;	// 58 = 0x3a
	NSTimer *_setCoverArtTimer;	// 60 = 0x3c
}
@property(assign) BOOL deletterboxImage;	// G=0x3670a12d; S=0x3670a0fd; converted property
@property(readonly, retain) BRImage *image;	// G=0x3670a099; converted property
@property(assign) BOOL showsBorder;	// G=0x3670a1fd; S=0x3670a15d; converted property
@property(assign) BOOL showsDefaultCoverArt;	// G=0x3670a14d; S=0x3670a13d; converted property
- (id)init;	// 0x36709f41
- (void)_coverArtChanged:(id)changed;	// 0x3670a531
- (void)_setCoverArtImage:(id)image;	// 0x3670a389
- (void)_setCoverArtImageWithDelay:(id)delay;	// 0x3670a32d
- (void)_setImageAsContents:(id)contents;	// 0x3670a4b5
- (void)_updateCoverArt;	// 0x3670a20d
- (void)dealloc;	// 0x3670a009
// converted property getter: - (BOOL)deletterboxImage;	// 0x3670a12d
// converted property getter: - (id)image;	// 0x3670a099
// converted property setter: - (void)setDeletterboxImage:(BOOL)image;	// 0x3670a0fd
- (void)setImageProxy:(id)proxy;	// 0x3670a0a9
// converted property setter: - (void)setShowsBorder:(BOOL)border;	// 0x3670a15d
// converted property setter: - (void)setShowsDefaultCoverArt:(BOOL)art;	// 0x3670a13d
// converted property getter: - (BOOL)showsBorder;	// 0x3670a1fd
// converted property getter: - (BOOL)showsDefaultCoverArt;	// 0x3670a14d
@end

