//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



@class BRControl, NSString;

@interface BRControlMediator : NSObject
{
    NSString *_identifier;
    BRControl *_control;
    BRControl *_preview;
    BOOL _active;
}

+ (id)mediator;
+ (id)mediatorWithControl:(id)arg1 identifier:(id)arg2;
- (BOOL)active;
- (id)control;
- (void)dealloc;
- (id)identifier;
- (id)init;
- (id)previewControl;
- (void)setActive:(BOOL)arg1;
- (void)setControl:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setPreviewControl:(id)arg1;

@end

