/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSString, BRControl;

@interface BRControlMediator : NSObject {
@private
	NSString *_identifier;	// 4 = 0x4
	BRControl *_control;	// 8 = 0x8
	BRControl *_preview;	// 12 = 0xc
	BOOL _active;	// 16 = 0x10
}
@property(assign) BOOL active;	// G=0x36714bd1; S=0x36714b75; converted property
@property(retain) BRControl *control;	// G=0x36714c65; S=0x36714be1; converted property
@property(retain) NSString *identifier;	// G=0x36714b65; S=0x36714b25; converted property
@property(retain) id previewControl;	// G=0x36714cf9; S=0x36714c75; converted property
+ (id)mediator;	// 0x36714a11
+ (id)mediatorWithControl:(id)control identifier:(id)identifier;	// 0x36714a59
- (id)init;	// 0x367149cd
// converted property getter: - (BOOL)active;	// 0x36714bd1
// converted property getter: - (id)control;	// 0x36714c65
- (void)dealloc;	// 0x36714ab1
// converted property getter: - (id)identifier;	// 0x36714b65
// converted property getter: - (id)previewControl;	// 0x36714cf9
// converted property setter: - (void)setActive:(BOOL)active;	// 0x36714b75
// converted property setter: - (void)setControl:(id)control;	// 0x36714be1
// converted property setter: - (void)setIdentifier:(id)identifier;	// 0x36714b25
// converted property setter: - (void)setPreviewControl:(id)control;	// 0x36714c75
@end

