//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRBaseMenuItemLayerPopulator.h"

@interface BRCollectionMenuItemPopulator : BRBaseMenuItemLayerPopulator
{
}

+ (BOOL)canHandleObject:(id)arg1;
- (id)_folderItemTypes;
- (id)allowedTypesPredicate;
- (id)menuItem;
- (float)menuItemHeightForObject:(id)arg1 delegate:(id)arg2;
- (unsigned int)numItemsInCollection:(id)arg1 hasOnlySongs:(char *)arg2;
- (id)numItemsString;

@end

