//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@protocol BRContextMenuUtility <NSObject>
+ (id)utility;
- (id)contextMenuProviderForObject:(id)arg1 target:(id)arg2 selector:(SEL)arg3;
- (void)handleSelectionForObject:(id)arg1 sender:(id)arg2 context:(id)arg3;
@end

