/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRContextMenuControl, NSMutableDictionary, BRControllerStack;
@protocol BRSubControllerHosting;

@interface BRController : BRControl {
@private
	NSMutableDictionary *_labels;	// 48 = 0x30
	BRControllerStack *_stack;	// 52 = 0x34
	BOOL _depthLimited;	// 56 = 0x38
	BRContextMenuControl *_contextMenu;	// 60 = 0x3c
	id _wasPushedBlock;	// 64 = 0x40
	id _wasPoppedBlock;	// 68 = 0x44
	id _wasBuriedBlock;	// 72 = 0x48
	id _wasExhumedBlock;	// 76 = 0x4c
	BRController<BRSubControllerHosting> *_hostingController;	// 80 = 0x50
}
@property(assign) BOOL depthLimited;	// G=0x3664897d; S=0x3664896d; converted property
@property(assign, nonatomic) BRController<BRSubControllerHosting> *hostingController;	// G=0x36648b19; S=0x366483f5; @synthesize=_hostingController
@property(retain) BRControllerStack *stack;	// G=0x3664886d; S=0x3664885d; converted property
@property(copy, nonatomic) id wasBuriedBlock;	// G=0x36648ab1; S=0x36648ac1; @synthesize=_wasBuriedBlock
@property(copy, nonatomic) id wasExhumedBlock;	// G=0x36648ae5; S=0x36648af5; @synthesize=_wasExhumedBlock
@property(copy, nonatomic) id wasPoppedBlock;	// G=0x36648a7d; S=0x36648a8d; @synthesize=_wasPoppedBlock
@property(copy, nonatomic) id wasPushedBlock;	// G=0x36648a49; S=0x36648a59; @synthesize=_wasPushedBlock
+ (id)controllerWithContentControl:(id)contentControl;	// 0x36648231
- (id)init;	// 0x3664826d
- (void)_contextMenuCancelItemSelected:(id)selected;	// 0x36648ce5
- (void)_handleWindowMaxBoundsChanged;	// 0x366489a9
- (void)addLabel:(id)label;	// 0x366488b1
- (BOOL)brEventAction:(id)action;	// 0x36648445
- (BOOL)canBeRemovedFromStack;	// 0x366488ad
- (int)contextMenuDimOption;	// 0x36648bad
- (BOOL)contextMenuIsVisible;	// 0x36648b35
- (id)controlForContextMenuPositioning;	// 0x36648b2d
- (id)controlForContextMenuStart;	// 0x36648b31
- (id)controlToDim;	// 0x36648ba9
- (void)controlWasDeactivated;	// 0x36648405
- (void)dealloc;	// 0x36648319
// converted property getter: - (BOOL)depthLimited;	// 0x3664897d
- (id)description;	// 0x36648729
- (void)dismissContextMenu;	// 0x36648b61
- (long)errorNumberForNoContent;	// 0x36648991
// declared property getter: - (id)hostingController;	// 0x36648b19
- (BOOL)isLabelled:(id)labelled;	// 0x36648935
- (BOOL)isNetworkDependent;	// 0x36648965
- (BOOL)isValidAfterDataUpdate;	// 0x3664898d
- (id)providersForContextMenu;	// 0x36648b29
- (BOOL)recreateOnReselect;	// 0x36648969
- (void)removeLabel:(id)label;	// 0x36648915
// converted property setter: - (void)setDepthLimited:(BOOL)limited;	// 0x3664896d
// declared property setter: - (void)setHostingController:(id)controller;	// 0x366483f5
// converted property setter: - (void)setStack:(id)stack;	// 0x3664885d
// declared property setter: - (void)setWasBuriedBlock:(id)block;	// 0x36648ac1
// declared property setter: - (void)setWasExhumedBlock:(id)block;	// 0x36648af5
// declared property setter: - (void)setWasPoppedBlock:(id)block;	// 0x36648a8d
// declared property setter: - (void)setWasPushedBlock:(id)block;	// 0x36648a59
// converted property getter: - (id)stack;	// 0x3664886d
- (BOOL)topOfStack;	// 0x3664887d
- (id)transitionType;	// 0x36648999
- (void)wasBuried;	// 0x36648c91
// declared property getter: - (id)wasBuriedBlock;	// 0x36648ab1
- (void)wasExhumed;	// 0x36648cc5
// declared property getter: - (id)wasExhumedBlock;	// 0x36648ae5
- (void)wasPopped;	// 0x36648c19
// declared property getter: - (id)wasPoppedBlock;	// 0x36648a7d
- (void)wasPushed;	// 0x36648bb1
// declared property getter: - (id)wasPushedBlock;	// 0x36648a49
@end

