//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



__attribute__((visibility("hidden")))
@interface BRContainerViewSectionInfo : NSObject
{
    long _numberOfItems;
    BOOL _hasHeader;
}

@property BOOL hasHeader; // @synthesize hasHeader=_hasHeader;
@property long numberOfItems; // @synthesize numberOfItems=_numberOfItems;

@end

