/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "NSObject.h"


@protocol BRContainerViewCell <NSObject>
- (void)cancelContainerViewLoad;
- (void)loadWithCompletionBlock:(id)completionBlock;
@optional
- (void)setFollowsLoadAndDisplayOnDemand;
@required
- (void)setIgnoreLoadAndDisplayOnDemand;
- (void)setIgnoreLoadAndDisplayOnDemandDisableAnimations:(BOOL)animations;
- (void)setReadyToDisplay;
@end

