//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class NSMutableArray;

@interface BRControllerStack : BRControl
{
    NSMutableArray *_stack;
    NSMutableArray *_transactions;
    NSMutableArray *_currentStackPath;
    BOOL _processingTransactions;
    BOOL _dumpStack;
}

- (void)_addTransaction:(id)arg1;
- (id)_checkSubstitutions:(id)arg1;
- (void)_databaseObjectModified:(id)arg1;
- (void)_performDepthLimitedCullingForController:(id)arg1;
- (void)_processPopToClassTransaction:(id)arg1;
- (void)_processPopToLabelTransaction:(id)arg1;
- (void)_processPopToTransaction:(id)arg1;
- (void)_processPopTransaction:(id)arg1;
- (void)_processPushTransaction:(id)arg1;
- (void)_processRemoveTransaction:(id)arg1;
- (void)_processReplaceAllTransaction:(id)arg1;
- (void)_processReplaceControllersAboveLabelTransaction:(id)arg1;
- (void)_processSwapTransaction:(id)arg1;
- (void)_processTransactions;
- (void)_refreshControllersNotification:(id)arg1;
- (void)_setContent:(id)arg1 direction:(int)arg2 oldTransition:(id)arg3;
- (void)_updateControllerValidity:(id)arg1;
- (void)_updateControllersOnlyLegacy:(BOOL)arg1;
- (void)_updateStackPathForPoppingController:(id)arg1;
- (void)_updateStackPathForPushingController:(id)arg1;
- (id)accessibilityLabel;
- (BOOL)brEventAction:(id)arg1;
- (id)controllers;
- (id)controllersLabeled:(id)arg1;
- (id)controllersOfClass:(Class)arg1;
- (int)count;
- (void)dealloc;
- (id)init;
- (void)layoutSubcontrols;
- (id)peekController;
- (void)popController;
- (void)popToController:(id)arg1;
- (void)popToControllerOfClass:(Class)arg1;
- (void)popToControllerWithLabel:(id)arg1;
- (void)pushController:(id)arg1;
- (void)removeController:(id)arg1;
- (void)replaceAllControllersWithController:(id)arg1;
- (void)replaceControllersAboveLabel:(id)arg1 withController:(id)arg2;
- (id)rootController;
- (id)stackPathForController:(id)arg1;
- (void)swapController:(id)arg1;
- (void)updateStackPathForController:(id)arg1 previousIdentifier:(id)arg2;

@end

