/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSTimer, BRBoxListControl;

@interface BRContextMenuControl : BRControl {
@private
	BRControl *_endPositionControl;	// 48 = 0x30
	BRControl *_startPositionControl;	// 52 = 0x34
	BRControl *_dimControl;	// 56 = 0x38
	BRControl *_dimPanel;	// 60 = 0x3c
	CGRect _endPositionControlFrame;	// 64 = 0x40
	CGRect _startPositionControlFrame;	// 80 = 0x50
	CGRect _dimControlFrame;	// 96 = 0x60
	BRBoxListControl *_contextBox;	// 112 = 0x70
	int _dimOption;	// 116 = 0x74
	NSTimer *_autoDismissTimer;	// 120 = 0x78
}
@property(retain) BRControl *dimControl;	// G=0x366820f5; S=0x366820b5; converted property
@property(assign) int dimOption;	// G=0x36682125; S=0x36682105; converted property
@property(retain) BRControl *endPositionControl;	// G=0x366820a5; S=0x36682065; converted property
@property(assign) BOOL isVisible;	// G=0x36682501; S=0x366823ed; converted property
@property(retain) id providers;	// G=0x36681ff5; S=0x36681fb9; converted property
@property(retain) BRControl *startPositionControl;	// G=0x36682055; S=0x36682015; converted property
- (id)init;	// 0x36681cd5
- (void)_addAnimationsForDisplayState:(BOOL)displayState;	// 0x36682551
- (void)_autoDismissTimerFired:(id)fired;	// 0x3668252d
- (CGRect)_dimControlFrame;	// 0x36682eb5
- (void)_dissmissAnimationComplete;	// 0x36682c55
- (CGRect)_endPositionControlFrame;	// 0x36682c7d
- (CGRect)_startPositionControlFrame;	// 0x36682d99
- (BOOL)brEventAction:(id)action;	// 0x36681eed
- (void)controlWasDeactivated;	// 0x36681e99
- (void)dealloc;	// 0x36681dfd
// converted property getter: - (id)dimControl;	// 0x366820f5
// converted property getter: - (int)dimOption;	// 0x36682125
// converted property getter: - (id)endPositionControl;	// 0x366820a5
// converted property getter: - (BOOL)isVisible;	// 0x36682501
- (void)layoutSubcontrols;	// 0x36682135
// converted property getter: - (id)providers;	// 0x36681ff5
// converted property setter: - (void)setDimControl:(id)control;	// 0x366820b5
// converted property setter: - (void)setDimOption:(int)option;	// 0x36682105
// converted property setter: - (void)setEndPositionControl:(id)control;	// 0x36682065
// converted property setter: - (void)setIsVisible:(BOOL)visible;	// 0x366823ed
- (void)setProvider:(id)provider;	// 0x36681f79
// converted property setter: - (void)setProviders:(id)providers;	// 0x36681fb9
// converted property setter: - (void)setStartPositionControl:(id)control;	// 0x36682015
// converted property getter: - (id)startPositionControl;	// 0x36682055
@end

