//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

@class BRImageControl, BRMarqueeTextControl, BRTextControl;

@interface BRComboMenuItemLayer : BRControl
{
    BRControl *_background;
    BRImageControl *_thumbnailLayer;
    id <BRImageProxy> _imageProxy;
    BRMarqueeTextControl *_titleLayer;
    BRTextControl *_subtitleLayer;
    BRTextControl *_leftTextLayer;
    BRTextControl *_middleTextLayer;
    BRImageControl *_bottomRightImageLayer;
    BRImageControl *_topRightImageLayer;
    float _thumbnailPaddingFactor;
    float _thumbnailLayerAspect;
}

- (void)_artworkAssetLoadedNotification:(id)arg1;
- (id)_comboMenuItemSubtitleTextAttributes;
- (id)_comboMenuItemTitleTextAttributes;
- (void)_setThumbnail:(id)arg1;
- (id)accessibilityLabel;
- (id)axSelectedItemText;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (void)dealloc;
- (float)defaultRowHeight;
- (struct CGRect)focusCursorFrame;
- (id)init;
- (BOOL)isAccessibilityElement;
- (void)layoutSubcontrols;
- (void)setBottomRightImage:(id)arg1;
- (void)setLeftText:(id)arg1;
- (void)setMiddleText:(id)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setThumbnailImageProxy:(id)arg1;
- (void)setThumbnailLayerAspectRatio:(float)arg1;
- (void)setThumbnailPaddingFactor:(float)arg1;
- (void)setTitle:(id)arg1;
- (void)setTopRightImage:(id)arg1;
- (id)subtitle;
- (float)thumbnailLayerAspectRatio;
- (float)thumbnailPaddingFactor;
- (id)title;

@end

