//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

@class BRCursorLayer, BRHorizontalSegmentedWidget, NSTimer;

@interface BRCursorControl : BRControl
{
    BRControl *_trackedControl;
    BRControl *_previousTrackedControl;
    BRCursorLayer *_cursorLayer;
    int _style;
    BOOL _cursorInactive;
    BRHorizontalSegmentedWidget *_previousBadge;
    BRHorizontalSegmentedWidget *_badge;
    NSTimer *_removePreviousBadgeTimer;
    BOOL _cursorTrackingDisabledWhenAvoidsCursor;
}

- (void)_addCursor;
- (void)_cursorFrameChanged:(id)arg1;
- (void)_focusChanged:(id)arg1;
- (void)_removeCursor;
- (void)_removePreviousBadgeTimerFired:(id)arg1;
- (void)_removePreviousTrackedControl;
- (void)_trackFocusedControl:(id)arg1;
- (void)_trackedBadgeUpdated:(id)arg1;
- (void)_updateBadgeForTrackedControl;
- (void)_updateCursorPositioning;
- (void)_updateMyBadge:(id *)arg1 withTrackedControl:(id)arg2;
- (void)_updatePreviousBadge;
- (void)controlWasActivated;
- (BOOL)cursorInactive;
- (id)cursorLayer;
- (int)cursorStyle;
@property(nonatomic) BOOL cursorTrackingDisabledWhenAvoidsCursor; // @synthesize cursorTrackingDisabledWhenAvoidsCursor=_cursorTrackingDisabledWhenAvoidsCursor;
- (void)dealloc;
- (id)init;
- (void)layoutSubcontrols;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)preferredActionForKey:(id)arg1;
- (void)setCursorInactive:(BOOL)arg1;
- (void)setCursorStyle:(int)arg1;
- (void)setOpacity:(float)arg1;

@end

