/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSTimer, NSDictionary;
@protocol BRProvider, BRCyclerDelegate, BRCyclerDataSource;

@interface BRCyclerControl : BRControl {
@private
	id<BRProvider> _provider;	// 48 = 0x30
	double _interval;	// 52 = 0x34
	double _startInterval;	// 60 = 0x3c
	long _index;	// 68 = 0x44
	long _startIndex;	// 72 = 0x48
	BOOL _returnsToStart;	// 76 = 0x4c
	NSTimer *_crossFadeTimer;	// 80 = 0x50
	BRControl *_control;	// 84 = 0x54
	NSDictionary *_subcontrolMetadata;	// 88 = 0x58
	BOOL _initialDisplayOccurred;	// 92 = 0x5c
	id<BRCyclerDataSource> _dataSource;	// 96 = 0x60
	id<BRCyclerDelegate> _delegate;	// 100 = 0x64
	BOOL _startsOnActivate;	// 104 = 0x68
}
@property(assign, nonatomic) id<BRCyclerDataSource> dataSource;	// G=0x36687535; S=0x36686e81; @synthesize=_dataSource
@property(assign, nonatomic) id<BRCyclerDelegate> delegate;	// G=0x36687545; S=0x36687555; @synthesize=_delegate
@property(assign) double interval;	// G=0x366872a9; S=0x36687231; converted property
@property(assign) BOOL returnsToStart;	// G=0x36687221; S=0x36687211; converted property
@property(assign) long startIndex;	// G=0x36687201; S=0x366870cd; converted property
@property(assign) double startInterval;	// G=0x366872d5; S=0x366872c1; converted property
@property(assign, nonatomic) BOOL startsOnActivate;	// G=0x36687565; S=0x36687575; @synthesize=_startsOnActivate
@property(readonly, retain) NSDictionary *subcontrolMetadata;	// G=0x3668732d; converted property
+ (id)cyclerWithProvider:(id)provider;	// 0x36686c7d
- (id)init;	// 0x36686cc5
- (id)initWithProvider:(id)provider;	// 0x36686d0d
- (void)_commonInit;	// 0x366879e9
- (void)_crossFade:(id)fade;	// 0x36687595
- (void)_providerUpdated:(id)updated;	// 0x36687585
- (void)_returnToStart;	// 0x36687999
- (void)_startCrossFadeTimer;	// 0x3668789d
- (void)_stopCrossFadeTimer;	// 0x36687965
- (id)accessibilityLabel;	// 0x366874a9
- (void)controlWasActivated;	// 0x36686eed
- (void)controlWasDeactivated;	// 0x36686f69
- (void)controlWasFocused;	// 0x36686fbd
- (void)controlWasUnfocused;	// 0x3668703d
- (void)cycle;	// 0x36687111
// declared property getter: - (id)dataSource;	// 0x36687535
- (void)dealloc;	// 0x36686ddd
// declared property getter: - (id)delegate;	// 0x36687545
// converted property getter: - (double)interval;	// 0x366872a9
- (void)layoutSubcontrols;	// 0x3668744d
- (id)preferredActionForKey:(id)key;	// 0x3668733d
- (void)reload;	// 0x36687125
// converted property getter: - (BOOL)returnsToStart;	// 0x36687221
// declared property setter: - (void)setDataSource:(id)source;	// 0x36686e81
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x36687555
// converted property setter: - (void)setInterval:(double)interval;	// 0x36687231
// converted property setter: - (void)setReturnsToStart:(BOOL)start;	// 0x36687211
// converted property setter: - (void)setStartIndex:(long)index;	// 0x366870cd
// converted property setter: - (void)setStartInterval:(double)interval;	// 0x366872c1
// declared property setter: - (void)setStartsOnActivate:(BOOL)activate;	// 0x36687575
- (void)setSubcontrolMetaData:(id)data;	// 0x366872ed
- (void)start;	// 0x36687101
// converted property getter: - (long)startIndex;	// 0x36687201
// converted property getter: - (double)startInterval;	// 0x366872d5
// declared property getter: - (BOOL)startsOnActivate;	// 0x36687565
// converted property getter: - (id)subcontrolMetadata;	// 0x3668732d
@end

