/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"

@class NSMutableDictionary;

@interface BRDarwinNotificationTranslator : BRSingleton {
@private
	NSMutableDictionary *_registrations;	// 4 = 0x4
}
+ (BOOL)deregisterDarwinNotification:(const char *)notification;	// 0x3675a149
+ (int)notificationTokenForDarwinNotification:(const char *)darwinNotification;	// 0x3675a181
+ (BOOL)registerDarwinNotification:(const char *)notification sendsNotificationNamed:(id)named;	// 0x3675a10d
+ (void)setSingleton:(id)singleton;	// 0x36759f8d
+ (id)singleton;	// 0x36759f7d
- (id)init;	// 0x36759f9d
- (BOOL)_deregisterDarwinNotification:(const char *)notification;	// 0x3675a4c9
- (BOOL)_registerDarwinNotification:(const char *)notification sendsNotificationNamed:(id)named;	// 0x3675a1e9
- (id)_registrationForDarwinNotification:(const char *)darwinNotification;	// 0x3675a5e1
- (id)_registrationForToken:(int)token;	// 0x3675a629
- (void)dealloc;	// 0x3675a001
@end

