//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

#import "BRProvider.h"

@class BRDataStore;

@interface BRDataStoreProvider : NSObject <BRProvider>
{
    id <BRControlFactory> _controlFactory;
    BRDataStore *_dataStore;
}

+ (id)providerWithDataStore:(id)arg1;
+ (id)providerWithDataStore:(id)arg1 controlFactory:(id)arg2;
- (void)_databaseMessagesSuppressed:(id)arg1;
- (void)_databaseObjectWasAdded:(id)arg1;
- (void)_databaseObjectWasModified:(id)arg1;
- (void)_databaseObjectWillBeDeleted:(id)arg1;
- (void)_hostAvailabilityChanged:(id)arg1;
- (void)_updateDataIfNeeded:(id)arg1;
- (id)controlFactory;
- (id)data;
- (id)dataAtIndex:(long)arg1;
- (long)dataCount;
- (id)dataStore;
- (void)dealloc;
- (id)hashForDataAtIndex:(long)arg1;
- (id)initWithDataStore:(id)arg1;
- (id)initWithDataStore:(id)arg1 controlFactory:(id)arg2;
- (void)setControlFactory:(id)arg1;

@end

