/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRMediaHost.h"


__attribute__((visibility("hidden")))
@interface BRDAAPMediaHost : BRMediaHost {
}
+ (id)daapMediaHostWithHostInfo:(id)hostInfo;	// 0x3673a481
- (id)init;	// 0x3673a4bd
- (id)initWithHostInfo:(id)hostInfo;	// 0x3673a4d1
- (id)hostname;	// 0x3673a535
@end

