/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRProvider.h"

@class BRProviderGroup;

@interface BRDependentProvider : NSObject <BRProvider> {
@private
	id<BRProvider> _provider;	// 4 = 0x4
	BRProviderGroup *_providerGroup;	// 8 = 0x8
	long _threshold;	// 12 = 0xc
	BOOL _hidden;	// 16 = 0x10
}
@property(readonly, assign) long threshold;	// G=0x36715bed; converted property
+ (id)providerWithDependentProvider:(id)dependentProvider providers:(id)providers threshold:(long)threshold;	// 0x36715819
- (id)initWithDependentProvider:(id)dependentProvider providers:(id)providers threshold:(long)threshold;	// 0x36715871
- (void)_groupDataCountChanged:(id)changed;	// 0x36715bfd
- (void)_providerDataSetChanged:(id)changed;	// 0x36715cc1
- (void)_providerItemsModified:(id)modified;	// 0x36715d19
- (id)controlFactory;	// 0x36715af9
- (id)dataAtIndex:(long)index;	// 0x36715b55
- (long)dataCount;	// 0x36715b19
- (void)dealloc;	// 0x36715a69
- (id)hashForDataAtIndex:(long)index;	// 0x36715b91
- (id)providers;	// 0x36715bcd
// converted property getter: - (long)threshold;	// 0x36715bed
@end

