//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRAuthenticationManager.h>

@class BRAccountType;

@interface BRDefaultAuthenticationManager : BRAuthenticationManager
{
    BRAccountType *_accountType;
}

- (id)_basicAccount;
- (void)_markAsPreferredAccount:(id)arg1;
- (void)_preferredAccountRemoved:(id)arg1;
@property(readonly) BRAccountType *accountType; // @synthesize accountType=_accountType;
- (void)dealloc;
- (id)initWithAccountType:(id)arg1;
- (id)initWithAccountType:(id)arg1 authenticatorCreation:(CDUnknownBlockType)arg2;
- (id)preferredAccount;

@end

