/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSTimer, NSAttributedString, NSString, BRMediaPlayer, BRImage;
@protocol BRMediaAsset;

__attribute__((visibility("hidden")))
@interface BRDescriptionOverlayControl : BRControl {
@private
	BRControl *_customOverlay;	// 48 = 0x30
	CGColorRef _fillColor;	// 52 = 0x34
	BRMediaPlayer *_player;	// 56 = 0x38
	id<BRMediaAsset> _asset;	// 60 = 0x3c
	NSString *_imageID;	// 64 = 0x40
	BRImage *_image;	// 68 = 0x44
	BRImage *_ratingImage;	// 72 = 0x48
	NSAttributedString *_title;	// 76 = 0x4c
	NSAttributedString *_publisher;	// 80 = 0x50
	NSAttributedString *_description;	// 84 = 0x54
	NSAttributedString *_pressAndHoldDescription;	// 88 = 0x58
	BOOL _showPressAndHoldDescription;	// 92 = 0x5c
	NSTimer *_fadeTimer;	// 96 = 0x60
}
- (id)init;	// 0x36687a3d
- (void)_fadeOverlay:(id)overlay;	// 0x366894ed
- (void)_hideOverlay;	// 0x36689415
- (void)_imageUpdated:(id)updated;	// 0x3668932d
- (id)_pressAndHoldDescriptionAttributes;	// 0x36689259
- (BOOL)_pressAndHoldOptionAvailable;	// 0x36689279
- (void)_setImage:(id)image;	// 0x36689205
- (void)_showOverlay;	// 0x3668948d
- (void)_showOverlayWithTimeout:(float)timeout;	// 0x36688bf9
- (void)_updateCurrentMediaInfo;	// 0x36688c95
- (id)accessibilityLabel;	// 0x36688b51
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x36689615
- (void)dealloc;	// 0x36687ae1
- (void)drawInContext:(CGContextRef)context;	// 0x36687f65
- (BOOL)hasContent;	// 0x36687cc5
- (void)hideOverlay;	// 0x36687d39
- (BOOL)isAccessibilityElement;	// 0x36688bf5
- (void)layoutSubcontrols;	// 0x36687e5d
- (void)setAsset:(id)asset;	// 0x36687c61
- (void)setPlayer:(id)player;	// 0x36687c21
- (void)showOverlayWithLongTimeout;	// 0x36687d49
- (void)showOverlayWithLongTimeoutFromTouchRemote;	// 0x36687e01
- (void)showOverlayWithShortTimeout;	// 0x36687da5
@end

