/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class BRWindow, NSString, BRControl;

@interface BRDialog : NSObject {
@private
	BRWindow *_window;	// 4 = 0x4
	BRControl *_control;	// 8 = 0x8
	NSString *_identifier;	// 12 = 0xc
}
@property(readonly, retain) BRControl *control;	// G=0x36726715; converted property
@property(readonly, retain) NSString *identifier;	// G=0x3672674d; converted property
+ (void)dismissDialogWithIdentifier:(id)identifier;	// 0x36726f91
+ (void)initialize;	// 0x36726491
+ (BOOL)isDialogCurrentlyPosted;	// 0x36726b05
+ (BOOL)isDialogPostedWithIdentifier:(id)identifier;	// 0x36726a9d
+ (void)postDialogWithControl:(id)control identifier:(id)identifier;	// 0x36726b31
+ (void)postDialogWithControl:(id)control identifier:(id)identifier style:(int)style opaque:(BOOL)opaque;	// 0x36726909
+ (void)postModalDialog:(id)dialog;	// 0x36726b9d
+ (void)postModalDialogWithControl:(id)control identifier:(id)identifier;	// 0x36726b55
+ (void)postModalDialogWithControl:(id)control identifier:(id)identifier style:(int)style opaque:(BOOL)opaque;	// 0x36726df9
+ (void)postModalDialogWithController:(id)controller identifier:(id)identifier;	// 0x36726b79
+ (void)postModalDialogWithController:(id)controller identifier:(id)identifier style:(int)style opaque:(BOOL)opaque;	// 0x36726e69
- (id)initWithControl:(id)control identifier:(id)identifier style:(int)style opaque:(BOOL)opaque;	// 0x367264f5
- (void)_dialogStackBankrupt:(id)bankrupt;	// 0x36727251
- (void)_transitionCompleted:(id)completed;	// 0x36727289
// converted property getter: - (id)control;	// 0x36726715
- (void)dealloc;	// 0x3672665d
// converted property getter: - (id)identifier;	// 0x3672674d
- (void)transitionIn;	// 0x36726785
- (void)transitionOut;	// 0x36726809
@end

