//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



#import "BRControlFactory-Protocol.h"
#import "BRControlHeightFactory-Protocol.h"
#import "BRProvider-Protocol.h"

@class BRDividerControl;

@interface BRDividerProvider : NSObject <BRControlFactory, BRControlHeightFactory, BRProvider>
{
    id <BRProvider> _provider;
    BRDividerControl *_topDivider;
    BOOL _dividerHidden;
    BOOL _showDivider;
}

+ (id)providerWithProvider:(id)arg1;
- (void)_providerDataSetChanged:(id)arg1;
- (void)_providerItemsModified:(id)arg1;
- (id)_shiftRangesDown:(id)arg1;
- (BOOL)_shouldShowDivider;
- (void)_updateTopDividerControl;
- (id)accessibilityLabel;
- (void)addDividerWithLabel:(id)arg1;
- (void)addDividerWithLabel:(id)arg1 andOrientation:(int)arg2;
- (id)controlFactory;
- (id)controlForData:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (id)dataAtIndex:(long)arg1;
- (long)dataCount;
- (void)dealloc;
- (id)divider;
- (BOOL)dividerHidden;
- (BOOL)dividerVisible;
- (id)hashForDataAtIndex:(long)arg1;
- (float)heightForControlForData:(id)arg1 requestedBy:(id)arg2;
- (id)initWithProvider:(id)arg1;
- (id)provider;
- (void)removeDivider;
- (void)setDividerHidden:(BOOL)arg1;

@end

