//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRDropShadowControl, BRReflectedImageControl, BRTextControl;

@interface BRDownloadPlayableAlertControl : BRControl
{
    BRDropShadowControl *_shadowControl;
    BRControl *_dialogBox;
    BRReflectedImageControl *_imageControl;
    BRTextControl *_titleControl;
    BRTextControl *_clockStartWarningControl;
    BRTextControl *_directionsControl;
    id <BRMediaAsset> _asset;
    double _activationTime;
}

+ (void)_imageLoadedOrErrored:(id)arg1 withImage:(id)arg2;
+ (void)_imageNotAvailable:(id)arg1;
+ (void)_imageUpdated:(id)arg1;
+ (void)_postPlayableAlertForAsset:(id)arg1 withAssetImage:(id)arg2;
+ (void)postPlayableAlertForAsset:(id)arg1;
- (BOOL)_dialogShouldBePosted;
- (BOOL)_isVideoPlayerControlActive;
- (void)_playAsset;
- (void)_postIfReady:(id)arg1;
- (void)_postWithControl:(id)arg1;
- (void)_setAsset:(id)arg1;
- (void)_setImage:(id)arg1;
- (id)accessibilityLabel;
- (BOOL)brEventAction:(id)arg1;
- (void)controlWasActivated;
- (void)dealloc;
- (id)init;
- (BOOL)isAccessibilityElement;
- (void)layoutSubcontrols;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

