/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSDictionary;

@interface BREvent : NSObject {
@private
	NSDictionary *_eventDictionary;	// 4 = 0x4
	int _action;	// 8 = 0x8
	double _timeStamp;	// 12 = 0xc
	int _value;	// 20 = 0x14
	unsigned _originator;	// 24 = 0x18
	BOOL _allowRetrigger;	// 28 = 0x1c
	BOOL _retrigger;	// 29 = 0x1d
}
@property(readonly, assign) BOOL allowRetrigger;	// G=0x3666c169; converted property
@property(readonly, retain) NSDictionary *eventDictionary;	// G=0x3666c159; converted property
@property(readonly, assign) unsigned originator;	// G=0x3666c149; converted property
@property(readonly, assign) double timeStamp;	// G=0x3666c131; converted property
@property(readonly, assign) int value;	// G=0x3666c0fd; converted property
+ (id)eventWithAction:(int)action value:(int)value;	// 0x3666ba29
+ (id)eventWithAction:(int)action value:(int)value atTime:(double)time;	// 0x3666ba69
+ (id)eventWithAction:(int)action value:(int)value atTime:(double)time originator:(unsigned)originator;	// 0x3666bab5
+ (id)eventWithAction:(int)action value:(int)value atTime:(double)time originator:(unsigned)originator eventDictionary:(id)dictionary allowRetrigger:(BOOL)retrigger;	// 0x3666bb05
+ (id)eventWithEvent:(id)event originator:(unsigned)originator;	// 0x3666bbfd
+ (id)eventWithEvent:(id)event originator:(unsigned)originator eventDictionary:(id)dictionary allowRetrigger:(BOOL)retrigger;	// 0x3666bb61
- (id)initWithAction:(int)action value:(int)value;	// 0x3666bcc1
- (id)initWithAction:(int)action value:(int)value atTime:(double)time;	// 0x3666bcf5
- (id)initWithAction:(int)action value:(int)value atTime:(double)time originator:(unsigned)originator;	// 0x3666bd21
- (id)initWithAction:(int)action value:(int)value atTime:(double)time originator:(unsigned)originator eventDictionary:(id)dictionary allowRetrigger:(BOOL)retrigger;	// 0x3666bd5d
// converted property getter: - (BOOL)allowRetrigger;	// 0x3666c169
- (void)dealloc;	// 0x3666be09
- (id)description;	// 0x3666be55
// converted property getter: - (id)eventDictionary;	// 0x3666c159
- (BOOL)isEqual:(id)equal;	// 0x3666c069
- (void)makeRetriggerEvent;	// 0x3666c11d
// converted property getter: - (unsigned)originator;	// 0x3666c149
- (int)remoteAction;	// 0x3666c0ed
- (BOOL)retriggerEvent;	// 0x3666c10d
// converted property getter: - (double)timeStamp;	// 0x3666c131
// converted property getter: - (int)value;	// 0x3666c0fd
@end

