/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRTransitionControl.h"


__attribute__((visibility("hidden")))
@interface BRFadeThroughBlackTransitionControl : BRTransitionControl {
@private
	BRControl *_shroud;	// 56 = 0x38
}
- (void)_addShroud;	// 0x366db385
- (void)_removeShroud;	// 0x366db431
- (void)_transitionInCompleted:(id)completed;	// 0x366db7c1
- (void)_transitionOutCompleted:(id)completed;	// 0x366db831
- (void)_updateContentForTransitionState;	// 0x366db471
- (void)dealloc;	// 0x366db1fd
- (void)layoutSubcontrols;	// 0x366db2e9
- (void)setContent:(id)content;	// 0x366db249
- (void)setTransitionedIn:(BOOL)anIn;	// 0x366db289
@end

