//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRSingleton.h>

@class NSMutableDictionary;

@interface BRFeatureManager : BRSingleton
{
    NSMutableDictionary *_featureDatabase;
    NSMutableDictionary *_featureDatabaseOverrides;
    NSMutableDictionary *_featureCodeLookupTable;
}

+ (void)setSingleton:(id)arg1;
+ (id)singleton;
- (void)_buildFeatureCodeLookupTable;
- (id)_featureNameForCode:(id)arg1;
- (void)_loadSavedCodes;
- (void)_markFeatureNamed:(id)arg1 enabled:(BOOL)arg2 inTable:(id)arg3;
- (id)_merchantWithFeatureCode:(id)arg1;
- (void)_notifyEnabledStateChangedForFeatureNamed:(id)arg1;
- (void)_saveFeatureCodes:(id)arg1;
- (id)allFeatures;
- (id)availableFeatures;
- (void)dealloc;
- (void)disableFeatureNamed:(id)arg1;
- (void)enableFeatureNamed:(id)arg1;
- (id)init;
- (BOOL)isFeatureEnabled:(id)arg1;
- (void)resetFeatures;
- (void)toggleSettingForCode:(id)arg1;

@end

