//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

@protocol BRFocusContainer <NSObject>
- (struct CGSize)boundsForFocusCandidate:(id)arg1;
- (id)debugDescriptionForFocusCandidate:(id)arg1;
- (BOOL)eligibilityForFocusCandidate:(id)arg1;
- (id)focusCandidates;
- (id)focusObjectForCandidate:(id)arg1;
- (struct CGPoint)positionForFocusCandidate:(id)arg1;
@end

