/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "NSObject.h"


@protocol BRFocusContainer <NSObject>
- (CGSize)boundsForFocusCandidate:(id)focusCandidate;
- (id)debugDescriptionForFocusCandidate:(id)focusCandidate;
- (BOOL)eligibilityForFocusCandidate:(id)focusCandidate;
- (id)focusCandidates;
- (id)focusObjectForCandidate:(id)candidate;
- (CGPoint)positionForFocusCandidate:(id)focusCandidate;
@end

