/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRType.h"


@interface BRGenre : BRType {
}
+ (id)classical;	// 0x36735029
+ (id)pop;	// 0x36734f39
+ (id)rock;	// 0x36735119
- (id)displayString;	// 0x36735209
@end

