/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"
#import "BRContainerViewCell.h"

@class BRContainerViewDataCache, NSMutableArray, NSTimer, BRCursorControl;

@interface BRGridView : BRControl <BRContainerViewCell> {
@private
	int _mode;	// 48 = 0x30
	BRControl *_requester;	// 52 = 0x34
	NSRange _range;	// 56 = 0x38
	float _lastGapHeight;	// 64 = 0x40
	double _heightToRange;	// 68 = 0x44
	double _controlHeight;	// 76 = 0x4c
	XXStruct_qlg9jA _columWidth;	// 84 = 0x54
	XXStruct_qlg9jA _horizontalGap;	// 88 = 0x58
	XXStruct_qlg9jA _verticalGap;	// 92 = 0x5c
	float _leftMargin;	// 96 = 0x60
	float _rightMargin;	// 100 = 0x64
	float _bottomMargin;	// 104 = 0x68
	float _bottomMarginFactor;	// 108 = 0x6c
	float _topMargin;	// 112 = 0x70
	float _topMarginFactor;	// 116 = 0x74
	int _navigationBehavior;	// 120 = 0x78
	id _dataSource;	// 124 = 0x7c
	id _delegate;	// 128 = 0x80
	BRCursorControl *_trackingCursor;	// 132 = 0x84
	BOOL _needsReload;	// 136 = 0x88
	NSMutableArray *_editEventQueue;	// 140 = 0x8c
	long _loadIndex;	// 144 = 0x90
	NSTimer *_forceDisplayTimer;	// 148 = 0x94
	BOOL _followsLoadAndDisplayOnDemand;	// 152 = 0x98
	id _loadCompletionBlock;	// 156 = 0x9c
	BOOL _toldToLoad;	// 160 = 0xa0
	NSMutableArray *_completedIndexes;	// 164 = 0xa4
	BRContainerViewDataCache *_dataCache;	// 168 = 0xa8
	XXStruct_qlg9jA _itemHeight;	// 172 = 0xac
	long _defaultFocusIndex;	// 176 = 0xb0
}
@property(assign) float bottomMargin;	// G=0x36693f39; S=0x36693ea5; converted property
@property(assign) XXStruct_qlg9jA columnWidth;	// G=0x3669304d; S=0x3669303d; converted property
@property(retain) id cursor;	// G=0x36694c51; S=0x36694c11; converted property
@property(retain) id dataSource;	// G=0x36692f5d; S=0x36692f11; converted property
@property(assign, nonatomic) long defaultFocusIndex;	// G=0x36694381; S=0x36694391; @synthesize=_defaultFocusIndex
@property(assign) id delegate;	// G=0x36692f7d; S=0x36692f6d; converted property
@property(assign) XXStruct_qlg9jA horizontalGap;	// G=0x366930b1; S=0x36693069; converted property
@property(assign, nonatomic) XXStruct_qlg9jA itemHeight;	// G=0x36694355; S=0x36694371; @synthesize=_itemHeight
@property(assign) float leftMargin;	// G=0x366931b5; S=0x36693175; converted property
@property(assign, nonatomic) int navigationBehavior;	// G=0x366943a1; S=0x366943b1; @synthesize=_navigationBehavior
@property(assign) float rightMargin;	// G=0x36693205; S=0x366931c5; converted property
@property(assign) long selection;	// G=0x36692f9d; S=0x36692f8d; converted property
@property(assign) float topMargin;	// G=0x36693fdd; S=0x36693f49; converted property
@property(assign) XXStruct_qlg9jA verticalGap;	// G=0x36693125; S=0x366930cd; converted property
+ (id)_jitterPositionAnimation;	// 0x366970c5
+ (id)_jitterTransformAnimation;	// 0x366974b9
- (id)init;	// 0x36692b89
- (id)initWithLayout:(id)layout;	// 0x36692ce9
- (BOOL)_allDisplayComplete;	// 0x36696e21
- (void)_animationDidStartInDisplayMode:(id)_animation;	// 0x36695f1d
- (void)_animationDidStartInEditModeMode:(id)_animation;	// 0x36695f21
- (void)_animationDidStopInDisplayMode:(id)_animation finished:(BOOL)finished;	// 0x36695f25
- (void)_animationDidStopInEditMode:(id)_animation finished:(BOOL)finished;	// 0x36695f29
- (id)_completedIndexes;	// 0x36696d6d
- (id)_controlAtIndex:(long)index controls:(id)controls;	// 0x366965f1
- (long)_controlsInHeight:(double)height startingAt:(long)at actualHeight:(double *)height3;	// 0x36696185
- (long)_controlsInHeightBackwards:(double)heightBackwards startingAt:(long)at actualHeight:(double *)height;	// 0x36696279
- (id)_controlsInRange:(NSRange)range;	// 0x36696479
- (id)_createControlsInRange:(NSRange)range;	// 0x366963d5
- (void)_displayControlsForRowThatContainsIndex:(long)rowThatContainsIndex force:(bool)force;	// 0x36696a39
- (void)_focusChanged:(id)changed;	// 0x36697f5d
- (void)_forceDisplayTimerFired:(id)fired;	// 0x366969f9
- (CGRect)_frameForControlAtIndex:(long)index controls:(id)controls;	// 0x366955fd
- (CGRect)_frameForControlAtIndex:(long)index rowFrame:(CGRect)frame controls:(id)controls;	// 0x36695749
- (void)_frameRowInRange:(NSRange)range rowFrame:(CGRect)frame controls:(id)controls;	// 0x36695801
- (BOOL)_handleEventInDisplayMode:(id)displayMode;	// 0x36695a41
- (BOOL)_handleEventInEditMode:(id)editMode;	// 0x36695ce1
- (float)_heightOfControlAtIndex:(long)index controls:(id)controls;	// 0x36696075
- (double)_heightOfRowsInRange:(NSRange)range includeVerticalGap:(BOOL)gap controls:(id)controls;	// 0x366960c1
- (double)_heightToRange;	// 0x366953f9
- (long)_indexOfFocusedControl;	// 0x3669635d
- (void)_layoutSubcontrols;	// 0x36694d75
- (void)_loadControlWithIndex:(long)index start:(BOOL)start;	// 0x36696655
- (BOOL)_okToLoadWithIndex:(long)index;	// 0x36696921
- (float)_positionOfColumn:(long)column inRowWidth:(float)rowWidth cellWidth:(float *)width;	// 0x366954dd
- (void)_reloadIfNeeded;	// 0x36697fd5
- (void)_restorePersistentSavedSelection;	// 0x36697d55
- (float)_rowHeightForControlsInRange:(NSRange)range controls:(id)controls;	// 0x36696009
- (id)_setControlRange:(NSRange)range withHeightToRange:(double)range2;	// 0x36694c61
- (BOOL)_setMode:(int)mode;	// 0x366958a5
- (void)_setSelectedItemJiggling:(BOOL)jiggling;	// 0x36696ed1
- (void)_stopForceDisplayTimer;	// 0x366969c5
- (BOOL)_swapControlAtIndex:(long)index withControlAtIndex:(long)index2;	// 0x36697795
- (id)_swapPositionAnimationFromIndex:(long)index toIndex:(long)index2;	// 0x366976bd
- (double)_totalHeight;	// 0x366952f1
- (void)_updatePersistentSavedSelection;	// 0x36697e95
- (id)accessibilityControls;	// 0x366936e9
- (void)animationDidStart:(id)animation;	// 0x366941b5
- (void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0x366941f1
// converted property getter: - (float)bottomMargin;	// 0x36693f39
- (BOOL)brEventAction:(id)action;	// 0x36693c51
- (void)cancelContainerViewLoad;	// 0x366942d5
// converted property getter: - (XXStruct_qlg9jA)columnWidth;	// 0x3669304d
- (BOOL)controlAcceptsFocusAtIndex:(long)index;	// 0x366948bd
- (CGRect)controlFocusFrameAtIndex:(long)index;	// 0x36694b3d
- (CGRect)controlFrameAtIndex:(long)index;	// 0x36694a45
- (void)controlWasActivated;	// 0x3669379d
- (void)controlWasDeactivated;	// 0x36693841
- (unsigned)countOfCells;	// 0x36693705
// converted property getter: - (id)cursor;	// 0x36694c51
- (long)dataCount;	// 0x36692fbd
// converted property getter: - (id)dataSource;	// 0x36692f5d
- (void)dealloc;	// 0x36692e45
// declared property getter: - (long)defaultFocusIndex;	// 0x36694381
// converted property getter: - (id)delegate;	// 0x36692f7d
- (void)didFocusItemAtIndex:(long)index;	// 0x36694709
- (BOOL)didPlayItemAtIndex:(long)index;	// 0x36694861
- (BOOL)didSelectItemAtIndex:(long)index;	// 0x36694805
- (void)didUnFocusItemAtIndex:(long)index;	// 0x366947b1
- (void)focusControlAtIndex:(long)index;	// 0x3669491d
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x36693c91
- (void)grid:(id)grid didFocusItemAtIndex:(long)index;	// 0x36694345
- (void)grid:(id)grid didSelectItemAtIndex:(long)index;	// 0x36694351
- (void)grid:(id)grid didUnFocusItemAtIndex:(long)index;	// 0x3669434d
- (float)grid:(id)grid heightForItemAtIndex:(long)index;	// 0x36694339
- (id)grid:(id)grid itemAtIndex:(long)index;	// 0x36694335
- (void)grid:(id)grid willDisplayItemAtIndex:(long)index;	// 0x3669433d
- (long)grid:(id)grid willFocusItemAtIndex:(long)index;	// 0x36694341
- (void)grid:(id)grid willUnFocusItemAtIndex:(long)index;	// 0x36694349
- (float)heightForItemAtIndex:(long)index;	// 0x366945dd
- (float)heightOfControlAtIndex:(long)index;	// 0x366933cd
- (float)heightToMaximum:(float)maximum;	// 0x366932b9
// converted property getter: - (XXStruct_qlg9jA)horizontalGap;	// 0x366930b1
- (long)indexForItemID:(id)itemID;	// 0x36694581
- (unsigned)indexInCellsOfObject:(id)object;	// 0x36693715
- (id)initialFocus;	// 0x36693a21
- (id)itemAtIndex:(long)index;	// 0x366944d1
// declared property getter: - (XXStruct_qlg9jA)itemHeight;	// 0x36694355
- (id)itemIDAtIndex:(long)index;	// 0x36694529
- (void)layoutSubcontrols;	// 0x3669402d
// converted property getter: - (float)leftMargin;	// 0x366931b5
- (void)loadWithCompletionBlock:(id)completionBlock;	// 0x3669422d
// declared property getter: - (int)navigationBehavior;	// 0x366943a1
- (long)numberOfColumns;	// 0x366944b1
- (long)numberOfColumnsInGrid:(id)grid;	// 0x36694331
- (long)numberOfItems;	// 0x36694491
- (long)numberOfItemsInGrid:(id)grid;	// 0x3669432d
- (id)objectInCellsAtIndex:(unsigned)index;	// 0x3669375d
- (void)populateDataCache:(id)cache;	// 0x366943c1
- (float)positionOfColumn:(long)column;	// 0x36693375
- (void)reload;	// 0x36693401
- (void)reloadItemAtIndex:(long)index;	// 0x36693565
- (void)reloadItemsAtIndexes:(id)indexes;	// 0x36693605
- (void)restorePersistentSavedSelection;	// 0x366936d9
// converted property getter: - (float)rightMargin;	// 0x36693205
- (long)rowCount;	// 0x36692fcd
- (void)scrollingCompleted;	// 0x3669413d
- (void)selectItemAtIndex:(long)index;	// 0x36694481
- (long)selectedIndex;	// 0x36694471
- (id)selectedObject;	// 0x36692fad
// converted property getter: - (long)selection;	// 0x36692f9d
// converted property setter: - (void)setBottomMargin:(float)margin;	// 0x36693ea5
// converted property setter: - (void)setColumnWidth:(XXStruct_qlg9jA)width;	// 0x3669303d
// converted property setter: - (void)setCursor:(id)cursor;	// 0x36694c11
// converted property setter: - (void)setDataSource:(id)source;	// 0x36692f11
// declared property setter: - (void)setDefaultFocusIndex:(long)index;	// 0x36694391
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x36692f6d
- (void)setFollowsLoadAndDisplayOnDemand;	// 0x36694309
// converted property setter: - (void)setHorizontalGap:(XXStruct_qlg9jA)gap;	// 0x36693069
- (void)setIgnoreLoadAndDisplayOnDemand;	// 0x36694305
- (void)setIgnoreLoadAndDisplayOnDemandDisableAnimations:(BOOL)animations;	// 0x3669431d
// declared property setter: - (void)setItemHeight:(XXStruct_qlg9jA)height;	// 0x36694371
// converted property setter: - (void)setLeftMargin:(float)margin;	// 0x36693175
// declared property setter: - (void)setNavigationBehavior:(int)behavior;	// 0x366943b1
- (void)setNeedsReload;	// 0x36693685
- (void)setReadyToDisplay;	// 0x36694301
// converted property setter: - (void)setRightMargin:(float)margin;	// 0x366931c5
// converted property setter: - (void)setSelection:(long)selection;	// 0x36692f8d
// converted property setter: - (void)setTopMargin:(float)margin;	// 0x36693f49
// converted property setter: - (void)setVerticalGap:(XXStruct_qlg9jA)gap;	// 0x366930cd
- (void)setVerticalMargins:(float)margins;	// 0x36693141
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x3669403d
// converted property getter: - (float)topMargin;	// 0x36693fdd
- (void)updatePersistentSavedSelection;	// 0x366936c9
// converted property getter: - (XXStruct_qlg9jA)verticalGap;	// 0x36693125
- (id)visibleControlAtIndex:(long)index;	// 0x3669326d
- (id)visibleControlsWithRange:(NSRange *)range;	// 0x36693215
- (NSRange)visibleRange;	// 0x36693251
- (void)visibleScrollRectChanged;	// 0x36693fed
- (void)willDisplayItemAtIndex:(long)index;	// 0x3669465d
- (long)willFocusItemAtIndex:(long)index;	// 0x366946b1
- (void)willUnFocusItemAtIndex:(long)index;	// 0x3669475d
- (void)windowMaxBoundsChanged;	// 0x3669394d
@end

