//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRImageControl, BRTextControl;

@interface BRHeaderControl : BRControl
{
    BRTextControl *_title;
    BRTextControl *_subtitle;
    BRImageControl *_icon;
    float _iconHorizontalOffset;
    float _iconKerningFactor;
    float _iconScaleFactor;
    float _iconEdgeSpace;
    int _iconPosition;
    BOOL _titleHidesIcon;
}

- (id)accessibilityLabel;
- (void)controlWasActivated;
- (void)dealloc;
- (id)icon;
- (float)iconEdgeSpace;
- (struct CGRect)iconFrame;
- (float)iconHorizontalOffset;
- (float)iconKerningFactor;
- (int)iconPosition;
- (float)iconScaleFactor;
- (id)init;
- (void)layoutSubcontrols;
- (void)setIcon:(id)arg1 horizontalOffset:(float)arg2 kerningFactor:(float)arg3;
- (void)setIcon:(id)arg1 position:(int)arg2 edgeSpace:(float)arg3;
- (void)setIconEdgeSpace:(float)arg1;
- (void)setIconHidden:(BOOL)arg1;
- (void)setIconHorizontalOffset:(float)arg1;
- (void)setIconKerningFactor:(float)arg1;
- (void)setIconPosition:(int)arg1;
- (void)setIconScaleFactor:(float)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setSubtitle:(id)arg1 withAttributes:(id)arg2;
- (void)setTitle:(id)arg1;
- (void)setTitle:(id)arg1 withAttributes:(id)arg2;
@property(nonatomic) BOOL titleHidesIcon; // @synthesize titleHidesIcon=_titleHidesIcon;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)subtitle;
- (id)title;

@end

