/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRInputMethod.h"


__attribute__((visibility("hidden")))
@interface BRHexInputMethod : BRInputMethod {
}
- (id)_keyboardsForTextEntryStyle:(int)textEntryStyle;	// 0x366c5105
- (id)name;	// 0x366c50f5
- (BOOL)usesCandidateDisplayForKeyboard:(id)keyboard;	// 0x366c5101
@end

