/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BREvent.h"


@interface BRHIDEvent : BREvent {
@private
	unsigned short _page;	// 30 = 0x1e
	unsigned short _usage;	// 32 = 0x20
	unsigned long long _extendedSignature;	// 36 = 0x24
}
@property(readonly, assign) unsigned long long extendedSignature;	// G=0x3666c779; converted property
@property(readonly, assign) unsigned short page;	// G=0x3666c759; converted property
@property(readonly, assign) unsigned short usage;	// G=0x3666c769; converted property
+ (id)eventWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value;	// 0x3666c279
+ (id)eventWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value atTime:(double)time;	// 0x3666c229
+ (id)eventWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value extendedSignature:(unsigned long long)signature;	// 0x3666c1d5
+ (id)eventWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value extendedSignature:(unsigned long long)signature atTime:(double)time;	// 0x3666c179
- (id)initWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value;	// 0x3666c2c1
- (id)initWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value atTime:(double)time;	// 0x3666c345
- (id)initWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value extendedSignature:(unsigned long long)signature;	// 0x3666c2fd
- (id)initWithPage:(unsigned short)page usage:(unsigned short)usage value:(int)value extendedSignature:(unsigned long long)signature atTime:(double)time;	// 0x3666c379
- (id)description;	// 0x3666c531
// converted property getter: - (unsigned long long)extendedSignature;	// 0x3666c779
- (BOOL)isEqual:(id)equal;	// 0x3666c665
// converted property getter: - (unsigned short)page;	// 0x3666c759
// converted property getter: - (unsigned short)usage;	// 0x3666c769
@end

