/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, NSMutableArray, BRImage, BRImageControl;

@interface BRHorizontalSegmentedWidget : BRControl {
@private
	BRImage *_leftImage;	// 48 = 0x30
	BRImage *_centerImage;	// 52 = 0x34
	BRImage *_rightImage;	// 56 = 0x38
	BRTextControl *_textControl;	// 60 = 0x3c
	BRImageControl *_leftEndLayer;	// 64 = 0x40
	NSMutableArray *_centerLayers;	// 68 = 0x44
	BRImageControl *_rightEndLayer;	// 72 = 0x48
	float _animationDuration;	// 76 = 0x4c
	BOOL _animationEnabled;	// 80 = 0x50
	int _numSegments;	// 84 = 0x54
}
@property(assign) float animationDuration;	// G=0x366e8689; S=0x366e8525; converted property
@property(retain) id attributedString;	// G=0x366e8801; S=0x366e8739; converted property
@property(readonly, retain) BRImage *centerImage;	// G=0x366e84d5; converted property
@property(readonly, retain) NSMutableArray *centerLayers;	// G=0x366e8dd1; converted property
@property(readonly, retain) BRImageControl *leftEndLayer;	// G=0x366e8dc1; converted property
@property(readonly, retain) BRImage *leftImage;	// G=0x366e84c5; converted property
@property(readonly, retain) BRImageControl *rightEndLayer;	// G=0x366e8e01; converted property
@property(readonly, retain) BRImage *rightImage;	// G=0x366e84e5; converted property
@property(assign) BOOL sublayerAnimationEnabled;	// G=0x366e86a9; S=0x366e8699; converted property
- (id)init;	// 0x366e81f9
- (void)_reloadSegments;	// 0x366e8e31
- (id)accessibilityLabel;	// 0x366e8e11
// converted property getter: - (float)animationDuration;	// 0x366e8689
// converted property getter: - (id)attributedString;	// 0x366e8801
// converted property getter: - (id)centerImage;	// 0x366e84d5
- (id)centerLayer;	// 0x366e8de1
// converted property getter: - (id)centerLayers;	// 0x366e8dd1
- (void)dealloc;	// 0x366e8241
- (void)layoutSubcontrols;	// 0x366e8941
// converted property getter: - (id)leftEndLayer;	// 0x366e8dc1
// converted property getter: - (id)leftImage;	// 0x366e84c5
// converted property getter: - (id)rightEndLayer;	// 0x366e8e01
// converted property getter: - (id)rightImage;	// 0x366e84e5
// converted property setter: - (void)setAnimationDuration:(float)duration;	// 0x366e8525
// converted property setter: - (void)setAttributedString:(id)string;	// 0x366e8739
- (void)setLeftFile:(id)file centerFile:(id)file2 rightFile:(id)file3;	// 0x366e8305
- (void)setLeftImage:(id)image centerImage:(id)image2 rightImage:(id)image3;	// 0x366e83b9
- (void)setNumSegments:(int)segments;	// 0x366e84f5
// converted property setter: - (void)setSublayerAnimationEnabled:(BOOL)enabled;	// 0x366e8699
- (void)setText:(id)text withAttributes:(id)attributes;	// 0x366e86b9
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x366e8821
// converted property getter: - (BOOL)sublayerAnimationEnabled;	// 0x366e86a9
@end

