/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <NSObject.h> // Unknown library

@class NSMutableDictionary, NSLock, NSMutableArray, BRAsyncTaskContext, NSString;

@interface BRImageManager : NSObject {
@private
	unsigned long long _maxCacheSize;	// 4 = 0x4
	unsigned long long _cacheSize;	// 12 = 0xc
	unsigned long long _maxCacheCount;	// 20 = 0x14
	unsigned long long _cacheCount;	// 28 = 0x1c
	unsigned long long _cacheSizePurgeThreshhold;	// 36 = 0x24
	BOOL _cachePurging;	// 44 = 0x2c
	BOOL _purgeCacheOnLoadAndQuit;	// 45 = 0x2d
	BOOL _disableAccessDateUpdates;	// 46 = 0x2e
	NSString *_imageCachePath;	// 48 = 0x30
	NSMutableDictionary *_images;	// 52 = 0x34
	NSMutableDictionary *_remoteImageRequests;	// 56 = 0x38
	NSLock *_remoteImageLock;	// 60 = 0x3c
	NSMutableArray *_jobQueue;	// 64 = 0x40
	NSMutableDictionary *_pendingCachedImagesToFlush;	// 68 = 0x44
	BOOL _processJobs;	// 72 = 0x48
	BRAsyncTaskContext *_loadTaskContext;	// 76 = 0x4c
	BRAsyncTaskContext *_writeTaskContext;	// 80 = 0x50
	NSMutableArray *_activeDelegates;	// 84 = 0x54
	int _pruneCount;	// 88 = 0x58
}
@property(assign, nonatomic) int pruneCount;	// G=0x36764975; S=0x36764985; @synthesize=_pruneCount
+ (id)fullScreenImageResizingOptions;	// 0x36761e51
+ (id)generalPurposeManager;	// 0x3676262d
+ (id)screenSaverManager;	// 0x36762789
+ (id)trickPlayManager;	// 0x36762899
- (id)initWithCachePath:(id)cachePath purgeCacheOnLoadAndQuit:(BOOL)quit maxCacheSizeInMB:(unsigned long long)mb maxCacheCount:(unsigned long long)count cacheSizePurgeThreshholdInMB:(unsigned long long)mb5 pruneCount:(int)count6 disableAccessDateUpdates:(BOOL)updates;	// 0x36761ee1
- (void)_ATVDataImageAvailable:(id)available;	// 0x36767235
- (void)_addLoadJobToQueue:(id)queue;	// 0x36764ed9
- (void)_addWriteJobToQueue:(id)queue withImageID:(id)imageID height:(int)height width:(int)width cropped:(BOOL)cropped;	// 0x36764995
- (id)_cachedCroppedImageKeyForImageID:(id)imageID forSize:(CGSize)size;	// 0x36767059
- (id)_cachedCroppedImagePathForImageID:(id)imageID forSize:(CGSize)size;	// 0x36766f3d
- (id)_cachedOriginalImagePathForImageID:(id)imageID;	// 0x36766de5
- (id)_cachedResizedImageKeyForImageID:(id)imageID forSize:(CGSize)size;	// 0x36766ff9
- (id)_cachedResizedImagePathForImageID:(id)imageID forSize:(CGSize)size;	// 0x36766e81
- (void)_checkCache;	// 0x3676698d
- (void)_decrementCacheSize:(unsigned long long)size;	// 0x36766945
- (id)_defaultResizingImageOptions;	// 0x36765d39
- (id)_extensionForImageID:(id)imageID;	// 0x367671a1
- (id)_imageFromWriteQueue:(id)writeQueue;	// 0x367670b9
- (void)_imageLoadFailed:(id)failed;	// 0x36766601
- (void)_imageLoadSucceeded:(id)succeeded;	// 0x36766251
- (void)_incrementCacheSize:(unsigned long long)size;	// 0x367668e9
- (BOOL)_isLoadJobQueued:(id)queued;	// 0x36766b05
- (void)_maintainImageCache;	// 0x36765f51
- (void)_performLoadJob:(id)job;	// 0x367651b5
- (void)_performWriteJob:(id)job;	// 0x36764d35
- (void)_postUnavailableImageNotification:(id)notification;	// 0x36766749
- (void)_postUpdateNotification:(id)notification;	// 0x36766711
- (void)_postWriteCompletedNotification:(id)notification size:(CGSize)size cropped:(BOOL)cropped;	// 0x367667b5
- (void)_purgeRemoveDirectory:(BOOL)directory;	// 0x36767411
- (id)_queuedLoadJobWithName:(id)name;	// 0x36766bad
- (void)_removeCacheFile:(id)file;	// 0x36765f15
- (void)_removeLoadJobFromQueue:(id)queue;	// 0x36765091
- (void)_removeRemoteImageRequestNamed:(id)named;	// 0x36765dc9
- (void)_removeWriteJobFromQueue:(id)queue;	// 0x36764c51
- (void)_scheduleMaintainCache;	// 0x36766a91
- (void)_startLoadJob:(id)job;	// 0x36765001
- (void)_startWriteJob:(id)job;	// 0x36764bb9
- (void)_terminateNotification:(id)notification;	// 0x36766d09
- (BOOL)_updateExistingImageRecord:(id)record;	// 0x367655e9
- (id)_writeIDForImageID:(id)imageID cropped:(BOOL)cropped size:(CGSize)size;	// 0x36766d71
- (void)_writeImage:(id)image named:(id)named forSize:(CGSize)size cropped:(BOOL)cropped;	// 0x3676570d
- (id)absolutePathForImageID:(id)imageID;	// 0x36764911
- (id)cachePath;	// 0x36764949
- (float)cacheSize;	// 0x36764959
- (void)cancelWriteForImageWithURL:(id)url imageID:(id)anId;	// 0x36762db5
- (void)dealloc;	// 0x36762511
- (id)downSampleImage:(id)image name:(id)name scaledToSize:(CGSize)size writeToDisk:(BOOL)disk;	// 0x36763bf1
- (id)downSampleImage:(id)image name:(id)name scaledToSize:(CGSize)size writeToDisk:(BOOL)disk original:(BOOL)original rotate:(BOOL)rotate;	// 0x36763c25
- (BOOL)hasRemoteImageBeenRequestedForMediaID:(id)mediaID;	// 0x36764665
- (id)imageNameFromURL:(id)url;	// 0x36762b19
- (id)imageNamed:(id)named;	// 0x367639c9
- (id)imageNamed:(id)named croppedToSize:(CGSize)size create:(BOOL)create;	// 0x367634a1
- (id)imageNamed:(id)named scaledToSize:(CGSize)size;	// 0x3676398d
- (BOOL)isImageAvailable:(id)available;	// 0x3676299d
- (BOOL)isImageAvailable:(id)available croppedToSize:(CGSize)size;	// 0x36762add
- (BOOL)isImageAvailable:(id)available scaledToSize:(CGSize)size;	// 0x36762aa1
- (BOOL)isImageWritten:(id)written;	// 0x36762a89
- (id)loadImageFromURL:(id)url headerFields:(id)fields decryptionAgent:(id)agent;	// 0x36762e1d
- (void)moveImageFromPath:(id)path imageID:(id)anId;	// 0x367630f1
// declared property getter: - (int)pruneCount;	// 0x36764975
- (void)purge;	// 0x36764935
- (void)purgeAndRemoveDirectory;	// 0x36764921
- (void)purgeRemoteRequest;	// 0x367647c9
- (BOOL)receiveRemoteImageURL:(id)url forID:(id)anId;	// 0x36764335
- (BOOL)receiveRemoteImageURL:(id)url forID:(id)anId withResizingOptions:(id)resizingOptions;	// 0x36764371
- (void)receivedRemoteITunesImage:(id)image forID:(id)anId;	// 0x367641dd
- (void)receivedRemoteImage:(id)image forID:(id)anId;	// 0x36764505
- (void)remoteImageRequestForMediaID:(id)mediaID;	// 0x36764029
// declared property setter: - (void)setPruneCount:(int)count;	// 0x36764985
- (void)writeCroppedImage:(id)image named:(id)named;	// 0x3676307d
- (id)writeEncryptedImageFromURL:(id)url;	// 0x36762bd1
- (void)writeImage:(id)image named:(id)named;	// 0x36762f55
- (void)writeImage:(id)image named:(id)named asynchronous:(BOOL)asynchronous;	// 0x36762f79
- (id)writeImageFromImageProxy:(id)imageProxy;	// 0x36762b49
- (id)writeImageFromURL:(id)url;	// 0x36762bb1
- (id)writeImageFromURL:(id)url decryptionAgent:(id)agent;	// 0x36762c25
- (id)writeImageFromURL:(id)url headerFields:(id)fields decryptionAgent:(id)agent;	// 0x36762c49
- (id)writeImageFromURL:(id)url imageID:(id)anId headerFields:(id)fields decryptionAgent:(id)agent;	// 0x36762c6d
- (void)writeScaledImage:(id)image named:(id)named withSize:(CGSize)size;	// 0x36762fd1
@end

