/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class BRImageManager, BRImageLoadJob, NSMutableData;

__attribute__((visibility("hidden")))
@interface BRImageLoadDelegate : NSObject {
@private
	BRImageManager *_manager;	// 4 = 0x4
	BRImageLoadJob *_job;	// 8 = 0x8
	NSMutableData *_data;	// 12 = 0xc
}
@property(readonly, retain) BRImageLoadJob *job;	// G=0x367679c9; converted property
+ (id)imageLoadDelegateForManager:(id)manager withJob:(id)job;	// 0x367677ad
- (id)initForManager:(id)manager withJob:(id)job;	// 0x367677ed
- (void)connection:(id)connection didFailWithError:(id)error;	// 0x36767909
- (void)connection:(id)connection didReceiveData:(id)data;	// 0x36767961
- (void)connection:(id)connection didReceiveResponse:(id)response;	// 0x367678b1
- (id)connection:(id)connection willCacheResponse:(id)response;	// 0x367679c5
- (id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;	// 0x36767905
- (void)connectionDidFinishLoading:(id)connection;	// 0x367679a5
- (id)content;	// 0x367679d9
- (void)dealloc;	// 0x36767851
// converted property getter: - (id)job;	// 0x367679c9
@end

