/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRProvider.h"

@class NSArray;

@interface BRImageProxyProvider : NSObject <BRProvider> {
@private
	NSArray *_images;	// 4 = 0x4
}
+ (id)providerWithAssets:(id)assets;	// 0x366620e5
+ (id)providerWithImageProxies:(id)imageProxies;	// 0x36662051
- (id)initWithAssets:(id)assets;	// 0x36662121
- (id)initWithImageProxies:(id)imageProxies;	// 0x3666208d
- (id)controlFactory;	// 0x366621c5
- (id)dataAtIndex:(long)index;	// 0x366621e9
- (long)dataCount;	// 0x366621c9
- (void)dealloc;	// 0x36662179
- (id)hashForDataAtIndex:(long)index;	// 0x36662289
@end

