//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



@class BRAsyncTaskContext, NSLock, NSMutableArray, NSMutableDictionary, NSString;

@interface BRImageManager : NSObject
{
    unsigned long long _maxCacheSize;
    unsigned long long _cacheSize;
    unsigned long long _maxCacheCount;
    unsigned long long _cacheCount;
    unsigned long long _cacheSizePurgeThreshhold;
    BOOL _cachePurging;
    BOOL _purgeCacheOnLoadAndQuit;
    BOOL _disableAccessDateUpdates;
    NSString *_imageCachePath;
    NSMutableDictionary *_images;
    NSMutableDictionary *_remoteImageRequests;
    NSLock *_remoteImageLock;
    NSMutableArray *_jobQueue;
    NSMutableDictionary *_pendingCachedImagesToFlush;
    BOOL _processJobs;
    BRAsyncTaskContext *_loadTaskContext;
    BRAsyncTaskContext *_writeTaskContext;
    NSMutableArray *_activeDelegates;
    int _pruneCount;
}

+ (id)fullScreenImageResizingOptions;
+ (id)generalPurposeManager;
+ (id)screenSaverManager;
+ (id)trickPlayManager;
- (void)_ATVDataImageAvailable:(id)arg1;
- (void)_addLoadJobToQueue:(id)arg1;
- (void)_addWriteJobToQueue:(id)arg1 withImageID:(id)arg2 height:(int)arg3 width:(int)arg4 cropped:(BOOL)arg5;
- (id)_cachedCroppedImageKeyForImageID:(id)arg1 forSize:(struct CGSize)arg2;
- (id)_cachedCroppedImagePathForImageID:(id)arg1 forSize:(struct CGSize)arg2;
- (id)_cachedOriginalImagePathForImageID:(id)arg1;
- (id)_cachedResizedImageKeyForImageID:(id)arg1 forSize:(struct CGSize)arg2;
- (id)_cachedResizedImagePathForImageID:(id)arg1 forSize:(struct CGSize)arg2;
- (void)_checkCache;
- (void)_decrementCacheSize:(unsigned long long)arg1;
- (id)_defaultResizingImageOptions;
- (id)_extensionForImageID:(id)arg1;
- (id)_imageFromWriteQueue:(id)arg1;
- (void)_imageLoadFailed:(id)arg1;
- (void)_imageLoadSucceeded:(id)arg1;
- (void)_incrementCacheSize:(unsigned long long)arg1;
- (BOOL)_isLoadJobQueued:(id)arg1;
- (void)_maintainImageCache;
- (void)_performLoadJob:(id)arg1;
- (void)_performWriteJob:(id)arg1;
- (void)_postUnavailableImageNotification:(id)arg1;
- (void)_postUpdateNotification:(id)arg1;
- (void)_postWriteCompletedNotification:(id)arg1 size:(struct CGSize)arg2 cropped:(BOOL)arg3;
- (void)_purgeRemoveDirectory:(BOOL)arg1;
- (id)_queuedLoadJobWithName:(id)arg1;
- (void)_removeCacheFile:(id)arg1;
- (void)_removeLoadJobFromQueue:(id)arg1;
- (void)_removeRemoteImageRequestNamed:(id)arg1;
- (void)_removeWriteJobFromQueue:(id)arg1;
- (void)_scheduleMaintainCache;
- (void)_startLoadJob:(id)arg1;
- (void)_startWriteJob:(id)arg1;
- (void)_terminateNotification:(id)arg1;
- (BOOL)_updateExistingImageRecord:(id)arg1;
- (id)_writeIDForImageID:(id)arg1 cropped:(BOOL)arg2 size:(struct CGSize)arg3;
- (void)_writeImage:(id)arg1 named:(id)arg2 forSize:(struct CGSize)arg3 cropped:(BOOL)arg4;
- (id)absolutePathForImageID:(id)arg1;
- (id)cachePath;
- (float)cacheSize;
- (void)cancelWriteForImageWithURL:(id)arg1 imageID:(id)arg2;
- (void)dealloc;
- (id)downSampleImage:(id)arg1 name:(id)arg2 scaledToSize:(struct CGSize)arg3 writeToDisk:(BOOL)arg4;
- (id)downSampleImage:(id)arg1 name:(id)arg2 scaledToSize:(struct CGSize)arg3 writeToDisk:(BOOL)arg4 original:(BOOL)arg5 rotate:(BOOL)arg6;
- (BOOL)hasRemoteImageBeenRequestedForMediaID:(id)arg1;
- (id)imageNameFromURL:(id)arg1;
- (id)imageNamed:(id)arg1;
- (id)imageNamed:(id)arg1 croppedToSize:(struct CGSize)arg2 create:(BOOL)arg3;
- (id)imageNamed:(id)arg1 scaledToSize:(struct CGSize)arg2;
- (id)initWithCachePath:(id)arg1 purgeCacheOnLoadAndQuit:(BOOL)arg2 maxCacheSizeInMB:(unsigned long long)arg3 maxCacheCount:(unsigned long long)arg4 cacheSizePurgeThreshholdInMB:(unsigned long long)arg5 pruneCount:(int)arg6 disableAccessDateUpdates:(BOOL)arg7;
- (BOOL)isImageAvailable:(id)arg1;
- (BOOL)isImageAvailable:(id)arg1 croppedToSize:(struct CGSize)arg2;
- (BOOL)isImageAvailable:(id)arg1 scaledToSize:(struct CGSize)arg2;
- (BOOL)isImageWritten:(id)arg1;
- (id)loadImageFromURL:(id)arg1 headerFields:(id)arg2 decryptionAgent:(id)arg3;
- (void)moveImageFromPath:(id)arg1 imageID:(id)arg2;
@property(nonatomic) int pruneCount; // @synthesize pruneCount=_pruneCount;
- (void)purge;
- (void)purgeAndRemoveDirectory;
- (void)purgeRemoteRequest;
- (BOOL)receiveRemoteImageURL:(id)arg1 forID:(id)arg2;
- (BOOL)receiveRemoteImageURL:(id)arg1 forID:(id)arg2 withResizingOptions:(id)arg3;
- (void)receivedRemoteITunesImage:(id)arg1 forID:(id)arg2;
- (void)receivedRemoteImage:(id)arg1 forID:(id)arg2;
- (void)remoteImageRequestForMediaID:(id)arg1;
- (void)writeCroppedImage:(id)arg1 named:(id)arg2;
- (id)writeEncryptedImageFromURL:(id)arg1;
- (void)writeImage:(id)arg1 named:(id)arg2;
- (void)writeImage:(id)arg1 named:(id)arg2 asynchronous:(BOOL)arg3;
- (id)writeImageFromImageProxy:(id)arg1;
- (id)writeImageFromURL:(id)arg1;
- (id)writeImageFromURL:(id)arg1 decryptionAgent:(id)arg2;
- (id)writeImageFromURL:(id)arg1 headerFields:(id)arg2 decryptionAgent:(id)arg3;
- (id)writeImageFromURL:(id)arg1 imageID:(id)arg2 headerFields:(id)arg3 decryptionAgent:(id)arg4;
- (void)writeScaledImage:(id)arg1 named:(id)arg2 withSize:(struct CGSize)arg3;

@end

