/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRImageProxy.h"

@class NSString;

@interface BRInternetRadioImageProxy : NSObject <BRImageProxy> {
@private
	NSString *_category;	// 4 = 0x4
}
- (id)initWithCategory:(id)category;	// 0x3666233d
- (void)cancelImageRequestsForImageSizes:(int)imageSizes;	// 0x36662579
- (void)dealloc;	// 0x36662395
- (id)defaultImageForImageSize:(int)imageSize;	// 0x36662521
- (id)imageForImageSize:(int)imageSize;	// 0x36662425
- (id)imageIDForImageSize:(int)imageSize;	// 0x366623e1
- (id)object;	// 0x3666257d
- (BOOL)supportsImageForImageSize:(int)imageSize;	// 0x36662561
@end

