//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



@class NSArray, NSString;

@interface BRIPConfiguration : NSObject
{
    NSString *_wirelessNetwork;
    NSString *_wirelessMACAddress;
    NSString *_wirelessIPAddress;
    NSString *_wirelessSubnetMask;
    NSString *_wirelessRouter;
    NSArray *_wirelessDNSAddresses;
    NSString *_wiredMACAddress;
    NSString *_wiredIPAddress;
    NSString *_wiredSubnetMask;
    NSString *_wiredRouter;
    NSArray *_wiredDNSAddresses;
    unsigned int _wirelessUseDHCP:1;
    unsigned int _wirelessActive:1;
    unsigned int _wiredUseDHCP:1;
    unsigned int _wiredActive:1;
}

+ (struct __SCDynamicStore *)_dynamicStoreSingleton;
+ (void)_pushWirelessUsageValues;
+ (id)currentConfiguration;
+ (BOOL)internetAvailable;
+ (BOOL)internetServerReachable:(id)arg1;
+ (id)ipAddressesForHostName:(id)arg1;
+ (BOOL)networkAvailable;
+ (BOOL)networkTimeIsApproximatelyCorrect;
+ (BOOL)receivedNTPClockSetNotification;
+ (void)setReceivedNTPClockSetNotification:(BOOL)arg1;
+ (void)setShowedNetworkTimeDialog:(BOOL)arg1;
+ (void)setUserDismissedNetworkTimeDialog:(BOOL)arg1;
+ (BOOL)showedNetworkTimeDialog;
+ (void)startMonitoringNetworkChanges:(BOOL)arg1;
+ (BOOL)userDismissedNetworkTimeDialog;
- (id)IPaddressForInterface:(int)arg1;
- (id)MACaddressForInterface:(int)arg1;
- (id)_dnsAddressesForServiceID:(id)arg1 usingStore:(struct __SCDynamicStore *)arg2;
- (void)_examineService:(struct __SCNetworkService *)arg1 usingStore:(struct __SCDynamicStore *)arg2;
- (void)_getStateForServiceID:(id)arg1 usingStore:(struct __SCDynamicStore *)arg2 ipAddress:(id *)arg3 mask:(id *)arg4 router:(id *)arg5;
- (void)_getWirelessNetworkStateUsingStore:(struct __SCDynamicStore *)arg1;
- (BOOL)_isActiveForInterface:(id)arg1 usingStore:(struct __SCDynamicStore *)arg2;
- (BOOL)_setDHCPForService:(struct __SCNetworkService *)arg1;
- (BOOL)_setDNSAddress:(id)arg1 forService:(struct __SCNetworkService *)arg2;
- (BOOL)_setIPAddress:(id)arg1 subnetMask:(id)arg2 router:(id)arg3 forService:(struct __SCNetworkService *)arg4;
- (void)dealloc;
- (id)description;
- (id)dnsAddressesForInterface:(int)arg1;
- (id)initFromCurrentConfiguration;
- (BOOL)isActiveForInterface:(int)arg1;
- (id)routerForInterface:(int)arg1;
- (void)setAddress:(id)arg1 subnetMask:(id)arg2 router:(id)arg3 forInterface:(int)arg4;
- (void)setDNSAddresses:(id)arg1 forInterface:(int)arg2;
- (void)setUseDHCPForInterface:(int)arg1;
- (id)subnetMaskForInterface:(int)arg1;
- (BOOL)useDHCPForInterface:(int)arg1;
- (id)wirelessNetwork;
- (long)wirelessSignalQuality;

@end

