//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRKeyboard.h"

@class BRButtonControl, BRImageControl;

__attribute__((visibility("hidden")))
@interface BRKeyboardRomanWeb : BRKeyboard
{
    BRButtonControl *_previousButton;
    BRButtonControl *_nextButton;
    BRButtonControl *_autoFillButton;
    BRButtonControl *_clearButton;
    BRImageControl *_rowDividerImageControl;
}

- (void)_autoFillButtonClick:(id)arg1;
- (void)_generateKeyEventWithCharacters:(id)arg1;
- (id)_keyboardDataFileName;
- (float)_mainKeysVerticalSpacing;
- (void)_nextButtonClick:(id)arg1;
- (int)_numberOfMainKeyRows;
- (float)_preferredGlyphHeight:(id)arg1;
- (float)_preferredGlyphWidth:(id)arg1;
- (void)_prevousButtonClick:(id)arg1;
- (BOOL)canShowLanguageSwitchButton;
- (BOOL)canWrapVertically;
- (id)customizeTextEntryControls:(id)arg1;
- (void)dealloc;
- (id)init;
- (int)mapVisualIndex:(int)arg1 toRow:(id)arg2;
- (id)name;
- (BOOL)popupKeyboardShouldBeRightAlignedForKey:(id)arg1;
- (void)removeCustomizedTextEntryControls:(id)arg1;
- (BOOL)requiresTextFieldLabel;

@end

