//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRSpacerControl;

__attribute__((visibility("hidden")))
@interface BRKeyboardControl : BRControl
{
    BRControl *_mainKeysContainer;
    BRSpacerControl *_verticalSpacer;
    BRControl *_actionKeysContainer;
}

+ (id)keyboardControlWithMainKeysContainer:(id)arg1 actionKeysContainer:(id)arg2;
- (id)actionKeysContainer;
- (void)dealloc;
- (id)defaultKeyControl;
- (BOOL)focusIsAtRightEdge;
- (id)focusedKeyControl;
- (struct CGPoint)focusedPoint;
- (id)initWithMainKeysContainer:(id)arg1 actionKeysContainer:(id)arg2;
- (BOOL)keyboardFocusIsAtEdge:(int)arg1;
- (void)layoutSubcontrols;
- (id)mainKeysContainer;
- (void)setActionKeysContainer:(id)arg1;
- (void)setFocusToDefaultKeyControl;
- (void)setFocusToGlyphNamed:(id)arg1;
- (void)setFocusedKeyControl:(id)arg1;
- (BOOL)setFocusedPoint:(struct CGPoint)arg1;
- (void)setVerticalSpacing:(float)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

