/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRKeyboardRomanSearch.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardRomanSearchUpperCase : BRKeyboardRomanSearch {
}
- (id)accessibilityLabel;	// 0x366d38a1
- (id)name;	// 0x366d3895
- (id)switchToThisKeyboardIdentifier;	// 0x366d386d
@end

