/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRKeyboardRomanSquare.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardJapaneseRomanSquare : BRKeyboardRomanSquare {
}
- (long)_startingIndexOfActionKeysInKeyRowData;	// 0x366ca035
- (id)actionDictionaryForKeyControl:(id)keyControl;	// 0x366c9e75
- (id)name;	// 0x366c9e65
@end

