//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRKeyboardRomanSquare.h>

__attribute__((visibility("hidden")))
@interface BRKeyboardJapaneseSquareHiragana : BRKeyboardRomanSquare
{
}

- (id)_mainKeyRowPlane;
- (float)_mainKeysVerticalSpacing;
- (int)_numberOfMainKeyRows;
- (long)_startingIndexOfActionKeysInKeyRowData;
- (id)actionDictionaryForKeyControl:(id)arg1;
- (id)name;

@end

