/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRKeyboard.h"


__attribute__((visibility("hidden")))
@interface BRKeyboardHex : BRKeyboard {
}
- (id)init;	// 0x366c9ce5
- (float)_actionKeysContainerSpacing;	// 0x366c9e5d
- (float)_actionKeysContainerWidth;	// 0x366c9e55
- (id)_keyboardDataFileName;	// 0x366c9ddd
- (float)_mainKeysHorizontalSpacing;	// 0x366c9e19
- (float)_mainKeysVerticalSpacing;	// 0x366c9e11
- (int)_numberOfActionKeyColumns;	// 0x366c9e0d
- (int)_numberOfActionKeyRows;	// 0x366c9e09
- (int)_numberOfMainKeyColumns;	// 0x366c9e05
- (int)_numberOfMainKeyRows;	// 0x366c9dfd
- (int)_numberOfMainKeysInLastRow;	// 0x366c9e01
- (id)_optionCharactersForKeyboardInput;	// 0x366c9df9
- (id)_popupKeyboardDataFileName;	// 0x366c9dd1
- (float)_preferredTextEntryControlWidth;	// 0x366c9e29
- (float)_verticalGapBetweenMainAndActionKeys;	// 0x366c9e21
- (CGRect)keyboardControlFrame;	// 0x366c9e35
- (int)mapVisualIndex:(int)index toRow:(id)row;	// 0x366c9d75
- (id)name;	// 0x366c9d69
- (id)switchToThisKeyboardIdentifier;	// 0x366c9d41
@end

