/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRKeyboard.h"

@class BRButtonControl, BRImageControl;

__attribute__((visibility("hidden")))
@interface BRKeyboardRomanWeb : BRKeyboard {
@private
	BRButtonControl *_previousButton;	// 48 = 0x30
	BRButtonControl *_nextButton;	// 52 = 0x34
	BRButtonControl *_autoFillButton;	// 56 = 0x38
	BRButtonControl *_clearButton;	// 60 = 0x3c
	BRImageControl *_rowDividerImageControl;	// 64 = 0x40
}
- (id)init;	// 0x366d0ab1
- (void)_autoFillButtonClick:(id)click;	// 0x366d1721
- (void)_generateKeyEventWithCharacters:(id)characters;	// 0x366d15cd
- (id)_keyboardDataFileName;	// 0x366d0c01
- (float)_mainKeysVerticalSpacing;	// 0x366d15c5
- (void)_nextButtonClick:(id)click;	// 0x366d16d5
- (int)_numberOfMainKeyRows;	// 0x366d15c1
- (float)_preferredGlyphHeight:(id)height;	// 0x366d0c25
- (float)_preferredGlyphWidth:(id)width;	// 0x366d0c1d
- (void)_prevousButtonClick:(id)click;	// 0x366d168d
- (BOOL)canShowLanguageSwitchButton;	// 0x366d15b9
- (BOOL)canWrapVertically;	// 0x366d14c5
- (id)customizeTextEntryControls:(id)controls;	// 0x366d0c2d
- (void)dealloc;	// 0x366d0b0d
- (int)mapVisualIndex:(int)index toRow:(id)row;	// 0x366d0bb9
- (id)name;	// 0x366d0ba9
- (BOOL)popupKeyboardShouldBeRightAlignedForKey:(id)popupKeyboard;	// 0x366d14c9
- (void)removeCustomizedTextEntryControls:(id)controls;	// 0x366d13e1
- (BOOL)requiresTextFieldLabel;	// 0x366d15bd
@end

