//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRKeyboard.h>

__attribute__((visibility("hidden")))
@interface BRKeyboardHex : BRKeyboard
{
}

- (float)_actionKeysContainerSpacing;
- (float)_actionKeysContainerWidth;
- (id)_keyboardDataFileName;
- (float)_mainKeysHorizontalSpacing;
- (float)_mainKeysVerticalSpacing;
- (int)_numberOfActionKeyColumns;
- (int)_numberOfActionKeyRows;
- (int)_numberOfMainKeyColumns;
- (int)_numberOfMainKeyRows;
- (int)_numberOfMainKeysInLastRow;
- (id)_optionCharactersForKeyboardInput;
- (id)_popupKeyboardDataFileName;
- (float)_preferredTextEntryControlWidth;
- (float)_verticalGapBetweenMainAndActionKeys;
- (id)init;
- (struct CGRect)keyboardControlFrame;
- (int)mapVisualIndex:(int)arg1 toRow:(id)arg2;
- (id)name;
- (id)switchToThisKeyboardIdentifier;

@end

