//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRKeyboard.h>

@class BRBlueGlowSelectionLozengeLayer, BRContextMenuControl, BRKeyboardHistoryControl, BRListView, BRScrollControl, BRWaitSpinnerControl, NSArray;

__attribute__((visibility("hidden")))
@interface BRKeyboardHistory : BRKeyboard
{
    BRKeyboardHistoryControl *_keyboardHistoryControl;
    BRListView *_recentItemsList;
    BRBlueGlowSelectionLozengeLayer *_cursor;
    BRScrollControl *_scroller;
    BRWaitSpinnerControl *_spinner;
    BRContextMenuControl *_contextMenu;
    NSArray *_textEntryHistoryClientsForDisplay;
    NSArray *_textEntryHistoryBehaviorsForDisplay;
    int _textEntryStyle;
    float _preferredTextEntryWidth;
    float _preferredTextEntryHeight;
    struct CGRect _keyboardControlFrame;
    float _textFieldBackgroundWidth;
    float _textFieldBackgroundHeight;
    struct CGRect _textFieldBackgroundFrame;
    struct CGRect _textFieldFrame;
    struct CGRect _spinnerFrame;
    struct CGRect _textFieldLabelFrame;
    struct CGRect _tabControlFrame;
}

- (void)_contextMenuCancelItemSelected:(id)arg1;
- (int)_contextMenuDimOption;
- (id)_controlForContextMenuPositioning;
- (id)_controlForContextMenuStart;
- (id)_controlForData:(id)arg1;
- (id)_controlToDim;
- (void)_dismissContextMenu;
- (id)_filterRawKeyboardData:(id)arg1;
- (id)_glyphDataForImage:(id)arg1;
- (id)_glyphDataForStrings:(id)arg1 attributes:(id)arg2;
- (id)_glyphDataForTextString:(id)arg1 attributes:(id)arg2;
- (void)_handleContextMenuSelection:(id)arg1;
- (id)_keyboardDataFileName;
- (void)_listViewFocusChanged:(id)arg1;
- (id)_mainKeyRowPlane;
- (int)_numberOfMainKeyRows;
- (float)_preferredTextEntryControlWidth;
- (id)_processGlyphDataChunk:(id)arg1;
- (id)_providersForContextMenu;
- (void)_textEntryHistoryChanged:(id)arg1;
- (id)customizeTextEntryControls:(id)arg1;
- (id)customizedTextEntryFieldControls;
- (void)customizedTextFieldControlsWereRemoved;
- (void)dealloc;
- (void)displayTextEntryHistoryForClients:(id)arg1 textEntryBehaviors:(id)arg2;
- (BOOL)handleEvent:(id)arg1;
- (id)initWithTextEntryStyle:(int)arg1;
- (id)keyboardControl;
- (struct CGRect)keyboardControlFrame;
- (void)list:(id)arg1 didFocusItemAtIndexPath:(id)arg2;
- (void)list:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (float)list:(id)arg1 heightForItemAtIndexPath:(id)arg2;
- (float)list:(id)arg1 heightForSectionHeader:(long)arg2;
- (id)list:(id)arg1 menuItemForRowAtIndexPath:(id)arg2;
- (long)list:(id)arg1 numberOfRowsInSection:(long)arg2;
- (id)list:(id)arg1 sectionHeaderForSection:(long)arg2;
- (id)name;
- (long)numberOfSectionsInList:(id)arg1;
- (id)popupKeyboardForKeyControl:(id)arg1 textEntryControl:(id)arg2;
- (void)removeCustomizedTextEntryControls:(id)arg1;
- (BOOL)requiresTextFieldLabel;
- (struct CGRect)spinnerFrame;
- (void)startSpinning;
- (void)stopSpinning;
- (id)switchToThisKeyboardIdentifier;
- (struct CGRect)tabControlFrame;
- (BOOL)textEntryControlShouldHandleMainKeysEvents;
- (struct CGRect)textFieldBackgroundFrame;
- (struct CGRect)textFieldFrame;
- (struct CGRect)textFieldLabelFrame;

@end

