//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

@class BRGridControl, BRScrollControl, BRSelectionLozengeLayer, ListAnimationDelegate, NSArray, NSTimer;

@interface BRListControl : BRControl
{
    NSArray *_providers;
    BRSelectionLozengeLayer *_topWidget;
    BRSelectionLozengeLayer *_bottomWidget;
    BRScrollControl *_scroller;
    BRGridControl *_list;
    ListAnimationDelegate *_animationDelegate;
    NSTimer *_pokeTimer;
    NSTimer *_delayTimer;
    NSTimer *_repeatTimer;
    double _repeatStart;
    double _repeatAccumulator;
    long _scrollSelection;
    long _savedSelection;
    int _style;
    BOOL _handlingProviderChange;
    BOOL _showsDividers;
    BOOL _firstDividerVisible;
    BOOL _showBackingLayer;
    BOOL _selectionEntered;
    BOOL _widgetHidden;
    BOOL _needsUpdate;
    BOOL _turboEngaged;
    BOOL _movingDown;
}

- (long)_backwardIndexForRowCount:(long)arg1 hitBoundary:(char *)arg2;
- (double)_calculateRepeatRate;
- (long)_dataIndexFromScrollIndex:(long)arg1;
- (void)_ensureSelectionFocusable;
- (void)_enterCurrentSelection;
- (id)_findDividerProviderForProvider:(id)arg1;
- (long)_forwardIndexForRowCount:(long)arg1 hitBoundary:(char *)arg2;
- (void)_gridDataUpdated:(id)arg1;
- (void)_gridDataWillBeUpdated:(id)arg1;
- (void)_hideFirstDividerInDividedProviders:(id)arg1;
- (void)_leaveCurrentSelection;
- (id)_legacyProvider;
- (void)_listScrollingCompleted:(id)arg1;
- (void)_listScrollingInitiated:(id)arg1;
- (float)_maxWidgetBottomGlowHeight;
- (float)_maxWidgetEdgeGlowWidth;
- (float)_maxWidgetTopGlowHeight;
- (void)_performScrollInitiationActivities;
- (void)_performScrollTerminationActivities;
- (void)_pokeTimerFired:(id)arg1;
- (void)_postSelectionFinalizedNotification;
- (void)_refillList;
- (void)_repeatDownTimerFired:(id)arg1;
- (void)_repeatUpTimerFired:(id)arg1;
- (void)_restoreCurrentSelectionIndex;
- (void)_restorePersistentSavedSelection;
- (void)_saveCurrentSelectionIndex;
- (BOOL)_scrollDown:(id)arg1;
- (long)_scrollIndexForDataIndex:(long)arg1;
- (BOOL)_scrollUp:(id)arg1;
- (void)_setNewScrollIndex:(long)arg1;
- (void)_slowToStopRepeatTimerMovingDown:(BOOL)arg1;
- (void)_startDownwardAutoScroll:(id)arg1;
- (void)_startRepeatTimerMovingDown:(BOOL)arg1;
- (void)_startUpwardAutoScroll:(id)arg1;
- (void)_stopRepeatTimer;
- (void)_updateGrid;
- (void)_updatePersistentSavedSelection;
- (void)_updateProviders;
- (void)_updateScrollPosition;
- (void)_updateWidgetFrame;
- (void)_updateWidgetFrameForWidget:(id)arg1 withItemFrame:(struct CGRect)arg2;
- (id)accessibilityLabel;
- (void)addDividerAtIndex:(long)arg1 withLabel:(id)arg2;
- (BOOL)brEventAction:(id)arg1;
- (void)clearSavedSelection;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (long)dataCount;
- (id)datasource;
- (void)dealloc;
- (BOOL)displaysSelectionWidget;
- (BOOL)firstDividerVisible;
- (id)init;
- (BOOL)lastItemCentered;
- (void)layoutSubcontrols;
- (float)listHeightToMaximum:(float)arg1;
- (id)providerForDataAtIndex:(long)arg1 providerIndex:(long *)arg2;
- (id)providers;
- (void)reload;
- (void)removeDividerAtIndex:(long)arg1;
- (void)removeDividers;
@property(readonly) BRScrollControl *scrollControl; // @synthesize scrollControl=_scroller;
- (id)selectedObject;
- (long)selection;
- (int)selectionLozengeStyle;
- (void)setBottomMargin:(float)arg1;
- (void)setDatasource:(id)arg1;
- (void)setDisplaysSelectionWidget:(BOOL)arg1;
- (void)setFirstDividerVisible:(BOOL)arg1;
- (void)setLastItemCentered:(BOOL)arg1;
- (void)setName:(id)arg1 forProvider:(id)arg2;
- (void)setProvider:(id)arg1;
- (void)setProviders:(id)arg1;
- (void)setSelection:(long)arg1;
- (void)setSelectionLozengeStyle:(int)arg1;
- (void)setShowsDividers:(BOOL)arg1;
- (void)setShowsWidgetBackingLayer:(BOOL)arg1;
- (void)setTopMargin:(float)arg1;
- (BOOL)showsDividers;
- (BOOL)showsWidgetBackingLayer;
- (void)updateSavedSelection;
- (id)visibleRowsAndRange:(struct _NSRange *)arg1;

@end

