//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRGridView.h>

@class BRBlueGlowSelectionLozengeLayer, ListViewAnimationDelegate, NSTimer;

@interface BRListView : BRGridView
{
    BRBlueGlowSelectionLozengeLayer *_cursor;
    ListViewAnimationDelegate *_animationDelegate;
    NSTimer *_pokeTimer;
    NSTimer *_delayTimer;
    NSTimer *_repeatTimer;
    double _repeatStart;
    double _repeatAccumulator;
    long _scrollSelection;
    long _savedSelection;
    BOOL _turboEngaged;
    BOOL _movingDown;
    BOOL _selectionEntered;
}

- (long)_backwardIndexForRowCount:(long)arg1 hitBoundary:(char *)arg2;
- (double)_calculateRepeatRate;
- (unsigned int)_countOfHeadersInRange:(struct _NSRange)arg1;
- (long)_dataIndexFromGridIndex:(long)arg1;
- (id)_dataIndexPathFromGridIndex:(long)arg1 sectionIndex:(long *)arg2;
- (void)_ensureSelectionFocusable;
- (void)_enterCurrentSelection;
- (long)_forwardIndexForRowCount:(long)arg1 hitBoundary:(char *)arg2;
- (long)_gridIndexForDataIndex:(long)arg1;
- (long)_gridIndexForDataIndexPath:(id)arg1;
- (void)_leaveCurrentSelection;
- (void)_listScrollingCompleted:(id)arg1;
- (void)_listScrollingInitiated:(id)arg1;
- (void)_performScrollInitiationActivities;
- (void)_performScrollTerminationActivities;
- (void)_pokeTimerFired:(id)arg1;
- (void)_postSelectionFinalizedNotification;
- (void)_repeatDownTimerFired:(id)arg1;
- (void)_repeatUpTimerFired:(id)arg1;
- (void)_restoreCurrentSelectionIndex;
- (void)_saveCurrentSelectionIndex;
- (BOOL)_scrollDown:(id)arg1;
- (BOOL)_scrollUp:(id)arg1;
- (void)_setNewScrollIndex:(long)arg1;
- (void)_slowToStopRepeatTimerMovingDown:(BOOL)arg1;
- (void)_startDownwardAutoScroll:(id)arg1;
- (void)_startRepeatTimerMovingDown:(BOOL)arg1;
- (void)_startUpwardAutoScroll:(id)arg1;
- (void)_stopRepeatTimer;
- (void)_updateScrollPosition;
- (void)_updateWidgetFrame;
- (void)_updateWidgetFrameForWidget:(id)arg1 withItemFrame:(struct CGRect)arg2;
- (id)accessibilityControls;
- (id)accessibilityLabel;
- (BOOL)brEventAction:(id)arg1;
- (void)controlWasActivated;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (unsigned int)countOfCells;
- (id)cursor;
- (void)dealloc;
- (void)didFocusItemAtIndex:(long)arg1;
- (BOOL)didPlayItemAtIndex:(long)arg1;
- (BOOL)didSelectItemAtIndex:(long)arg1;
- (void)didUnFocusItemAtIndex:(long)arg1;
- (float)heightForItemAtIndex:(long)arg1;
- (long)indexForItemID:(id)arg1;
- (unsigned int)indexInCellsOfObject:(id)arg1;
- (id)init;
- (BOOL)isAccessibilityElement;
- (id)itemAtIndex:(long)arg1;
- (id)itemIDAtIndex:(long)arg1;
- (BOOL)lastItemCentered;
- (void)layoutSubcontrols;
- (void)list:(id)arg1 didFocusItemAtIndexPath:(id)arg2;
- (void)list:(id)arg1 didPlayItemAtIndexPath:(id)arg2;
- (void)list:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)list:(id)arg1 didUnFocusItemAtIndexPath:(id)arg2;
- (float)list:(id)arg1 heightForItemAtIndexPath:(id)arg2;
- (float)list:(id)arg1 heightForSectionHeader:(long)arg2;
- (id)list:(id)arg1 indexPathForItemID:(id)arg2;
- (id)list:(id)arg1 itemIDForIndexPath:(id)arg2;
- (id)list:(id)arg1 menuItemForRowAtIndexPath:(id)arg2;
- (long)list:(id)arg1 numberOfRowsInSection:(long)arg2;
- (id)list:(id)arg1 sectionHeaderForSection:(long)arg2;
- (void)list:(id)arg1 willDisplayItemAtIndexPath:(id)arg2;
- (id)list:(id)arg1 willFocusItemAtIndexPath:(id)arg2;
- (void)list:(id)arg1 willUnFocusItemAtIndexPath:(id)arg2;
- (float)listHeightToMaximum:(float)arg1;
- (void)listWasActivated:(id)arg1;
- (long)numberOfSectionsInList:(id)arg1;
- (id)objectInCellsAtIndex:(unsigned int)arg1;
- (void)populateDataCache:(id)arg1;
- (void)reload;
- (void)selectItemAtIndex:(long)arg1;
- (void)selectRowAtIndexPath:(id)arg1;
- (long)selectedIndex;
- (id)selectedIndexPath;
- (long)selection;
- (void)setCursor:(id)arg1;
- (void)setLastItemCentered:(BOOL)arg1;
- (id)visibleRowAtIndexPath:(id)arg1;
- (id)visibleRowsAndRange:(struct _NSRange *)arg1;
- (void)willDisplayItemAtIndex:(long)arg1;
- (long)willFocusItemAtIndex:(long)arg1;
- (void)willUnFocusItemAtIndex:(long)arg1;

@end

