/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface BRLogManager : NSObject {
}
+ (void)initialize;	// 0x3676b969
+ (BOOL)isClassNameRegistered:(id)registered;	// 0x3676ba29
+ (BOOL)isClassRegistered:(Class)registered;	// 0x3676ba05
+ (void)logMessage:(id)message fromSource:(id)source args:(void *)args;	// 0x3676ba91
+ (void)registerClass:(Class)aClass;	// 0x3676b9e5
+ (void)registerClassWithName:(id)name;	// 0x3676ba4d
+ (void)resetRegisteredClasses;	// 0x3676b9d5
+ (void)unregisterClass:(Class)aClass;	// 0x3676ba71
@end

