/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"

@class NSString, NSMutableDictionary;

@interface BRLocalizedStringManager : BRSingleton {
@private
	NSString *_currentLanguage;	// 4 = 0x4
	NSMutableDictionary *_stringFileCache;	// 8 = 0x8
}
+ (id)_backRowFramework;	// 0x3676b4e1
+ (id)accessibilityLocalizedStringForKey:(id)key;	// 0x3676b079
+ (id)appliance:(id)appliance localizedStringForKey:(id)key inFile:(id)file;	// 0x3676b11d
+ (id)applicationLocalizedStringForKey:(id)key inFile:(id)file;	// 0x3676b0d9
+ (id)backRowLocalizedStringForKey:(id)key inFile:(id)file;	// 0x3676b0ad
+ (id)localizedLanguageForCode:(id)code;	// 0x3676b451
+ (id)localizedStringForKey:(id)key inFile:(id)file fromBundle:(id)bundle;	// 0x3676b1b1
+ (id)pathForResource:(id)resource ofType:(id)type forBundle:(id)bundle;	// 0x3676b3c9
+ (void)setSingleton:(id)singleton;	// 0x3676aeed
+ (id)singleton;	// 0x3676aedd
- (id)init;	// 0x3676aefd
- (id)_currentLanguageNameForBundle:(id)bundle;	// 0x3676b681
- (id)_hashKeyForStringKey:(id)stringKey inFile:(id)file fromBundlePath:(id)bundlePath;	// 0x3676b74d
- (void)_languageChanged:(id)changed;	// 0x3676b4e5
- (void)dealloc;	// 0x3676afe9
@end

