/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"


@interface BRMarimbaSlideshowControl : BRControl {
}
+ (Class)layerClass;	// 0x36705581
- (id)init;	// 0x3670559d
- (id)layerForBacking;	// 0x367055f5
@end

