/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <NSObject.h> // Unknown library
#import "BRControlFactory.h"

@protocol BRSelectionHandler;

@interface BRMainMenuControlFactory : NSObject <BRControlFactory> {
@private
	id<BRSelectionHandler> _selectionHandler;	// 4 = 0x4
}
@property(retain) id selectionHandler;	// G=0x36672dcd; S=0x36672d8d; converted property
+ (id)factory;	// 0x36672cf9
- (id)_posterControlForAsset:(id)asset currentControl:(id)control requestedBy:(id)by;	// 0x36672ed9
- (id)_posterControlForCollection:(id)collection currentControl:(id)control requestedBy:(id)by;	// 0x36673155
- (id)_posterControlForMediaItem:(ATVMediaItemRef)mediaItem currentControl:(id)control requestedBy:(id)by;	// 0x366733d1
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x36672ddd
- (void)dealloc;	// 0x36672d41
// converted property getter: - (id)selectionHandler;	// 0x36672dcd
// converted property setter: - (void)setSelectionHandler:(id)handler;	// 0x36672d8d
@end

