//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

@class BRTextControl;

@interface BRMainMenuShelfErrorControl : BRControl
{
    BRTextControl *_text;
    BRTextControl *_subtext;
}

- (id)_subtextAttributes;
- (id)_textAttributes;
- (id)accessibilityLabel;
- (void)dealloc;
- (id)init;
- (void)layoutSubcontrols;
- (void)setSubtext:(id)arg1;
- (void)setText:(id)arg1;
- (id)subtext;
- (id)text;

@end

