/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRSelectionHandler.h"


@interface BRMainMenuSelectionHandler : NSObject <BRSelectionHandler> {
@private
	id<BRSelectionHandler> _handler;	// 4 = 0x4
}
+ (id)handlerWithHandler:(id)handler;	// 0x36719b55
- (id)initWithHandler:(id)handler;	// 0x36719b91
- (void)dealloc;	// 0x36719be5
- (BOOL)handlePlayForControl:(id)control;	// 0x36719e25
- (BOOL)handleSelectionForControl:(id)control;	// 0x36719c31
@end

