//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRController.h>

@class BRBackgroundTask, BRMainMenuControl, NSArray, NSMutableArray;

@interface BRMainMenuController : BRController
{
    NSArray *_applianceInfos;
    NSMutableArray *_topShelfControllers;
    BRMainMenuControl *_browser;
    BOOL _enabled;
    BOOL _handlingMainMenuEvent;
    BRBackgroundTask *_topShelfRefreshTask;
}

+ (BOOL)handlingMainMenuEvent;
+ (void)highlightApplianceWithKey:(id)arg1 andCategoryWithIdentifier:(id)arg2;
+ (void)setHandlingMainMenuEvent:(BOOL)arg1;
- (BOOL)_browserItemSelected:(id)arg1;
- (void)_handleWindowMaxBoundsChanged;
- (BOOL)_handlingMainMenuEvent;
- (void)_highlightApplianceWithKey:(id)arg1 andCategoryWithIdentifier:(id)arg2;
- (void)_loadAppliances;
- (void)_reloadTopShelvesByRecreating:(BOOL)arg1;
- (void)_setHandlingMainMenuEvent:(BOOL)arg1;
- (void)_shelfNoLongerFocusable:(id)arg1;
- (void)_topShelfControllerWillBeHidden:(id)arg1;
- (void)_topShelfControllerWillBeShown:(id)arg1;
- (id)accessibilityLabel;
- (BOOL)canBeRemovedFromStack;
- (void)clearRemembery;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
@property(readonly) id <BRAppliance> currentAppliance;
- (void)dealloc;
- (void)enable;
- (id)init;
- (void)mainMenu:(id)arg1 didSelectCategoryAtIndexPath:(id)arg2;
- (id)mainMenu:(id)arg1 shelfForApplianceAtIndex:(unsigned int)arg2;
- (void)mainMenu:(id)arg1 willHideShelfAtApplianceIndex:(long)arg2;
- (void)mainMenu:(id)arg1 willShowShelfAtApplianceIndex:(long)arg2;
- (void)reloadMainMenu;

@end

