/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRImageControl;

@interface BRMainMenuImageControl : BRControl {
@private
	BRImageControl *_content;	// 48 = 0x30
}
- (BOOL)acceptsFocus;	// 0x366a7b59
- (void)dealloc;	// 0x366a7b0d
- (void)layoutSubcontrols;	// 0x366a7bf9
- (void)setImageProxy:(id)proxy;	// 0x366a7b5d
@end

