//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRMenuView.h>

@class BRControl, BRImageControl, BRMediaPlayer, BRPhotoMediaCollection, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface BRMarimbaMenuView : BRMenuView
{
    BRMediaPlayer *_slideshowPhotoPlayer;
    BRImageControl *_listBackgroundControl;
    BRControl *_slideshowPreview;
    BRPhotoMediaCollection *_collection;
    NSArray *_slideshowThemeIdentifierKeys;
    NSString *_nextSlideshowTheme;
    NSString *_newlyRequestedTheme;
    BRControl *_fadeThroughBlackShroudControl;
    BOOL _themeSwitchInFlight;
    BOOL _playerVisualsChanged;
    BOOL _fadeThroughBlackControlNeedsLayout;
    BOOL _loopPhotos;
}

- (void)_beginTransitionToNewTheme;
- (void)_configurePhotoLooping:(BOOL)arg1;
- (void)_fadeInAnimationCompleted:(id)arg1;
- (void)_fadeOutAnimationCompleted:(id)arg1;
- (void)_finishTransitionToNewTheme;
- (void)_insertSlideshowPreview;
- (void)_marimbaLayerTransitionIsFinished:(id)arg1;
- (void)_playerVisualsChanged:(id)arg1;
- (void)_prepareToBeginTransitionToNewTheme;
- (void)_removeSlideshowPreview;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (id)currentTheme;
- (id)currentTransitions;
- (void)dealloc;
- (id)initWithMediaCollection:(id)arg1;
- (void)layoutSubcontrols;
- (id)musicServerID;
- (void)playSlideshow;
- (id)playlistID;
- (void)setLoopPhotos:(BOOL)arg1;
- (void)setMusicServerID:(id)arg1 playlistID:(id)arg2 playlistRef:(struct __ATVMediaCollection *)arg3;
- (void)setMuted:(BOOL)arg1;
- (void)setTimePerSlide:(double)arg1;
- (void)stopSlideshow;
- (void)switchToNewMenu;
- (BOOL)switchToTheme:(id)arg1;
- (void)switchToTransition:(id)arg1;
- (void)toggleSlideshowPlayback;

@end

