//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface BRMappingDictionary : NSObject
{
    NSMutableDictionary *_info;
}

- (long)count;
- (void)dealloc;
- (id)init;
- (id)keyEnumerator;
- (id)objectEnumerator;
- (id)objectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)setValueTransformer:(id)arg1 forKey:(id)arg2;
- (id)transformedValueForKey:(id)arg1 forObject:(id)arg2;
- (id)valueForKey:(id)arg1;
- (id)valueTransformerForKey:(id)arg1;

@end

