/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "NSObject.h"


@protocol BRMetadataPopulator <NSObject>
- (id)axMetadataFromAsset:(id)asset;
- (void)populateLayer:(id)layer fromAsset:(id)asset;
- (void)populateLongDescriptionLayer:(id)layer fromAsset:(id)asset;
@end

