//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

#import "BRMetadataContainer.h"

@class NSArray;

@interface BRMetadataLinesLayer : BRControl <BRMetadataContainer>
{
    struct CGSize _sizeThatFits;
    float _lineHeight;
    BOOL _delimeterDisabled;
    NSArray *_lineLayers;
    NSArray *_values;
    NSArray *_labels;
    float _extraLineHeight;
    BOOL _useMultiLineMetadata;
}

- (void)_buildLineLayersForValues:(id)arg1 andLabels:(id)arg2 usingIndexes:(id)arg3;
- (void)_layoutLines;
- (void)_setLineHeightUsingValues:(id)arg1 andLabels:(id)arg2;
- (id)_visibleMetadataIndexesForHeight:(float)arg1 andValues:(id)arg2;
- (float)_widthOfWidestLabel;
- (id)accessibilityLabel;
- (void)dealloc;
@property(nonatomic) BOOL delimeterDisabled; // @synthesize delimeterDisabled=_delimeterDisabled;
@property(nonatomic) float extraLineHeight; // @synthesize extraLineHeight=_extraLineHeight;
- (id)init;
@property(retain, nonatomic) NSArray *labels; // @synthesize labels=_labels;
- (void)layoutSubcontrols;
@property(retain, nonatomic) NSArray *lineLayers; // @synthesize lineLayers=_lineLayers;
- (void)setMetadata:(id)arg1 withLabels:(id)arg2;
- (void)setMetadata:(id)arg1 withLabels:(id)arg2 frameWidth:(float)arg3 maxHeight:(float)arg4;
@property(nonatomic) BOOL useMultiLineMetadata; // @synthesize useMultiLineMetadata=_useMultiLineMetadata;
@property(retain, nonatomic) NSArray *values; // @synthesize values=_values;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

