/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRMediaHostState.h"


__attribute__((visibility("hidden")))
@interface BRMediaHostStateUnavailable : BRMediaHostState {
}
- (id)mediaHostEvent:(id)event forMediaHost:(id)mediaHost;	// 0x3673c045
@end

