//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRType.h>

@interface BRMediaCollectionType : BRType
{
}

+ (id)composer;
+ (id)compoundITunesAlbum;
+ (id)compoundITunesArtist;
+ (id)genre;
+ (id)iPhotoAlbum;
+ (id)iPhotoEvent;
+ (id)iPhotoFaces;
+ (id)iPhotoFolder;
+ (id)iPhotoSlideshow;
+ (id)iTunesAlbum;
+ (id)iTunesArtist;
+ (id)iTunesFolderPlaylist;
+ (id)iTunesGeniusMix;
+ (id)iTunesInternetRadioPlaylist;
+ (id)iTunesMainGeniusPlaylist;
+ (id)iTunesMainOnTheGoPlaylist;
+ (id)iTunesPlaylist;
+ (id)iTunesPurchasesPlaylist;
+ (id)iTunesSavedGeniusPlaylist;
+ (id)iTunesSavedOnTheGoPlaylist;
+ (id)iTunesSmartPlaylist;
+ (id)movieTrailer;
+ (id)onTheGoCollectionTypes;
+ (id)photoCollectionTypes;
+ (id)playlistCollectionTypes;
+ (id)podcastCollection;
+ (id)podcastSubscriptionCollection;
+ (id)unknown;
+ (id)video;
+ (id)videoSlideshow;
- (id)description;
- (int)playlistTypeCompare:(id)arg1;

@end

