//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



@protocol BRMediaProvider <NSObject>
- (BOOL)autoload;
- (long)countOfObjectsWithMediaType:(id)arg1;
- (void)flush;
- (BOOL)isPasswordProtected;
- (id)mediaTypes;
- (id)objectsWithEntityName:(id)arg1 qualifiedByPredicate:(id)arg2 sortDescriptors:(id)arg3 error:(id *)arg4;
- (id)objectsWithEntityName:(id)arg1 qualifiedByPredicate:(id)arg2 sortDescriptors:(id)arg3 excludeHiddenObjects:(BOOL)arg4 error:(id *)arg5;
- (id)providerID;
- (id)providerName;
- (void)reset;
- (void)setIsPasswordProtected:(BOOL)arg1;
- (int)status;
@end

