//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class BRMenuItem;

@interface BRMenuItemMediator : NSObject
{
    BRMenuItem *_menuItem;
    SEL _mediaParadeSelector;
    SEL _menuSelector;
    id _object;
}

+ (id)mediatorWithMenuItem:(id)arg1;
- (void)dealloc;
- (id)initWithMenuItem:(id)arg1;
- (SEL)mediaPreviewSelector;
- (SEL)menuActionSelector;
- (id)menuItem;
- (id)object;
- (void)setMediaPreviewSelector:(SEL)arg1;
- (void)setMenuActionSelector:(SEL)arg1;
- (void)setMenuActionSelector:(SEL)arg1 withObject:(id)arg2;

@end

