//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

#import "BRContainerViewCell-Protocol.h"

@class NSDictionary, NSMutableArray, NSTimer;

@interface BRMediaShelfView : BRControl <BRContainerViewCell>
{
    id _dataSource;
    id _delegate;
    NSDictionary *_controlActions;
    NSDictionary *_titleActions;
    BOOL _centered;
    BOOL _scrollable;
    struct _NSRange _flatRange;
    struct CATransform3D _leftTransform;
    struct CATransform3D _rightTransform;
    NSMutableArray *_cells;
    NSMutableArray *_titles;
    NSTimer *_scrollTimer;
    BOOL _scrolling;
    int _collapsedState;
    BOOL _ordered;
    BOOL _needToReloadDataOnActivate;
    long _numberOfItems;
    struct _NSRange _refillVisibleRange;
    BOOL _restoreLastFocus;
    NSTimer *_forceDisplayTimer;
    CDUnknownBlockType _loadCompletionBlock;
    BOOL _okToLoad;
    BOOL _displayComplete;
    BOOL _explicitlyAcceptsFocus;
    long _columnCount;
    CDStruct_1420b1e7 _horizontalGap;
    float _coverflowMargin;
    BOOL antialiasCoverflowPosters;
}

- (long)_columnCount;
- (id)_controlActions;
- (id)_controlsInRange:(struct _NSRange)arg1 oldRange:(struct _NSRange)arg2;
- (float)_coverflowMargin;
- (id)_createControlAtIndex:(int)arg1;
- (id)_createControlsInRange:(struct _NSRange)arg1;
- (void)_displayCellsForce:(BOOL)arg1;
- (struct _NSRange)_dividedRangeForRange:(struct _NSRange)arg1 andDirection:(int)arg2;
- (unsigned int)_dividerCountInRange:(struct _NSRange)arg1;
- (unsigned int)_firstScrollableIndex;
- (void)_focusChanged:(id)arg1;
- (void)_forceDisplayTimerFired:(id)arg1;
- (float)_horizontalGap;
- (long)_indexFromIndexPath:(id)arg1;
- (id)_indexPathFromIndex:(long)arg1 sectionIndex:(long *)arg2;
- (BOOL)_isDividerAtIndex:(long)arg1;
- (unsigned int)_lastScrollableIndex;
- (void)_layoutShelfContents;
- (BOOL)_leftButtonEvent;
- (void)_loadControlWithStartIndex:(long)arg1 start:(BOOL)arg2;
- (void)_loadControlsInRange:(struct _NSRange)arg1;
- (unsigned int)_nextFocusableIndexInDirection:(int)arg1;
- (long)_numberOfItems;
- (void)_purgeControls;
- (void)_refillShelf;
- (void)_reloadTitles;
- (void)_removeSectionHeaderTitleControls;
- (BOOL)_rightButtonEvent;
- (BOOL)_scrollInDirection:(int)arg1;
- (BOOL)_scrollIndexToVisible:(long)arg1;
- (BOOL)_scrollLeft;
- (BOOL)_scrollRight;
- (long)_sectionIndexForIndex:(long)arg1;
- (id)_setControlRange:(struct _NSRange)arg1 oldRange:(struct _NSRange)arg2;
- (void)_setDimness:(float)arg1 forLayer:(id)arg2;
- (void)_setFlatRange:(struct _NSRange)arg1 delayedLayout:(BOOL)arg2;
- (void)_stopForceDisplayTimer;
- (id)_titleActions;
- (id)_updateFlatRangeForScrollDirection:(int)arg1;
- (void)_updateSublayerTransform;
- (struct _NSRange)_visibleRange;
- (id)accessibilityControls;
- (id)accessibilityLabel;
@property(nonatomic) BOOL antialiasCoverflowPosters; // @synthesize antialiasCoverflowPosters;
- (BOOL)brEventAction:(id)arg1;
- (void)cancelContainerViewLoad;
- (BOOL)centered;
- (int)collapsedState;
@property(nonatomic) long columnCount; // @synthesize columnCount=_columnCount;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (unsigned int)countOfCells;
@property(nonatomic) float coverflowMargin; // @synthesize coverflowMargin=_coverflowMargin;
- (long)dataCount;
- (id)dataSource;
- (void)dealloc;
- (id)delegate;
- (id)focusedControlForEvent:(id)arg1 focusPoint:(struct CGPoint *)arg2;
- (id)focusedIndexPath;
@property(nonatomic) CDStruct_1420b1e7 horizontalGap; // @synthesize horizontalGap=_horizontalGap;
- (unsigned int)indexInCellsOfObject:(id)arg1;
- (id)init;
- (void)layoutSubcontrols;
- (void)loadWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)objectInCellsAtIndex:(unsigned int)arg1;
- (BOOL)ordered;
- (void)reloadData;
- (BOOL)restorePersistentSavedSelection;
- (BOOL)scrollable;
- (void)scrollingCompleted;
- (id)selectedControl;
- (void)setAcceptsFocus:(BOOL)arg1;
- (void)setCentered:(BOOL)arg1;
- (void)setCollapsedState:(int)arg1;
- (void)setDataSource:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setFocusedIndexPath:(id)arg1;
- (void)setIgnoreLoadAndDisplayOnDemand;
- (void)setIgnoreLoadAndDisplayOnDemandDisableAnimations:(BOOL)arg1;
- (void)setOrdered:(BOOL)arg1;
- (void)setReadyToDisplay;
- (void)setScrollable:(BOOL)arg1;
- (void)updatePersistentSavedSelection;
- (void)visibleScrollRectChanged;
- (void)windowMaxBoundsChanged;

@end

