//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRMenuView.h"

@class BRControl, BRTextControl, NSString;

@interface BRMediaMenuView : BRMenuView
{
    BRControl *_preview;
    NSString *_previewLabel;
    BRControl *_listHeader;
    BRTextControl *_descriptionControl;
    CDStruct_1420b1e7 _headerMaxWidth;
    BOOL _headerCanExpandListWidth;
    CDStruct_1420b1e7 _previewTrailingGap;
    CDStruct_1420b1e7 _headerSpaceAbove;
    CDStruct_1420b1e7 _headerSpaceBelow;
}

- (id)accessibilityLabel;
- (id)accessibilityScreenContent;
- (BOOL)brEventAction:(id)arg1;
- (void)dealloc;
@property(nonatomic) BOOL headerCanExpandListWidth; // @synthesize headerCanExpandListWidth=_headerCanExpandListWidth;
@property(nonatomic) CDStruct_1420b1e7 headerMaxWidth; // @synthesize headerMaxWidth=_headerMaxWidth;
@property CDStruct_1420b1e7 headerSpaceAbove; // @synthesize headerSpaceAbove=_headerSpaceAbove;
@property CDStruct_1420b1e7 headerSpaceBelow; // @synthesize headerSpaceBelow=_headerSpaceBelow;
- (id)initWithListAlignment:(int)arg1;
- (void)layoutSubcontrols;
- (id)listDescription;
- (id)listHeader;
- (id)preview;
- (id)previewLabel;
@property(nonatomic) CDStruct_1420b1e7 previewTrailingGap; // @synthesize previewTrailingGap=_previewTrailingGap;
- (void)setListDescription:(id)arg1;
- (void)setListHeader:(id)arg1;
- (void)setPreview:(id)arg1;
- (void)setPreviewLabel:(id)arg1;

@end

