//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRType.h>

@interface BRMediaType : BRType
{
    BRMediaType *_derivedFrom;
}

+ (id)TVShow;
+ (id)TVShowPreview;
+ (id)_defaultImageForMediaType:(id)arg1 forImageSize:(int)arg2;
+ (id)airTunes;
+ (id)app;
+ (id)audioBook;
+ (id)booklet;
+ (id)cdSong;
+ (id)coachedAudio;
+ (id)defaultImageForMediaType:(id)arg1 forImageSize:(int)arg2;
+ (id)demoRentalMovie;
+ (id)dotMacPhoto;
+ (id)dotMacVideo;
+ (id)dotMacVideoSlideshow;
+ (id)downloadSpeedTest;
+ (id)dvd;
+ (id)flickrPhoto;
+ (id)iTunesExtras;
+ (id)iTunesLP;
+ (id)iTunesU;
+ (void)initialize;
+ (id)interactiveBooklet;
+ (id)internetPhoto;
+ (id)internetPhotoMediaTypes;
+ (id)internetRadioStation;
+ (id)liveStreamingTypes;
+ (id)liveVideo;
+ (id)movie;
+ (id)moviePreview;
+ (id)movieTrailer;
+ (id)musicVideo;
+ (id)musicVideoPreview;
+ (id)onTheGoMediaTypes;
+ (id)photo;
+ (id)podcast;
+ (id)podcastSubscription;
+ (id)radioStation;
+ (id)song;
+ (id)songPreview;
+ (id)storeMediaTypeStringForMediaType:(id)arg1;
+ (id)storeMediaTypes;
+ (id)storeRentalMovie;
+ (id)storeRentalTVShow;
+ (id)streamingPodcast;
+ (id)streamingVideo;
+ (id)syncedInternetRadioStation;
+ (id)trickPlay;
+ (id)unchapteredTypes;
+ (id)videoClip;
+ (id)ytVideo;
- (void)dealloc;
- (id)description;
- (BOOL)isKindOfMediaType:(id)arg1;
- (id)parentType;
- (void)setParentType:(id)arg1;

@end

