//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRMediaObject.h"

@protocol BRMediaCollection <BRMediaObject>
- (id)artist;
- (id)artistForSorting;
- (id)assetEnumerator;
- (id)childCollections;
- (id)collectionID;
- (id)collectionType;
- (int)count;
- (id)date;
- (long)duration;
- (id)imageProxy;
- (BOOL)isAvailable;
- (BOOL)isCompilation;
- (BOOL)isHidden;
- (BOOL)isLocal;
- (BOOL)isSingleArtistCompilation;
- (id)mediaAssets;
- (id)mediaType;
- (id)mediaTypes;
- (id)parentCollection;
- (id)provider;
- (id)title;
- (id)titleForSorting;
- (id)titleForSortingNoDefault;
- (id)titleNoDefault;
- (void)willBeDeleted;
@end

