/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSMutableArray, NSTimer, NSSet, NSDictionary, BRMediaHostEvent, BRMediaHostState;
@protocol BRUnresolvedMediaProviderHandler;

@interface BRMediaHost : NSObject {
@private
	NSDictionary *_hostInfo;	// 4 = 0x4
	NSMutableArray *_providers;	// 8 = 0x8
	int _hostType;	// 12 = 0xc
	NSMutableArray *_eventQueue;	// 16 = 0x10
	NSSet *_eventFilter;	// 20 = 0x14
	BRMediaHostEvent *_filterEvent;	// 24 = 0x18
	BRMediaHostState *_state;	// 28 = 0x1c
	NSTimer *_eventTimer;	// 32 = 0x20
	BOOL _supportsPhotos;	// 36 = 0x24
	BOOL _supportsPhotoThumbnails;	// 37 = 0x25
	id<BRUnresolvedMediaProviderHandler> _unresolvedProviderHandler;	// 40 = 0x28
}
@property(readonly, retain) NSDictionary *hostInfo;	// G=0x36738f85; converted property
@property(readonly, assign) int hostType;	// G=0x36739e25; converted property
@property(retain) id hostname;	// G=0x36739179; S=0x36738b4d; converted property
@property(retain) BRMediaHostState *state;	// G=0x36739e15; S=0x36739c19; converted property
@property(assign) BOOL supportsPhotoThumbnails;	// G=0x36739ea9; S=0x36739e99; converted property
@property(assign) BOOL supportsPhotos;	// G=0x36739e55; S=0x36739e89; converted property
+ (void)_addHostToMounts:(id)mounts;	// 0x3673a839
+ (void)_hostsChanged;	// 0x3673a861
+ (id)_mediaProviderAdvertisingMediaTypes:(id)types forceLocalResolution:(BOOL)resolution;	// 0x3673a589
+ (id)_mediaProvidersAdvertisingMediaTypes:(id)types forceLocalResolution:(BOOL)resolution;	// 0x3673a6b5
+ (void)_removeHostFromMounts:(id)mounts;	// 0x3673a811
+ (void)_updateTo3_0:(id)a3_0;	// 0x3673ac29
+ (void)addMediaHost:(id)host;	// 0x367382dd
+ (id)allRentalAssets;	// 0x36738751
+ (id)currentHost;	// 0x36737c41
+ (id)daapHosts;	// 0x367381ed
+ (id)daapMediaHostWithHostInfo:(id)hostInfo;	// 0x36737b51
+ (void)initialize;	// 0x367375fd
+ (BOOL)isPairedForSyncing:(BOOL *)syncing;	// 0x367385f9
+ (id)localHost;	// 0x36737cf5
+ (id)localMediaProviderAdvertisingMediaTypes:(id)types;	// 0x3673873d
+ (id)mediaHost;	// 0x36737925
+ (id)mediaHostForMediaProvider:(id)mediaProvider;	// 0x36737f91
+ (id)mediaHostMatchingHostInfo:(id)info;	// 0x36737dd1
+ (id)mediaHosts;	// 0x36738019
+ (id)mediaProviderAdvertisingMediaTypes:(id)types;	// 0x36738715
+ (id)mediaProvidersAdvertisingMediaTypes:(id)types;	// 0x36738729
+ (id)mountedMediaHosts;	// 0x36738651
+ (id)pairedHost;	// 0x367380dd
+ (void)removeMediaHost:(id)host;	// 0x36738411
+ (void)removeMediaHost:(id)host supressingRemoveNotification:(BOOL)notification;	// 0x36738431
+ (void)setCurrentHost:(id)host;	// 0x36737d59
+ (id)streamingHosts;	// 0x367380fd
+ (id)streamingMediaHostWithHostInfo:(id)hostInfo;	// 0x36737a5d
+ (id)syncingHost;	// 0x367380ed
+ (id)syncingMediaHostWithHostInfo:(id)hostInfo;	// 0x3673796d
+ (void)unmountAllHosts;	// 0x367377f5
+ (void)unmountInactiveStreamingHosts;	// 0x3673787d
- (id)init;	// 0x36738971
- (int)_codingVersion;	// 0x3673a8c5
- (void)_mediaProviderLoadFailed:(id)failed;	// 0x3673ab31
- (void)_mediaProviderLoaded:(id)loaded;	// 0x3673aaf5
- (void)_mediaProviderUnloaded:(id)unloaded;	// 0x3673abed
- (void)_mediaProviderUnloading:(id)unloading;	// 0x3673ab6d
- (void)_mount;	// 0x367391ad
- (void)_processEvent:(id)event;	// 0x3673aa49
- (void)_processNextEvent;	// 0x3673a8c9
- (void)_unmount;	// 0x367392b9
- (void)abandonEvent:(id)event;	// 0x36738ec1
- (void)addMediaProvider:(id)provider;	// 0x36739449
- (void)addMediaProvider:(id)provider checkForDuplicates:(BOOL)duplicates;	// 0x3673945d
- (BOOL)containsPasswordedProvider;	// 0x36739edd
- (void)dealloc;	// 0x36738a31
- (id)hostID;	// 0x36738afd
// converted property getter: - (id)hostInfo;	// 0x36738f85
// converted property getter: - (int)hostType;	// 0x36739e25
// converted property getter: - (id)hostname;	// 0x36739179
- (BOOL)isLocal;	// 0x36739e35
- (id)lastAccessedDate;	// 0x36739f3d
- (id)mediaProviderAdvertisingMediaTypes:(id)types;	// 0x36739a55
- (id)mediaProviderWithID:(id)anId andMachineID:(id)anId2;	// 0x36739851
- (id)mediaProviders;	// 0x36739381
- (id)mediaProvidersAdvertisingMediaTypes:(id)types;	// 0x36739941
- (void)postEvent:(id)event;	// 0x36738ce9
- (id)registeredMediaProviderForMediaTypes:(id)mediaTypes;	// 0x36739b09
- (void)removeAllMediaProviders;	// 0x36739b89
- (void)removeMediaProvider:(id)provider;	// 0x367396cd
- (void)removeMediaProviderWithID:(id)anId andMachineID:(id)anId2;	// 0x3673981d
// converted property setter: - (void)setHostname:(id)hostname;	// 0x36738b4d
// converted property setter: - (void)setState:(id)state;	// 0x36739c19
// converted property setter: - (void)setSupportsPhotoThumbnails:(BOOL)thumbnails;	// 0x36739e99
// converted property setter: - (void)setSupportsPhotos:(BOOL)photos;	// 0x36739e89
- (void)setUnresolvedMediaProviderHandler:(id)handler;	// 0x36738b09
// converted property getter: - (id)state;	// 0x36739e15
// converted property getter: - (BOOL)supportsPhotoThumbnails;	// 0x36739ea9
// converted property getter: - (BOOL)supportsPhotos;	// 0x36739e55
- (void)waitForEvent:(id)event toProcessEvent:(id)processEvent;	// 0x36738c55
@end

