/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRMetadataContainer.h"
#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSArray;

@interface BRMetadataLinesLayer : BRControl <BRMetadataContainer> {
@private
	CGSize _sizeThatFits;	// 48 = 0x30
	float _lineHeight;	// 56 = 0x38
	BOOL _delimeterDisabled;	// 60 = 0x3c
	NSArray *_lineLayers;	// 64 = 0x40
	NSArray *_values;	// 68 = 0x44
	NSArray *_labels;	// 72 = 0x48
	float _extraLineHeight;	// 76 = 0x4c
	BOOL _useMultiLineMetadata;	// 80 = 0x50
}
@property(assign, nonatomic) BOOL delimeterDisabled;	// G=0x366af619; S=0x366af629; @synthesize=_delimeterDisabled
@property(assign, nonatomic) float extraLineHeight;	// G=0x366af6d5; S=0x366af6e5; @synthesize=_extraLineHeight
@property(retain, nonatomic) NSArray *labels;	// G=0x366af6a1; S=0x366af6b1; @synthesize=_labels
@property(retain, nonatomic) NSArray *lineLayers;	// G=0x366af639; S=0x366af649; @synthesize=_lineLayers
@property(assign, nonatomic) BOOL useMultiLineMetadata;	// G=0x366af6f5; S=0x366af705; @synthesize=_useMultiLineMetadata
@property(retain, nonatomic) NSArray *values;	// G=0x366af66d; S=0x366af67d; @synthesize=_values
- (id)init;	// 0x366af249
- (void)_buildLineLayersForValues:(id)values andLabels:(id)labels usingIndexes:(id)indexes;	// 0x366afa0d
- (void)_layoutLines;	// 0x366afd59
- (void)_setLineHeightUsingValues:(id)values andLabels:(id)labels;	// 0x366af715
- (id)_visibleMetadataIndexesForHeight:(float)height andValues:(id)values;	// 0x366af8c5
- (float)_widthOfWidestLabel;	// 0x366aff6d
- (id)accessibilityLabel;	// 0x366b0075
- (void)dealloc;	// 0x366af2ad
// declared property getter: - (BOOL)delimeterDisabled;	// 0x366af619
// declared property getter: - (float)extraLineHeight;	// 0x366af6d5
// declared property getter: - (id)labels;	// 0x366af6a1
- (void)layoutSubcontrols;	// 0x366af4c5
// declared property getter: - (id)lineLayers;	// 0x366af639
// declared property setter: - (void)setDelimeterDisabled:(BOOL)disabled;	// 0x366af629
// declared property setter: - (void)setExtraLineHeight:(float)height;	// 0x366af6e5
// declared property setter: - (void)setLabels:(id)labels;	// 0x366af6b1
// declared property setter: - (void)setLineLayers:(id)layers;	// 0x366af649
- (void)setMetadata:(id)metadata withLabels:(id)labels;	// 0x366af321
- (void)setMetadata:(id)metadata withLabels:(id)labels frameWidth:(float)width maxHeight:(float)height;	// 0x366af3a9
// declared property setter: - (void)setUseMultiLineMetadata:(BOOL)metadata;	// 0x366af705
// declared property setter: - (void)setValues:(id)values;	// 0x366af67d
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x366af4a9
// declared property getter: - (BOOL)useMultiLineMetadata;	// 0x366af6f5
// declared property getter: - (id)values;	// 0x366af66d
@end

