/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


@interface BRMediaCollectionGeniusInfo : NSObject {
}
+ (id)geniusInfoForGeniusPlaylist:(id)geniusPlaylist;	// 0x366626b9
+ (BOOL)isGeniusDBAvailable;	// 0x36662701
+ (void)setImplementationClass:(Class)aClass;	// 0x366626a9
- (id)initWithGeniusPlaylist:(id)geniusPlaylist;	// 0x3666272d
- (BOOL)assetIsCurrentSeed:(id)seed;	// 0x36662759
- (BOOL)assetIsValidSeed:(id)seed;	// 0x3666275d
- (BOOL)playlistIsDirty;	// 0x3666276d
- (BOOL)refreshGeniusPlaylist;	// 0x36662765
- (id)saveGeniusPlaylist;	// 0x36662769
- (BOOL)setGeniusSeed:(id)seed;	// 0x36662761
@end

