/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRReflectionControl, BRMetadataControl, NSTimer, BRCoverArtImageLayer;
@protocol BRMetadataProvider;

@interface BRMetadataPreviewControl : BRControl {
@private
	id _asset;	// 48 = 0x30
	id<BRMetadataProvider> _metadataProvider;	// 52 = 0x34
	BRControl *_coverArtWrapper;	// 56 = 0x38
	BRCoverArtImageLayer *_coverArtLayer;	// 60 = 0x3c
	BRReflectionControl *_reflectionLayer;	// 64 = 0x40
	BRMetadataControl *_metadataLayer;	// 68 = 0x44
	NSTimer *_timer;	// 72 = 0x48
	BOOL _showsMetadataImmediately;	// 76 = 0x4c
	BOOL _showingMetadata;	// 77 = 0x4d
}
@property(retain) id asset;	// G=0x366ee8dd; S=0x366ee71d; converted property
@property(assign) BOOL deletterboxAssetArtwork;	// G=0x366ee94d; S=0x366ee92d; converted property
@property(assign) BOOL showsDefaultCoverArt;	// G=0x366ee991; S=0x366ee971; converted property
@property(assign) BOOL showsMetadataImmediately;	// G=0x366ee91d; S=0x366ee8ed; converted property
- (id)init;	// 0x366edb1d
- (void)_coverArtChanged:(id)changed;	// 0x366eee9d
- (void)_downloadStateChanged:(id)changed;	// 0x366eef19
- (CGRect)_frameForArt:(id)art inBounds:(CGSize)bounds;	// 0x366eef59
- (CGRect)_frameForArt:(id)art withMetadataFrame:(CGRect)metadataFrame inBounds:(CGSize)bounds;	// 0x366ef079
- (CGRect)_metadataFrameForBounds:(CGSize)bounds;	// 0x366ef389
- (void)_metadataTimerFired:(id)fired;	// 0x366eeef9
- (float)_reflectionAmountForArtFrame:(CGRect)artFrame bottomCutoff:(float)cutoff;	// 0x366ef41d
- (void)_showMetadataAfterDelay;	// 0x366eea79
- (void)_updateMetadataLayer;	// 0x366eeb19
- (id)accessibilityLabel;	// 0x366eea59
// converted property getter: - (id)asset;	// 0x366ee8dd
- (void)controlWasActivated;	// 0x366ee9c5
- (void)controlWasDeactivated;	// 0x366eea05
- (void)dealloc;	// 0x366edd69
// converted property getter: - (BOOL)deletterboxAssetArtwork;	// 0x366ee94d
- (void)layoutSubcontrols;	// 0x366ede49
- (id)metadataControl;	// 0x366ee9b5
// converted property setter: - (void)setAsset:(id)asset;	// 0x366ee71d
// converted property setter: - (void)setDeletterboxAssetArtwork:(BOOL)artwork;	// 0x366ee92d
- (void)setImageProxy:(id)proxy;	// 0x366ee651
- (void)setMetadataProvider:(id)provider;	// 0x366ee6b1
// converted property setter: - (void)setShowsDefaultCoverArt:(BOOL)art;	// 0x366ee971
// converted property setter: - (void)setShowsMetadataImmediately:(BOOL)immediately;	// 0x366ee8ed
// converted property getter: - (BOOL)showsDefaultCoverArt;	// 0x366ee991
// converted property getter: - (BOOL)showsMetadataImmediately;	// 0x366ee91d
@end

