/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library
#import "BRControlFactory.h"

@class NSMutableArray;

@interface BRMediatorProvider : NSObject <BRControlFactory, BRProvider> {
@private
	NSMutableArray *_activeMediators;	// 4 = 0x4
	NSMutableArray *_mediators;	// 8 = 0x8
}
@property(readonly, retain) NSMutableArray *mediators;	// G=0x36716601; converted property
+ (id)provider;	// 0x367161f5
+ (id)providerWithControl:(id)control identifier:(id)identifier;	// 0x36716365
+ (id)providerWithControlArray:(id)controlArray;	// 0x3671651d
+ (id)providerWithControls:(id)controls;	// 0x3671646d
+ (id)providerWithControlsAndIdentifiers:(id)controlsAndIdentifiers;	// 0x367163b1
+ (id)providerWithMediator:(id)mediator;	// 0x36716241
+ (id)providerWithMediatorArray:(id)mediatorArray;	// 0x36716319
+ (id)providerWithMediators:(id)mediators;	// 0x3671628d
- (id)init;	// 0x36716151
- (id)initWithMediators:(id)mediators;	// 0x3671602d
- (long)_activeInsertIndexForMediator:(id)mediator;	// 0x36716bc1
- (void)_activeStateChanged:(id)changed;	// 0x36716a2d
- (void)_controlChanged:(id)changed;	// 0x36716b45
- (void)_insertMediator:(id)mediator atIndex:(long)index;	// 0x36716c59
- (void)_subscribeToNotificationsForMediator:(id)mediator;	// 0x367168e1
- (void)_unsubscribeToNotificationsForMediator:(id)mediator;	// 0x36716999
- (void)addMediator:(id)mediator;	// 0x36716611
- (id)controlFactory;	// 0x36716851
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x367168cd
- (id)dataAtIndex:(long)index;	// 0x36716875
- (long)dataCount;	// 0x36716855
- (void)dealloc;	// 0x36716165
- (id)hashForDataAtIndex:(long)index;	// 0x36716895
- (void)insertMediator:(id)mediator after:(id)after;	// 0x36716729
- (void)insertMediator:(id)mediator before:(id)before;	// 0x36716789
- (id)mediatorWithIdentifier:(id)identifier;	// 0x367167d5
// converted property getter: - (id)mediators;	// 0x36716601
- (void)removeMediator:(id)mediator;	// 0x36716651
@end

