/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRType.h"


@interface BRMediaCollectionType : BRType {
}
+ (id)composer;	// 0x367370cd
+ (id)compoundITunesAlbum;	// 0x36736dfd
+ (id)compoundITunesArtist;	// 0x36736eed
+ (id)genre;	// 0x36736fdd
+ (id)iPhotoAlbum;	// 0x3673658d
+ (id)iPhotoEvent;	// 0x3673667d
+ (id)iPhotoFaces;	// 0x3673676d
+ (id)iPhotoFolder;	// 0x3673685d
+ (id)iPhotoSlideshow;	// 0x3673649d
+ (id)iTunesAlbum;	// 0x367362bd
+ (id)iTunesArtist;	// 0x367363ad
+ (id)iTunesFolderPlaylist;	// 0x36735c2d
+ (id)iTunesGeniusMix;	// 0x36735efd
+ (id)iTunesInternetRadioPlaylist;	// 0x36735d1d
+ (id)iTunesMainGeniusPlaylist;	// 0x36735e0d
+ (id)iTunesMainOnTheGoPlaylist;	// 0x367360dd
+ (id)iTunesPlaylist;	// 0x3673595d
+ (id)iTunesPurchasesPlaylist;	// 0x36735b3d
+ (id)iTunesSavedGeniusPlaylist;	// 0x36735fed
+ (id)iTunesSavedOnTheGoPlaylist;	// 0x367361cd
+ (id)iTunesSmartPlaylist;	// 0x36735a4d
+ (id)movieTrailer;	// 0x3673694d
+ (id)onTheGoCollectionTypes;	// 0x367372bd
+ (id)photoCollectionTypes;	// 0x367373e9
+ (id)playlistCollectionTypes;	// 0x367371bd
+ (id)podcastCollection;	// 0x36736a3d
+ (id)podcastSubscriptionCollection;	// 0x36736b2d
+ (id)unknown;	// 0x3673586d
+ (id)video;	// 0x36736c1d
+ (id)videoSlideshow;	// 0x36736d0d
- (id)description;	// 0x36737495
- (int)playlistTypeCompare:(id)compare;	// 0x367374d5
@end

