/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRTransportDataProvider.h"
#import "AppleTV-Structs.h"
#import <NSObject.h> // Unknown library

@class NSMutableArray;
@protocol BRPlayerDelegate;

@interface BRMediaPlayer : NSObject <BRTransportDataProvider> {
@private
	NSMutableArray *_stateStack;	// 4 = 0x4
	id<BRPlayerDelegate> _playerDelegate;	// 8 = 0x8
}
@property(assign) long chapterGroupIndex;	// G=0x36743409; S=0x36743405; converted property
@property(assign) long currentChapterIndex;	// G=0x367433f1; S=0x367433ed; converted property
@property(assign) BOOL disablePlatformFilters;	// G=0x36743451; S=0x3674344d; converted property
@property(assign) double elapsedTime;	// G=0x3674336d; S=0x36743369; converted property
@property(assign) BOOL isPlaylistDynamic;	// G=0x3674353d; S=0x36743539; converted property
@property(assign) BOOL muted;	// G=0x3674354d; S=0x36743549; converted property
@property(retain) id playbackDate;	// G=0x3674338d; S=0x36743389; converted property
@property(retain, nonatomic) id<BRPlayerDelegate> playerDelegate;	// G=0x367434a5; S=0x367434b5; @synthesize=_playerDelegate
@property(retain) id playerSpecificOptions;	// G=0x36743591; S=0x3674358d; converted property
@property(assign) int playlistEndAction;	// G=0x3674349d; S=0x36743499; converted property
@property(assign) int repeatMode;	// G=0x36743529; S=0x36743525; converted property
@property(retain) id selectedAudioOption;	// G=0x36743505; S=0x36743501; converted property
@property(retain) id selectedMedia;	// G=0x36743511; S=0x36743515; converted property
@property(retain) id selectedSubtitleOption;	// G=0x367434f9; S=0x367434f1; converted property
@property(assign) BOOL shufflePlayback;	// G=0x3674351d; S=0x36743519; converted property
@property(assign) BOOL skipExplicit;	// G=0x36743535; S=0x36743531; converted property
@property(assign) double startTime;	// G=0x367433b5; S=0x367433b1; converted property
@property(assign) double stopTime;	// G=0x3674339d; S=0x36743399; converted property
@property(assign) double virtualChapterMark;	// G=0x367433d1; S=0x367433cd; converted property
@property(assign) float volume;	// G=0x36743559; S=0x36743555; converted property
+ (BOOL)allowMultiplePlayers;	// 0x367430dd
+ (id)contentTypes;	// 0x367430d9
+ (BOOL)handlesVideoForType:(id)type;	// 0x367430e1
- (id)init;	// 0x367430e5
- (void)_checkPlayerMedia:(id)media;	// 0x36743889
- (void)_invalidateAsset:(id)asset;	// 0x36743825
- (void)appendMediaList:(id)list;	// 0x3674327d
- (void)appendMediaToSlidingWindow:(id)slidingWindow;	// 0x36743281
- (BOOL)attemptAuthorizationWithError:(id *)error;	// 0x36743455
- (id)audioOptions;	// 0x367434fd
- (BRTimeRange)bufferedRange;	// 0x3674342d
- (float)bufferingProgress;	// 0x3674343d
- (id)chapterAtIndex:(long)index;	// 0x36743425
- (long)chapterCount;	// 0x36743421
- (id)chapterGroupAtIndex:(long)index;	// 0x3674340d
- (long)chapterGroupCount;	// 0x36743401
// converted property getter: - (long)chapterGroupIndex;	// 0x36743409
- (long)chapterIndexForTime:(double)time;	// 0x367433f5
- (BOOL)chapterIsPlayable:(long)playable;	// 0x367433f9
- (id)chapters;	// 0x3674341d
- (void)clearStack;	// 0x367437f1
- (id)collection;	// 0x36743285
- (BOOL)cueMediaWithError:(id *)error;	// 0x367432e1
// converted property getter: - (long)currentChapterIndex;	// 0x367433f1
- (long)currentInterstitialIndex;	// 0x36743415
- (id)currentVideoFrame;	// 0x367434e1
- (void)dealloc;	// 0x367431a1
- (id)debugStringForState:(int)state;	// 0x36743595
// converted property getter: - (BOOL)disablePlatformFilters;	// 0x36743451
- (double)duration;	// 0x36743355
// converted property getter: - (double)elapsedTime;	// 0x3674336d
- (void)handleFailedURLResponse:(id)response requester:(id)requester;	// 0x36743821
- (BOOL)hasRealChapters;	// 0x367433fd
- (id)interstitialTimes;	// 0x36743411
- (BOOL)isAssetReadyToPlay:(id)play;	// 0x36743445
// converted property getter: - (BOOL)isPlaylistDynamic;	// 0x3674353d
- (BOOL)isTrackEnabled:(int)enabled;	// 0x36743509
- (double)keyframeTimeNearTime:(double)time searchForwards:(BOOL)forwards;	// 0x367434e5
- (id)media;	// 0x36743289
- (int)mediaCount;	// 0x36743291
- (long)mediaIndex;	// 0x367432dd
// converted property getter: - (BOOL)muted;	// 0x3674354d
- (void)nextChapter;	// 0x367433e5
- (void)nextMedia;	// 0x36743545
- (int)peekState;	// 0x36743739
// converted property getter: - (id)playbackDate;	// 0x3674338d
- (id)playbackInfo;	// 0x36743449
// declared property getter: - (id)playerDelegate;	// 0x367434a5
// converted property getter: - (id)playerSpecificOptions;	// 0x36743591
- (int)playerState;	// 0x36743349
- (BOOL)playingVisualContent;	// 0x367434d9
// converted property getter: - (int)playlistEndAction;	// 0x3674349d
- (int)popState;	// 0x36743771
- (void)previousChapter;	// 0x367433e9
- (void)previousMedia;	// 0x36743541
- (void)pushState:(int)state;	// 0x36743679
- (id)qualityOfServiceInfo;	// 0x367434a1
// converted property getter: - (int)repeatMode;	// 0x36743529
- (void)resetToBeginning;	// 0x367433c9
- (BOOL)reverseTouchSwipeBehavior;	// 0x36743235
// converted property getter: - (id)selectedAudioOption;	// 0x36743505
// converted property getter: - (id)selectedMedia;	// 0x36743511
// converted property getter: - (id)selectedSubtitleOption;	// 0x367434f9
// converted property setter: - (void)setChapterGroupIndex:(long)index;	// 0x36743405
// converted property setter: - (void)setCurrentChapterIndex:(long)index;	// 0x367433ed
// converted property setter: - (void)setDisablePlatformFilters:(BOOL)filters;	// 0x3674344d
// converted property setter: - (void)setElapsedTime:(double)time;	// 0x36743369
- (void)setFailedURLDelegate:(id)delegate;	// 0x3674381d
- (void)setForcedSubtitleOption;	// 0x367434f5
- (void)setForwardPlaybackEndTime:(double)time;	// 0x36743381
// converted property setter: - (void)setIsPlaylistDynamic:(BOOL)dynamic;	// 0x36743539
- (void)setMediaAsCurrentlyPlayingAppendingTrackList:(id)list;	// 0x36743279
- (BOOL)setMediaAtIndex:(long)index inCollection:(id)collection error:(id *)error;	// 0x3674323d
- (BOOL)setMediaAtIndex:(long)index inTrackList:(id)trackList error:(id *)error;	// 0x36743239
// converted property setter: - (void)setMuted:(BOOL)muted;	// 0x36743549
// converted property setter: - (void)setPlaybackDate:(id)date;	// 0x36743389
// declared property setter: - (void)setPlayerDelegate:(id)delegate;	// 0x367434b5
// converted property setter: - (void)setPlayerSpecificOptions:(id)options;	// 0x3674358d
// converted property setter: - (void)setPlaylistEndAction:(int)action;	// 0x36743499
// converted property setter: - (void)setRepeatMode:(int)mode;	// 0x36743525
- (void)setReversePlaybackEndTime:(double)time;	// 0x36743385
// converted property setter: - (void)setSelectedAudioOption:(id)option;	// 0x36743501
// converted property setter: - (void)setSelectedMedia:(id)media;	// 0x36743515
// converted property setter: - (void)setSelectedSubtitleOption:(id)option;	// 0x367434f1
// converted property setter: - (void)setShufflePlayback:(BOOL)playback;	// 0x36743519
// converted property setter: - (void)setSkipExplicit:(BOOL)anExplicit;	// 0x36743531
- (void)setStartDate:(id)date isEstimate:(BOOL)estimate;	// 0x36743391
// converted property setter: - (void)setStartTime:(double)time;	// 0x367433b1
- (BOOL)setState:(int)state error:(id *)error;	// 0x36743345
// converted property setter: - (void)setStopTime:(double)time;	// 0x36743399
- (void)setTrackEnabled:(BOOL)enabled forTrackID:(int)trackID;	// 0x3674350d
// converted property setter: - (void)setVirtualChapterMark:(double)mark;	// 0x367433cd
// converted property setter: - (void)setVolume:(float)volume;	// 0x36743555
// converted property getter: - (BOOL)shufflePlayback;	// 0x3674351d
// converted property getter: - (BOOL)skipExplicit;	// 0x36743535
- (id)startDate;	// 0x36743395
// converted property getter: - (double)startTime;	// 0x367433b5
// converted property getter: - (double)stopTime;	// 0x3674339d
- (BOOL)stopsActiveAudioPlayer;	// 0x36743231
- (id)subtitleOptions;	// 0x367434ed
- (BOOL)supportsBufferedRange;	// 0x36743429
- (BOOL)supportsMultipleTrickSpeeds;	// 0x3674334d
- (BOOL)supportsRepeatModes;	// 0x3674352d
- (BOOL)supportsShufflePlayback;	// 0x36743521
- (BOOL)supportsTrickPlay;	// 0x36743351
- (BOOL)supportsVolumeControl;	// 0x36743551
- (int)swapState:(int)state;	// 0x36743705
- (id)trackList;	// 0x3674328d
// converted property getter: - (double)virtualChapterMark;	// 0x367433d1
- (id)visuals;	// 0x367434dd
// converted property getter: - (float)volume;	// 0x36743559
@end

