//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRMediaParadeLayer, BRMediaParadeProvider;

@interface BRMediaParadeControl : BRControl
{
    BRMediaParadeLayer *_layer;
    BRMediaParadeProvider *_provider;
    BOOL _waitingForQueue;
    BOOL _pumpPrimed;
    BOOL _serializeArtwork;
}

- (void)_queueReady:(id)arg1;
- (void)_startFeeding;
- (void)_startFeedingWhenQueueReady;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)dealloc;
- (id)init;
- (void)setDeletterboxAssetArtwork:(BOOL)arg1;
- (void)setImageProxies:(id)arg1;
- (void)setSerializeArtwork:(BOOL)arg1;

@end

