/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRType.h"


@interface BRMediaType : BRType {
@private
	BRMediaType *_derivedFrom;	// 8 = 0x8
}
@property(retain) id parentType;	// G=0x36740335; S=0x367402f5; converted property
+ (id)TVShow;	// 0x3673d819
+ (id)TVShowPreview;	// 0x3673d909
+ (id)_defaultImageForMediaType:(id)mediaType forImageSize:(int)imageSize;	// 0x36740371
+ (id)airTunes;	// 0x3673ee69
+ (id)app;	// 0x3673f779
+ (id)audioBook;	// 0x3673da29
+ (id)booklet;	// 0x3673dd59
+ (id)cdSong;	// 0x3673cfd9
+ (id)coachedAudio;	// 0x3673df39
+ (id)defaultImageForMediaType:(id)mediaType forImageSize:(int)imageSize;	// 0x36740091
+ (id)demoRentalMovie;	// 0x3673e6b9
+ (id)dotMacPhoto;	// 0x3673e239
+ (id)dotMacVideo;	// 0x3673e7d9
+ (id)dotMacVideoSlideshow;	// 0x3673e8f9
+ (id)downloadSpeedTest;	// 0x3673ef89
+ (id)dvd;	// 0x3673d609
+ (id)flickrPhoto;	// 0x3673e359
+ (id)iTunesExtras;	// 0x3673f0b1
+ (id)iTunesLP;	// 0x3673f1a9
+ (id)iTunesU;	// 0x3673f399
+ (void)initialize;	// 0x3673ca51
+ (id)interactiveBooklet;	// 0x3673de49
+ (id)internetPhoto;	// 0x3673e119
+ (id)internetPhotoMediaTypes;	// 0x3673fbcd
+ (id)internetRadioStation;	// 0x3673ed49
+ (id)liveStreamingTypes;	// 0x3673ffe5
+ (id)liveVideo;	// 0x3673f589
+ (id)movie;	// 0x3673d519
+ (id)moviePreview;	// 0x3673d6f9
+ (id)movieTrailer;	// 0x3673db19
+ (id)musicVideo;	// 0x3673d0f9
+ (id)musicVideoPreview;	// 0x3673d219
+ (id)onTheGoMediaTypes;	// 0x3673fd01
+ (id)photo;	// 0x3673e029
+ (id)podcast;	// 0x3673d339
+ (id)podcastSubscription;	// 0x3673d429
+ (id)radioStation;	// 0x3673eb09
+ (id)song;	// 0x3673cdc9
+ (id)songPreview;	// 0x3673ceb9
+ (id)storeMediaTypeStringForMediaType:(id)mediaType;	// 0x367400ad
+ (id)storeMediaTypes;	// 0x3673f871
+ (id)storeRentalMovie;	// 0x3673e479
+ (id)storeRentalTVShow;	// 0x3673e599
+ (id)streamingPodcast;	// 0x3673ea19
+ (id)streamingVideo;	// 0x3673f491
+ (id)syncedInternetRadioStation;	// 0x3673ec29
+ (id)trickPlay;	// 0x3673f2a1
+ (id)unchapteredTypes;	// 0x3673fe51
+ (id)videoClip;	// 0x3673f681
+ (id)ytVideo;	// 0x3673dc39
- (void)dealloc;	// 0x36740269
- (id)description;	// 0x367402b5
- (BOOL)isKindOfMediaType:(id)mediaType;	// 0x36740345
// converted property getter: - (id)parentType;	// 0x36740335
// converted property setter: - (void)setParentType:(id)type;	// 0x367402f5
@end

