/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, BRImageControl;

@interface BRMetadataTitleControl : BRControl {
@private
	BRTextControl *_title;	// 48 = 0x30
	BRTextControl *_titleSubtext;	// 52 = 0x34
	BRImageControl *_rating;	// 56 = 0x38
	BRImageControl *_rightImage;	// 60 = 0x3c
	BOOL _ratingSnapsToTitle;	// 64 = 0x40
	float _rightImageHeight;	// 68 = 0x44
}
- (id)init;	// 0x366b2fdd
- (void)_layoutSubcontrolsWithSize:(CGSize)size;	// 0x366b36c9
- (id)accessibilityLabel;	// 0x366b3645
- (void)dealloc;	// 0x366b3185
- (void)layoutSubcontrols;	// 0x366b35fd
- (CGSize)renderedSize;	// 0x366b3435
- (void)setRating:(id)rating;	// 0x366b3309
- (void)setRatingSnapsToTitle:(BOOL)title;	// 0x366b338d
- (void)setRightImage:(id)image;	// 0x366b33bd
- (void)setRightImageFixedHeight:(float)height;	// 0x366b33f9
- (void)setTitle:(id)title;	// 0x366b320d
- (void)setTitleSubtext:(id)subtext;	// 0x366b3289
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x366b3525
@end

