/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"
#import "BRContainerViewCell.h"

@class NSMutableArray, NSTimer, NSDictionary;

@interface BRMediaShelfView : BRControl <BRContainerViewCell> {
@private
	id _dataSource;	// 48 = 0x30
	id _delegate;	// 52 = 0x34
	NSDictionary *_controlActions;	// 56 = 0x38
	NSDictionary *_titleActions;	// 60 = 0x3c
	BOOL _centered;	// 64 = 0x40
	BOOL _scrollable;	// 65 = 0x41
	NSRange _flatRange;	// 68 = 0x44
	CATransform3D _leftTransform;	// 76 = 0x4c
	CATransform3D _rightTransform;	// 140 = 0x8c
	NSMutableArray *_cells;	// 204 = 0xcc
	NSMutableArray *_titles;	// 208 = 0xd0
	NSTimer *_scrollTimer;	// 212 = 0xd4
	BOOL _scrolling;	// 216 = 0xd8
	int _collapsedState;	// 220 = 0xdc
	BOOL _ordered;	// 224 = 0xe0
	BOOL _needToReloadDataOnActivate;	// 225 = 0xe1
	long _numberOfItems;	// 228 = 0xe4
	NSRange _refillVisibleRange;	// 232 = 0xe8
	BOOL _restoreLastFocus;	// 240 = 0xf0
	NSTimer *_forceDisplayTimer;	// 244 = 0xf4
	id _loadCompletionBlock;	// 248 = 0xf8
	BOOL _okToLoad;	// 252 = 0xfc
	BOOL _displayComplete;	// 253 = 0xfd
	BOOL _explicitlyAcceptsFocus;	// 254 = 0xfe
	long _columnCount;	// 256 = 0x100
	XXStruct_qlg9jA _horizontalGap;	// 260 = 0x104
	float _coverflowMargin;	// 264 = 0x108
	BOOL antialiasCoverflowPosters;	// 268 = 0x10c
}
@property(assign, nonatomic) BOOL antialiasCoverflowPosters;	// G=0x3665675d; S=0x3665676d; @synthesize
@property(assign) BOOL centered;	// G=0x366559d1; S=0x366559a1; converted property
@property(assign) int collapsedState;	// G=0x36655f7d; S=0x36655f51; converted property
@property(assign, nonatomic) long columnCount;	// G=0x36656711; S=0x366556e1; @synthesize=_columnCount
@property(assign, nonatomic) float coverflowMargin;	// G=0x3665673d; S=0x3665674d; @synthesize=_coverflowMargin
@property(retain) id dataSource;	// G=0x36655891; S=0x366557d5; converted property
@property(assign) id delegate;	// G=0x366558b1; S=0x366558a1; converted property
@property(retain) id focusedIndexPath;	// G=0x36655db5; S=0x36655e41; converted property
@property(assign, nonatomic) XXStruct_qlg9jA horizontalGap;	// G=0x36656721; S=0x36655715; @synthesize=_horizontalGap
@property(assign) BOOL ordered;	// G=0x36655a11; S=0x366559e1; converted property
@property(assign) BOOL scrollable;	// G=0x36655991; S=0x3665594d; converted property
- (id)init;	// 0x366551e1
- (long)_columnCount;	// 0x36656859
- (id)_controlActions;	// 0x36658781
- (id)_controlsInRange:(NSRange)range oldRange:(NSRange)range2;	// 0x36658da1
- (float)_coverflowMargin;	// 0x36656939
- (id)_createControlAtIndex:(int)index;	// 0x36658b29
- (id)_createControlsInRange:(NSRange)range;	// 0x36658efd
- (void)_displayCellsForce:(BOOL)force;	// 0x36659355
- (NSRange)_dividedRangeForRange:(NSRange)range andDirection:(int)direction;	// 0x36659551
- (unsigned)_dividerCountInRange:(NSRange)range;	// 0x36659675
- (unsigned)_firstScrollableIndex;	// 0x36656ab1
- (void)_focusChanged:(id)changed;	// 0x366569f1
- (void)_forceDisplayTimerFired:(id)fired;	// 0x3665952d
- (float)_horizontalGap;	// 0x366568b5
- (long)_indexFromIndexPath:(id)indexPath;	// 0x36659b2d
- (id)_indexPathFromIndex:(long)index sectionIndex:(long *)index2;	// 0x36659be1
- (BOOL)_isDividerAtIndex:(long)index;	// 0x366596c1
- (unsigned)_lastScrollableIndex;	// 0x36656a71
- (void)_layoutShelfContents;	// 0x36657059
- (BOOL)_leftButtonEvent;	// 0x36656b99
- (void)_loadControlWithStartIndex:(long)startIndex start:(BOOL)start;	// 0x36659041
- (void)_loadControlsInRange:(NSRange)range;	// 0x36658fa1
- (unsigned)_nextFocusableIndexInDirection:(int)direction;	// 0x36656ac1
- (long)_numberOfItems;	// 0x36659a3d
- (void)_purgeControls;	// 0x36656805
- (void)_refillShelf;	// 0x3665677d
- (void)_reloadTitles;	// 0x36659761
- (void)_removeSectionHeaderTitleControls;	// 0x36659999
- (BOOL)_rightButtonEvent;	// 0x36656b39
- (BOOL)_scrollInDirection:(int)direction;	// 0x36656bf9
- (BOOL)_scrollIndexToVisible:(long)visible;	// 0x36657025
- (BOOL)_scrollLeft;	// 0x36656e01
- (BOOL)_scrollRight;	// 0x36656de9
- (long)_sectionIndexForIndex:(long)index;	// 0x36659cfd
- (id)_setControlRange:(NSRange)range oldRange:(NSRange)range2;	// 0x36658bb1
- (void)_setDimness:(float)dimness forLayer:(id)layer;	// 0x36658645
- (void)_setFlatRange:(NSRange)range delayedLayout:(BOOL)layout;	// 0x366589c9
- (void)_stopForceDisplayTimer;	// 0x366594f9
- (id)_titleActions;	// 0x3665987d
- (id)_updateFlatRangeForScrollDirection:(int)scrollDirection;	// 0x36658915
- (void)_updateSublayerTransform;	// 0x36656efd
- (NSRange)_visibleRange;	// 0x36656e1d
- (id)accessibilityControls;	// 0x3665610d
- (id)accessibilityLabel;	// 0x36659db1
// declared property getter: - (BOOL)antialiasCoverflowPosters;	// 0x3665675d
- (BOOL)brEventAction:(id)action;	// 0x36655a21
- (void)cancelContainerViewLoad;	// 0x36656451
// converted property getter: - (BOOL)centered;	// 0x366559d1
// converted property getter: - (int)collapsedState;	// 0x36655f7d
// declared property getter: - (long)columnCount;	// 0x36656711
- (void)controlWasActivated;	// 0x36655481
- (void)controlWasDeactivated;	// 0x3665553d
- (unsigned)countOfCells;	// 0x36656129
// declared property getter: - (float)coverflowMargin;	// 0x3665673d
- (long)dataCount;	// 0x366558c1
// converted property getter: - (id)dataSource;	// 0x36655891
- (void)dealloc;	// 0x36655369
// converted property getter: - (id)delegate;	// 0x366558b1
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x3665606d
// converted property getter: - (id)focusedIndexPath;	// 0x36655db5
// declared property getter: - (XXStruct_qlg9jA)horizontalGap;	// 0x36656721
- (unsigned)indexInCellsOfObject:(id)object;	// 0x366561b1
- (void)layoutSubcontrols;	// 0x36655f8d
- (void)loadWithCompletionBlock:(id)completionBlock;	// 0x366563ad
- (id)objectInCellsAtIndex:(unsigned)index;	// 0x3665629d
// converted property getter: - (BOOL)ordered;	// 0x36655a11
- (void)reloadData;	// 0x36655751
- (BOOL)restorePersistentSavedSelection;	// 0x366564a5
// converted property getter: - (BOOL)scrollable;	// 0x36655991
- (void)scrollingCompleted;	// 0x36656361
- (id)selectedControl;	// 0x36655f41
- (void)setAcceptsFocus:(BOOL)focus;	// 0x36655435
// declared property setter: - (void)setAntialiasCoverflowPosters:(BOOL)posters;	// 0x3665676d
// converted property setter: - (void)setCentered:(BOOL)centered;	// 0x366559a1
// converted property setter: - (void)setCollapsedState:(int)state;	// 0x36655f51
// declared property setter: - (void)setColumnCount:(long)count;	// 0x366556e1
// declared property setter: - (void)setCoverflowMargin:(float)margin;	// 0x3665674d
// converted property setter: - (void)setDataSource:(id)source;	// 0x366557d5
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x366558a1
// converted property setter: - (void)setFocusedIndexPath:(id)path;	// 0x36655e41
// declared property setter: - (void)setHorizontalGap:(XXStruct_qlg9jA)gap;	// 0x36655715
- (void)setIgnoreLoadAndDisplayOnDemand;	// 0x36656481
- (void)setIgnoreLoadAndDisplayOnDemandDisableAnimations:(BOOL)animations;	// 0x36656495
// converted property setter: - (void)setOrdered:(BOOL)ordered;	// 0x366559e1
- (void)setReadyToDisplay;	// 0x3665647d
// converted property setter: - (void)setScrollable:(BOOL)scrollable;	// 0x3665594d
- (void)updatePersistentSavedSelection;	// 0x366565e5
- (void)visibleScrollRectChanged;	// 0x366562f9
- (void)windowMaxBoundsChanged;	// 0x3665566d
@end

