/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRController.h"

@class BRListControl, BRTextControl, BRHeaderControl, BRListControlMonitor;

@interface BRMenuController : BRController {
@private
	BRListControl *_list;	// 84 = 0x54
	BRHeaderControl *_header;	// 88 = 0x58
	id _selectedObject;	// 92 = 0x5c
	BOOL _clearSavedSelection;	// 96 = 0x60
	BRListControlMonitor *_listControlMonitor;	// 100 = 0x64
	float _menuWidthFactor;	// 104 = 0x68
	float _headerWidthFactor;	// 108 = 0x6c
	BOOL _useCenteredLayout;	// 112 = 0x70
	BRTextControl *_primaryTextControl;	// 116 = 0x74
	BRTextControl *_secondaryTextControl;	// 120 = 0x78
	BRTextControl *_labelControl;	// 124 = 0x7c
}
@property(readonly, retain) BRHeaderControl *header;	// G=0x3665a421; converted property
@property(assign) float headerWidthFactor;	// G=0x3665a46d; S=0x3665a431; converted property
@property(readonly, retain) BRListControl *list;	// G=0x3665a369; converted property
@property(retain) id listIcon;	// G=0x3665b2a1; S=0x3665b239; converted property
@property(assign) float listIconHorizontalOffset;	// G=0x3665b2e1; S=0x3665b2c1; converted property
@property(assign) float listIconKerningFactor;	// G=0x3665b321; S=0x3665b301; converted property
@property(retain) id listTitle;	// G=0x3665b1f9; S=0x3665b179; converted property
@property(assign) float menuWidthFactor;	// G=0x3665a411; S=0x3665a379; converted property
@property(assign) long selectedItem;	// G=0x3665b4b5; S=0x3665b495; converted property
@property(retain) id selectedObject;	// G=0x3665a62d; S=0x3665a5ed; converted property
- (id)init;	// 0x36659ed1
- (BOOL)_itemSelected:(id)selected;	// 0x3665b519
- (id)accessibilityLabel;	// 0x3665b40d
- (id)accessibilitySecondaryLabel;	// 0x3665b42d
- (void)cancelCurrentListMonitorLoads;	// 0x3665a7dd
- (void)clearSavedSelection;	// 0x3665a481
- (int)contextMenuDimOption;	// 0x3665b409
- (id)controlForContextMenuPositioning;	// 0x3665b341
- (id)controlForContextMenuStart;	// 0x3665b351
- (id)controlToDim;	// 0x3665b379
- (void)controlWasActivated;	// 0x3665a4cd
- (void)dealloc;	// 0x3665a031
- (long)defaultIndex;	// 0x3665b511
// converted property getter: - (id)header;	// 0x3665a421
// converted property getter: - (float)headerWidthFactor;	// 0x3665a46d
- (BOOL)isCurrentSelectionValidForModelData:(id)modelData;	// 0x3665a699
- (BOOL)isValidAfterDataUpdate;	// 0x3665a731
- (BOOL)isVolatile;	// 0x3665b58d
- (long)itemCount;	// 0x3665b4d5
- (void)itemSelected:(long)selected;	// 0x3665b50d
- (void)layoutSubcontrols;	// 0x3665a125
- (void)layoutSubcontrolsUsingCenteredLayout;	// 0x3665a851
// converted property getter: - (id)list;	// 0x3665a369
// converted property getter: - (id)listIcon;	// 0x3665b2a1
// converted property getter: - (float)listIconHorizontalOffset;	// 0x3665b2e1
// converted property getter: - (float)listIconKerningFactor;	// 0x3665b321
// converted property getter: - (id)listTitle;	// 0x3665b1f9
- (float)listVerticalOffset;	// 0x3665a47d
- (id)loadModelData;	// 0x3665a63d
// converted property getter: - (float)menuWidthFactor;	// 0x3665a411
- (id)primaryInfoTextControl;	// 0x3665ae55
- (void)refreshControllerForModelUpdate;	// 0x3665a641
- (void)refreshControllerForModelUpdateToObject:(id)object;	// 0x3665a645
- (id)secondaryInfoTextControl;	// 0x3665afa5
// converted property getter: - (long)selectedItem;	// 0x3665b4b5
// converted property getter: - (id)selectedObject;	// 0x3665a62d
// converted property setter: - (void)setHeaderWidthFactor:(float)factor;	// 0x3665a431
- (void)setIcon:(id)icon horizontalOffset:(float)offset kerningFactor:(float)factor;	// 0x3665acbd
- (void)setLabel:(id)label;	// 0x3665afb5
- (void)setLabel:(id)label withAttributes:(id)attributes;	// 0x3665aff1
// converted property setter: - (void)setListIcon:(id)icon;	// 0x3665b239
- (void)setListIcon:(id)icon horizontalOffset:(float)offset kerningFactor:(float)factor;	// 0x3665b219
// converted property setter: - (void)setListIconHorizontalOffset:(float)offset;	// 0x3665b2c1
// converted property setter: - (void)setListIconKerningFactor:(float)factor;	// 0x3665b301
// converted property setter: - (void)setListTitle:(id)title;	// 0x3665b179
- (void)setListTitle:(id)title withAttributes:(id)attributes;	// 0x3665b0f9
// converted property setter: - (void)setMenuWidthFactor:(float)factor;	// 0x3665a379
- (void)setPrimaryInfoText:(id)text;	// 0x3665ad15
- (void)setPrimaryInfoText:(id)text withAttributes:(id)attributes;	// 0x3665ad29
- (void)setSecondaryInfoText:(id)text;	// 0x3665ae65
- (void)setSecondaryInfoText:(id)text withAttributes:(id)attributes;	// 0x3665ae79
// converted property setter: - (void)setSelectedItem:(long)item;	// 0x3665b495
// converted property setter: - (void)setSelectedObject:(id)object;	// 0x3665a5ed
- (void)setTitle:(id)title;	// 0x3665ac79
- (void)setUseCenteredLayout:(BOOL)layout;	// 0x3665a7fd
- (BOOL)shouldRefreshForUpdateToObject:(id)object;	// 0x3665a72d
- (int)soundForSelectingItem:(long)selectingItem;	// 0x3665b515
- (void)wasPushed;	// 0x3665a531
@end

