/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BROptionDialog.h"


@interface BRModalOptionDialog : BROptionDialog {
@private
	long _cancelIdx;	// 152 = 0x98
	BOOL _allowMenuButton;	// 156 = 0x9c
}
- (id)init;	// 0x3667b1c9
- (id)initAllowingMenuButton:(BOOL)button;	// 0x3667b1dd
- (void)_done:(id)done;	// 0x3667b37d
- (BOOL)brEventAction:(id)action;	// 0x3667b2ed
- (long)runModal;	// 0x3667b22d
- (void)setCancelIndex:(long)index;	// 0x3667b2dd
@end

