/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRNetworkMediaProvider.h"

@class NSMutableArray;

@interface BRMovieTrailersProvider : BRNetworkMediaProvider {
@private
	NSMutableArray *_mediaCollections;	// 12 = 0xc
	int _lastError;	// 16 = 0x10
}
@property(readonly, assign) int lastError;	// G=0x36663419; converted property
+ (void)initialize;	// 0x36662c89
+ (BOOL)trailersAvailable;	// 0x36662ded
- (id)init;	// 0x36662e89
- (BOOL)_addMediaAsset:(id)asset;	// 0x36752d21
- (void)_loadTrailers;	// 0x36663429
- (void)_loadTrailersWithResolution:(id)resolution forURL:(id)url;	// 0x36663641
- (void)_networkStatusChanged:(id)changed;	// 0x36662df1
- (void)_postLoadedNotification:(id)notification;	// 0x366635a5
- (void)dealloc;	// 0x36662f5d
- (int)errorCodeForProvider;	// 0x366633a1
// converted property getter: - (int)lastError;	// 0x36663419
- (int)load;	// 0x36663111
- (id)mediaForEntityName:(id)entityName;	// 0x36663029
- (id)mediaTypes;	// 0x36662fd9
- (id)providerID;	// 0x3666301d
- (int)unload;	// 0x366632cd
@end

