/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRXMLMediaAsset.h"


@interface BRMovieTrailer : BRXMLMediaAsset {
}
+ (id)movieTrailerFromMediaProvider:(id)mediaProvider;	// 0x36662809
- (id)mediaType;	// 0x36662855
- (id)titleForSorting;	// 0x36662871
@end

