/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRImage;

__attribute__((visibility("hidden")))
@interface BRMultiPartWidgetLayer : BRControl {
@private
	BOOL _suppressAnimations;	// 49 = 0x31
	BRControl *_topRightCornerControl;	// 52 = 0x34
	BRControl *_topEdgeControl;	// 56 = 0x38
	BRControl *_topLeftCornerControl;	// 60 = 0x3c
	BRControl *_rightEdgeControl;	// 64 = 0x40
	BRControl *_bottomRightCornerControl;	// 68 = 0x44
	BRControl *_bottomEdgeControl;	// 72 = 0x48
	BRControl *_bottomLeftCornerControl;	// 76 = 0x4c
	BRControl *_leftEdgeControl;	// 80 = 0x50
	BRControl *_centerControl;	// 84 = 0x54
	BRControl *_bottomDecoControl;	// 88 = 0x58
	BRControl *_topDecoControl;	// 92 = 0x5c
	float _centerOverlapFactor;	// 96 = 0x60
	float _sourceArtSceneHeight;	// 100 = 0x64
}
@property(assign, nonatomic) BRImage *bottomDeco;	// G=0x3670b149; S=0x3670b11d; 
@property(assign, nonatomic) BRControl *bottomDecoControl;	// G=0x3670bcfd; S=0x3670bd0d; @synthesize=_bottomDecoControl
@property(assign, nonatomic) BRImage *bottomEdge;	// G=0x3670b0e5; S=0x3670b0b9; 
@property(assign, nonatomic) BRControl *bottomEdgeControl;	// G=0x3670bc7d; S=0x3670bc8d; @synthesize=_bottomEdgeControl
@property(assign, nonatomic) BRImage *bottomLeftCorner;	// G=0x3670af55; S=0x3670af29; 
@property(assign, nonatomic) BRControl *bottomLeftCornerControl;	// G=0x3670bc9d; S=0x3670bcad; @synthesize=_bottomLeftCornerControl
@property(assign, nonatomic) BRImage *bottomRightCorner;	// G=0x3670aef1; S=0x3670aec5; 
@property(assign, nonatomic) BRControl *bottomRightCornerControl;	// G=0x3670bc5d; S=0x3670bc6d; @synthesize=_bottomRightCornerControl
@property(assign, nonatomic) BRImage *center;	// G=0x3670b211; S=0x3670b1e5; 
@property(assign, nonatomic) BRControl *centerControl;	// G=0x3670bcdd; S=0x3670bced; @synthesize=_centerControl
@property(assign, nonatomic) float centerOverlapFactor;	// G=0x3670bd3d; S=0x3670b4a9; @synthesize=_centerOverlapFactor
@property(assign, nonatomic) BRImage *leftEdge;	// G=0x3670b01d; S=0x3670aff1; 
@property(assign, nonatomic) BRControl *leftEdgeControl;	// G=0x3670bcbd; S=0x3670bccd; @synthesize=_leftEdgeControl
@property(assign, nonatomic) BRImage *rightEdge;	// G=0x3670afb9; S=0x3670af8d; 
@property(assign, nonatomic) BRControl *rightEdgeControl;	// G=0x3670bc3d; S=0x3670bc4d; @synthesize=_rightEdgeControl
@property(assign, nonatomic) float sourceArtSceneHeight;	// G=0x3670bd4d; S=0x3670bd5d; @synthesize=_sourceArtSceneHeight
@property(assign, nonatomic) BRImage *topDeco;	// G=0x3670b1ad; S=0x3670b181; 
@property(assign, nonatomic) BRControl *topDecoControl;	// G=0x3670bd1d; S=0x3670bd2d; @synthesize=_topDecoControl
@property(assign, nonatomic) BRImage *topEdge;	// G=0x3670b081; S=0x3670b055; 
@property(assign, nonatomic) BRControl *topEdgeControl;	// G=0x3670bbfd; S=0x3670bc0d; @synthesize=_topEdgeControl
@property(assign, nonatomic) BRImage *topLeftCorner;	// G=0x3670ae8d; S=0x3670ae61; 
@property(assign, nonatomic) BRControl *topLeftCornerControl;	// G=0x3670bc1d; S=0x3670bc2d; @synthesize=_topLeftCornerControl
@property(assign, nonatomic) BRImage *topRightCorner;	// G=0x3670ae29; S=0x3670adfd; 
@property(assign, nonatomic) BRControl *topRightCornerControl;	// G=0x3670bbdd; S=0x3670bbed; @synthesize=_topRightCornerControl
- (id)init;	// 0x3670ada1
- (id)_defaultActions;	// 0x3670bd6d
- (void)_setImage:(id)image inControlNamed:(id)controlNamed withAntialiasingMask:(unsigned)antialiasingMask;	// 0x3670be6d
- (float)animationDuration;	// 0x3670b5f5
- (id)animationTimingFunction;	// 0x3670b5fd
// declared property getter: - (id)bottomDeco;	// 0x3670b149
// declared property getter: - (id)bottomDecoControl;	// 0x3670bcfd
// declared property getter: - (id)bottomEdge;	// 0x3670b0e5
// declared property getter: - (id)bottomEdgeControl;	// 0x3670bc7d
// declared property getter: - (id)bottomLeftCorner;	// 0x3670af55
// declared property getter: - (id)bottomLeftCornerControl;	// 0x3670bc9d
// declared property getter: - (id)bottomRightCorner;	// 0x3670aef1
// declared property getter: - (id)bottomRightCornerControl;	// 0x3670bc5d
// declared property getter: - (id)center;	// 0x3670b211
// declared property getter: - (id)centerControl;	// 0x3670bcdd
// declared property getter: - (float)centerOverlapFactor;	// 0x3670bd3d
- (void)clearImageMap;	// 0x3670b249
- (CGSize)edgeSize;	// 0x3670b345
- (void)layoutSubcontrols;	// 0x3670b629
// declared property getter: - (id)leftEdge;	// 0x3670b01d
// declared property getter: - (id)leftEdgeControl;	// 0x3670bcbd
// declared property getter: - (id)rightEdge;	// 0x3670afb9
// declared property getter: - (id)rightEdgeControl;	// 0x3670bc3d
// declared property setter: - (void)setBottomDeco:(id)deco;	// 0x3670b11d
// declared property setter: - (void)setBottomDecoControl:(id)control;	// 0x3670bd0d
// declared property setter: - (void)setBottomEdge:(id)edge;	// 0x3670b0b9
// declared property setter: - (void)setBottomEdgeControl:(id)control;	// 0x3670bc8d
// declared property setter: - (void)setBottomLeftCorner:(id)corner;	// 0x3670af29
// declared property setter: - (void)setBottomLeftCornerControl:(id)control;	// 0x3670bcad
// declared property setter: - (void)setBottomRightCorner:(id)corner;	// 0x3670aec5
// declared property setter: - (void)setBottomRightCornerControl:(id)control;	// 0x3670bc6d
// declared property setter: - (void)setCenter:(id)center;	// 0x3670b1e5
// declared property setter: - (void)setCenterControl:(id)control;	// 0x3670bced
// declared property setter: - (void)setCenterOverlapFactor:(float)factor;	// 0x3670b4a9
// declared property setter: - (void)setLeftEdge:(id)edge;	// 0x3670aff1
// declared property setter: - (void)setLeftEdgeControl:(id)control;	// 0x3670bccd
// declared property setter: - (void)setRightEdge:(id)edge;	// 0x3670af8d
// declared property setter: - (void)setRightEdgeControl:(id)control;	// 0x3670bc4d
// declared property setter: - (void)setSourceArtSceneHeight:(float)height;	// 0x3670bd5d
- (void)setSuppressAnimations:(BOOL)animations;	// 0x3670b4c9
// declared property setter: - (void)setTopDeco:(id)deco;	// 0x3670b181
// declared property setter: - (void)setTopDecoControl:(id)control;	// 0x3670bd2d
// declared property setter: - (void)setTopEdge:(id)edge;	// 0x3670b055
// declared property setter: - (void)setTopEdgeControl:(id)control;	// 0x3670bc0d
// declared property setter: - (void)setTopLeftCorner:(id)corner;	// 0x3670ae61
// declared property setter: - (void)setTopLeftCornerControl:(id)control;	// 0x3670bc2d
// declared property setter: - (void)setTopRightCorner:(id)corner;	// 0x3670adfd
// declared property setter: - (void)setTopRightCornerControl:(id)control;	// 0x3670bbed
// declared property getter: - (float)sourceArtSceneHeight;	// 0x3670bd4d
// declared property getter: - (id)topDeco;	// 0x3670b1ad
// declared property getter: - (id)topDecoControl;	// 0x3670bd1d
// declared property getter: - (id)topEdge;	// 0x3670b081
// declared property getter: - (id)topEdgeControl;	// 0x3670bbfd
// declared property getter: - (id)topLeftCorner;	// 0x3670ae8d
// declared property getter: - (id)topLeftCornerControl;	// 0x3670bc1d
// declared property getter: - (id)topRightCorner;	// 0x3670ae29
// declared property getter: - (id)topRightCornerControl;	// 0x3670bbdd
- (void)updateAnimations;	// 0x3670b511
@end

