/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRSingleton.h"
#import "ATVProgressMonitorConfiguration.h"

@class NSTimer, NSDictionary, NSNumber, NSString, BRBackgroundTask, NSMutableDictionary, NSArray;
@protocol BRMediaProvider;

@interface BRMusicStore : BRSingleton <ATVProgressMonitorConfiguration> {
@private
	int _musicStoreLoadState;	// 4 = 0x4
	NSDictionary *_storeFrontsDictionary;	// 8 = 0x8
	NSDictionary *_storeFrontCodesDictionary;	// 12 = 0xc
	NSNumber *_storeFrontID;	// 16 = 0x10
	NSArray *_rootCollection;	// 20 = 0x14
	NSArray *_partnerData;	// 24 = 0x18
	id<BRMediaProvider> _provider;	// 28 = 0x1c
	BOOL _initializing;	// 32 = 0x20
	NSString *_selectedLanguageCode;	// 36 = 0x24
	NSString *_storeMainMenuPresentsKey;	// 40 = 0x28
	dispatch_queue_s *_urlBagQueue;	// 44 = 0x2c
	NSDictionary *_urlBag;	// 48 = 0x30
	BRBackgroundTask *_bagReloadTask;	// 52 = 0x34
	NSTimer *_retryTimer;	// 56 = 0x38
	NSString *_platform;	// 60 = 0x3c
	BOOL _initializePlatform;	// 64 = 0x40
	NSMutableDictionary *_languageIDForLanguageCodeCache;	// 68 = 0x44
	BOOL _dsidSentWithLastStoreRefresh;	// 72 = 0x48
}
@property(retain) id currentStoreFrontID;	// G=0x367486b9; S=0x36748ab9; converted property
@property(assign) BOOL dsidSentWithLastStoreRefresh;	// G=0x3674ac8d; S=0x3674ac9d; @synthesize=_dsidSentWithLastStoreRefresh
@property(assign) int musicStoreLoadState;	// G=0x367484a1; S=0x367484b1; converted property
@property(readonly, retain) NSArray *rootCollection;	// G=0x3674a7dd; converted property
+ (void)setSingleton:(id)singleton;	// 0x36748219
+ (id)singleton;	// 0x36748229
- (id)init;	// 0x36748239
- (id)URLBagEntryForKey:(id)key;	// 0x36748509
- (id)_acceptLanguage;	// 0x3674d199
- (void)_bootstrapMusicStore;	// 0x3674ae2d
- (void)_bootstrapMusicStoreFromURL:(id)url;	// 0x3674ae5d
- (id)_canonicalNameForMediaType:(id)mediaType;	// 0x3674acb9
- (id)_currentStoreFrontsFilePath;	// 0x3674cdc1
- (id)_defaultStoreFrontsFilePath;	// 0x3674cd91
- (id)_determineLanguageCodeForStoreFront:(id)storeFront;	// 0x3674d439
- (void)_initializeGhostrider;	// 0x3674c3b5
- (BOOL)_initializeMusicStore;	// 0x3674b975
- (id)_languageIDForLanguageCode:(id)languageCode;	// 0x3674d329
- (BOOL)_loadRootCollection:(id)collection;	// 0x3674ba05
- (double)_maxAgeFromResponseHeaders:(id)responseHeaders;	// 0x3674c575
- (void)_networkStateChanged:(id)changed;	// 0x3674c841
- (id)_primaryMusicStoreURL;	// 0x3674acad
- (void)_requestStoreFrontList;	// 0x3674c93d
- (void)_retryRootCollection:(id)collection;	// 0x3674c395
- (void)_rootCollectionLoaded:(id)loaded;	// 0x3674bd95
- (void)_seedMusicStore:(id)store;	// 0x3674af71
- (BOOL)_seedMusicStoreWithBag:(id)bag;	// 0x3674b81d
- (void)_seedRequestProcessed:(id)processed;	// 0x3674b431
- (void)_setCurrentStoreFrontID:(id)anId language:(id)language platform:(id)platform;	// 0x3674d0cd
- (void)_setRootCollection:(id)collection;	// 0x3674bed5
- (void)_storeFrontListRequestProcessed:(id)processed;	// 0x3674ca91
- (id)_storeFrontsDictionary;	// 0x3674cdf5
- (id)_storeLanguageID;	// 0x3674d21d
- (void)_storeLoadFailed:(id)failed;	// 0x3674ad85
- (void)_updateDateAndTimeFromResponse:(id)response;	// 0x3674c6e9
- (void)_updateReloadTaskWithInterval:(double)interval;	// 0x3674b2f9
- (void)_updateStoreFrontFromResponse:(id)response;	// 0x3674c675
- (id)_ytURLDictPath;	// 0x367490a9
- (id)bandwidthHintReadyToPlayMaxTimeInSeconds;	// 0x3674a1ad
- (id)beaconingPuntRatio;	// 0x36749c89
- (id)beaconingURLString;	// 0x36749ba9
- (id)bookmarkSaveInterval;	// 0x36749f29
- (id)cacheBusterURLForURL:(id)url;	// 0x367486b5
- (id)commonHeaders;	// 0x3674a4c5
// converted property getter: - (id)currentStoreFrontID;	// 0x367486b9
- (id)currentStoreFrontISO3166Code;	// 0x36748905
- (void)dealloc;	// 0x36748361
- (void)decomposeCompositeStoreFrontHeader:(id)header;	// 0x36748d59
- (void)delayedRootCollectionReset;	// 0x3674aac9
- (id)downloadCapBytesSpeedtest;	// 0x367499e9
- (id)downloadCapInSecondsSpeedtest;	// 0x36749909
- (id)downloadMovieSpeedTestURLsArray;	// 0x36749829
- (id)downloadSpeedTestKVSDomain;	// 0x36749659
- (id)downloadSpeedTestPostResultsURLString;	// 0x36749ac9
- (id)downloadSpeedTestURLsArray;	// 0x36749749
// declared property getter: - (BOOL)dsidSentWithLastStoreRefresh;	// 0x3674ac8d
- (id)keyValueStoreGetAllURLString;	// 0x36749d69
- (id)keyValueStorePutAllURLString;	// 0x36749e49
- (id)matchLogoPath;	// 0x3674a409
- (id)matchStoreCategory;	// 0x3674a329
// converted property getter: - (int)musicStoreLoadState;	// 0x367484a1
- (id)previewBandwidthHintPromptTime;	// 0x3674a031
- (id)provider;	// 0x36748ead
- (void)purgeMusicStore;	// 0x36748fed
- (void)refreshURLBag;	// 0x36748491
// converted property getter: - (id)rootCollection;	// 0x3674a7dd
- (id)rootCollectionForMediaType:(id)mediaType;	// 0x3674a891
// converted property setter: - (void)setCurrentStoreFrontID:(id)anId;	// 0x36748ab9
- (void)setCurrentStoreFrontID:(id)anId language:(id)language;	// 0x36748acd
// declared property setter: - (void)setDsidSentWithLastStoreRefresh:(BOOL)lastStoreRefresh;	// 0x3674ac9d
// converted property setter: - (void)setMusicStoreLoadState:(int)state;	// 0x367484b1
- (id)storeFronts;	// 0x3674abed
- (id)storeHeadersDictionary;	// 0x3674a5e5
- (id)storeHeadersWithDsid;	// 0x365a30a9
- (id)storeMainMenuPresentsURLKey;	// 0x36749255
- (id)storeRecommendationsURL;	// 0x3674938d
- (id)storeRelatedMoviesURLString;	// 0x36749499
- (id)storeViewMovieURLString;	// 0x36749579
- (id)userAgent;	// 0x3674a6cd
- (id)vendorBags;	// 0x3674aaa1
- (id)ytAuthURLBase;	// 0x36749199
- (id)ytURLBase;	// 0x367490dd
@end

