//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRBaseMetadataPopulator.h"

__attribute__((visibility("hidden")))
@interface BRMusicAlbumMetadataPopulator : BRBaseMetadataPopulator
{
}

- (void)populateMetadataLabels:(id *)arg1 andValues:(id *)arg2 forAsset:(id)arg3;

@end

