//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRSingleton.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface BRNetworkMonitor : BRSingleton
{
    NSTimer *_networkDropTimer;
}

+ (void)setSingleton:(id)arg1;
+ (id)singleton;
- (void)_completeNetworkTransition;
- (void)handleSysConfigCallbackWithStore:(struct __SCDynamicStore *)arg1 changedKeys:(struct __CFArray *)arg2 info:(void *)arg3;

@end

