//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRAlertController.h>

@interface BRNetworkAlertController : BRAlertController
{
}

- (void)_networkStatusChanged:(id)arg1;
- (void)dealloc;
- (id)initWithType:(int)arg1 titled:(id)arg2 primaryText:(id)arg3 secondaryText:(id)arg4;

@end

