/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library

@class NSSet, NSString;
@protocol BRControlFactory;

@interface BRNowPlayingProvider : NSObject <BRProvider> {
@private
	id<BRControlFactory> _factory;	// 4 = 0x4
	NSSet *_types;	// 8 = 0x8
	NSString *_playerMediaAssetID;	// 12 = 0xc
}
+ (id)providerForTypes:(id)types;	// 0x36716d29
- (void)_checkPlayerState;	// 0x3671716d
- (id)_initWithTypes:(id)types;	// 0x36716ed1
- (void)_playerStateChanged:(id)changed;	// 0x3671711d
- (id)controlFactory;	// 0x36716e19
- (id)dataAtIndex:(long)index;	// 0x36716e81
- (long)dataCount;	// 0x36716e69
- (void)dealloc;	// 0x36716d75
- (id)hashForDataAtIndex:(long)index;	// 0x36716ec5
@end

