//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BROptionDialog.h>

@interface BROptionAlertControl : BROptionDialog
{
    long _cancelIdx;
}

+ (int)postAlertWithTitle:(id)arg1 primaryText:(id)arg2 secondaryText:(id)arg3 firstButton:(id)arg4 secondButton:(id)arg5 thirdButton:(id)arg6 defaultFocus:(int)arg7;
+ (int)postAlertWithTitleAndCancel:(id)arg1 primaryText:(id)arg2 secondaryText:(id)arg3 firstButton:(id)arg4 secondButton:(id)arg5 thirdButton:(id)arg6 defaultFocus:(int)arg7 identifier:(id)arg8 cancelIndex:(int)arg9;
+ (int)postDeleteConfirmationWithName:(id)arg1;
+ (void)postError:(id)arg1;
- (BOOL)_itemSelected:(id)arg1;
- (BOOL)brEventAction:(id)arg1;
- (void)setCancelIndex:(long)arg1;

@end

