/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRTextField.h"
#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRPasscodeSelectionLayer, BRDeviceKeyboardMessage;
@protocol BRTextFieldDelegate;

@interface BRPasscodeEntryControl : BRControl <BRTextField> {
@private
	BRPasscodeSelectionLayer *_passcodeLayer;	// 48 = 0x30
	unsigned _numDigits;	// 52 = 0x34
	BOOL _isUserEditable;	// 56 = 0x38
	CGSize _passcodeLayerSize;	// 60 = 0x3c
	BRDeviceKeyboardMessage *_deviceKeyboardMessage;	// 68 = 0x44
	id<BRTextFieldDelegate> _textFieldDelegate;	// 72 = 0x48
}
- (id)initWithNumDigits:(unsigned)numDigits userEditable:(BOOL)editable hideDigits:(BOOL)digits;	// 0x366f04a1
- (void)_handlePlayPauseButton:(id)button;	// 0x366f0e85
- (void)_layoutUI;	// 0x366f0ef5
- (void)_shakeAnimationCompleted:(id)completed;	// 0x366f0a09
- (id)accessibilityLabel;	// 0x366f154d
- (id)accessibilityTraits;	// 0x366f14c9
- (BOOL)brEventAction:(id)action;	// 0x366f0a61
- (void)controlWasFocused;	// 0x366f0d45
- (void)controlWasUnfocused;	// 0x366f0dc9
- (void)dealloc;	// 0x366f0609
- (void)deviceKeyboardClose;	// 0x366f0f39
- (void)deviceKeyboardMessageHandler:(id)handler;	// 0x366f10d5
- (void)deviceKeyboardUpdate:(BOOL)update;	// 0x366f0fb9
- (BOOL)isAccessibilityElement;	// 0x366f14c5
- (CGSize)preferredSizeFromScreenSize:(CGSize)screenSize;	// 0x366f0699
- (void)reset;	// 0x366f0769
- (void)setDelegate:(id)delegate;	// 0x366f0739
- (void)setFrame:(CGRect)frame;	// 0x366f0a19
- (void)setInitialPasscode:(id)passcode;	// 0x366f0749
- (void)setKeyboardTitle:(id)title;	// 0x366f0e09
- (void)setString:(id)string;	// 0x366f0e65
- (void)shake;	// 0x366f0809
- (id)stringValue;	// 0x366f0e45
- (float)widthOfDigitsFromScreenSize:(CGSize)screenSize;	// 0x366f0719
@end

