//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRImage, NSString;

__attribute__((visibility("hidden")))
@interface BRPairingPinControl : BRControl
{
    BRImage *_boxImage;
    NSString *_pin;
}

- (id)PIN;
- (id)_layerForPINDigit:(id)arg1;
- (id)accessibilityLabel;
- (void)dealloc;
- (id)init;
- (void)layoutSubcontrols;
- (void)setPIN:(id)arg1;

@end

