/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, BRPasscodeSelectionWidget, NSArray, BRImageControl;

__attribute__((visibility("hidden")))
@interface BRPasscodeSelectionLayer : BRControl {
@private
	NSArray *_backgroundLayers;	// 48 = 0x30
	NSArray *_digitLayers;	// 52 = 0x34
	NSArray *_bulletLayers;	// 56 = 0x38
	BRImageControl *_arrowsLayer;	// 60 = 0x3c
	BRPasscodeSelectionWidget *_selectionWidget;	// 64 = 0x40
	BRTextControl *_doneLayer;	// 68 = 0x44
	BOOL _isUserEditable;	// 72 = 0x48
	unsigned _numDigits;	// 76 = 0x4c
	BOOL _hideDigits;	// 80 = 0x50
	int _selection;	// 84 = 0x54
}
@property(retain) id passcode;	// G=0x3671b6b5; S=0x3671b7f9; converted property
- (id)initWithNumDigits:(unsigned)numDigits userEditable:(BOOL)editable hideDigits:(BOOL)digits;	// 0x3671aac5
- (void)_adjustDigitVisibility:(id)visibility;	// 0x3671cfb9
- (CGRect)_arrowsFrameForSelection:(int)selection;	// 0x3671c7e1
- (id)_buildArrowsLayer;	// 0x3671c155
- (id)_buildBackgroundLayers;	// 0x3671bdc9
- (id)_buildBulletLayers;	// 0x3671bff9
- (id)_buildDigitLayers;	// 0x3671bec1
- (id)_buildDoneLayer;	// 0x3671c219
- (CGRect)_cellFrameForSelection:(int)selection;	// 0x3671ca01
- (CGRect)_digitFrameForSelection:(int)selection digit:(id)digit;	// 0x3671c90d
- (void)_hideDigitAtIndex:(int)index;	// 0x3671cf2d
- (float)_layoutUIWithHeight:(float)height;	// 0x3671c2f5
- (CGRect)_selectionWidgetFrameForSelection:(int)selection;	// 0x3671c71d
- (void)_setDigitHighlighted:(BOOL)highlighted atIndex:(int)index;	// 0x3671cd6d
- (void)_setDigitValue:(id)value atIndex:(int)index;	// 0x3671ce59
- (void)_setSelection:(int)selection;	// 0x3671cb2d
- (id)accessibilityLabel;	// 0x3671d01d
- (id)accessibilityTraits;	// 0x3671d189
- (void)dealloc;	// 0x3671ad45
- (BOOL)decrementSelection;	// 0x3671b3c5
- (BOOL)digitsHidden;	// 0x3671bbc1
- (BOOL)doneButtonSelected;	// 0x3671b9e5
- (void)hideDigits:(int)digits;	// 0x3671bbd1
- (BOOL)incrementSelection;	// 0x3671b19d
- (BOOL)moveSelectionLeft;	// 0x3671b0c5
- (BOOL)moveSelectionRight;	// 0x3671afd9
// converted property getter: - (id)passcode;	// 0x3671b6b5
- (CGRect)preferredFrameForScreenSize:(CGSize)screenSize;	// 0x3671adf5
- (void)reset;	// 0x3671ba31
- (void)setFrame:(CGRect)frame;	// 0x3671bad1
// converted property setter: - (void)setPasscode:(id)passcode;	// 0x3671b7f9
- (BOOL)setSelection:(int)selection;	// 0x3671b5d9
- (void)showDigits;	// 0x3671bcb5
- (float)widthOfDigitsForScreenSize:(CGSize)screenSize;	// 0x3671af4d
@end

