//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRController.h>

#import "BRTextFieldDelegate.h"

@class BRHeaderControl, BRPasscodeEntryControl, BRTextControl, NSDictionary, NSString;

@interface BRParentalControlsPasscodeController : BRController <BRTextFieldDelegate>
{
    BRController *_guardedController;
    BRPasscodeEntryControl *_editor;
    BRHeaderControl *_header;
    BRTextControl *_prompt;
    NSString *_passcodeToConfirm;
    int _mode;
    NSDictionary *_userInfo;
}

+ (id)passcodeEntryControllerGuarding:(id)arg1 hideDigits:(BOOL)arg2;
- (void)_passcodeEnteredForConfirm:(id)arg1;
- (void)_passcodeEnteredForEntry:(id)arg1;
- (void)_passcodeEnteredForSet:(id)arg1;
- (id)accessibilityLabel;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 prompt:(id)arg2 mode:(int)arg3 guarding:(id)arg4 hideDigits:(BOOL)arg5;
- (void)setFrame:(struct CGRect)arg1;
- (void)setIcon:(id)arg1 horizontalOffset:(float)arg2 kerningFactor:(float)arg3;
- (void)setIconScaleFactor:(float)arg1;
- (void)setPasscodeToConfirm:(id)arg1;
- (void)setUserInfo:(id)arg1;
- (void)textDidChange:(id)arg1;
- (void)textDidEndEditing:(id)arg1;
- (id)userInfo;

@end

