/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRDotArrayControl, BRCursorControl, NSString, BRHeaderControl, BRImageControl, BRImage;

@interface BRPageStripView : BRControl {
@private
	id _dataSource;	// 48 = 0x30
	id _delegate;	// 52 = 0x34
	BRHeaderControl *_headerControl;	// 56 = 0x38
	BRCursorControl *_cursor;	// 60 = 0x3c
	BRDotArrayControl *_dotControl;	// 64 = 0x40
	BRImageControl *_overlayImageControl;	// 68 = 0x44
	BRControl *_descControl;	// 72 = 0x48
	int _selectedIndex;	// 76 = 0x4c
	BRControl *_prevPrevControl;	// 80 = 0x50
	BRControl *_prevControl;	// 84 = 0x54
	BRControl *_selectedControl;	// 88 = 0x58
	BRControl *_nextControl;	// 92 = 0x5c
	BRControl *_nextNextControl;	// 96 = 0x60
}
@property(assign, nonatomic) id dataSource;	// G=0x3666d0e9; S=0x3666ca01; @synthesize=_dataSource
@property(assign, nonatomic) id delegate;	// G=0x3666d0f9; S=0x3666d109; @synthesize=_delegate
@property(readonly, assign, nonatomic) BRDotArrayControl *dotControl;	// G=0x3666d139; @synthesize=_dotControl
@property(retain, nonatomic) BRImage *headerImage;	// G=0x3666cb09; S=0x3666caa1; 
@property(retain, nonatomic) BRImage *overlayImage;	// G=0x3666ca41; S=0x3666ca21; 
@property(assign, nonatomic) int selectedIndex;	// G=0x3666d119; S=0x3666d129; @synthesize=_selectedIndex
@property(copy, nonatomic) NSString *title;	// G=0x3666ca81; S=0x3666ca61; 
+ (id)pageStripView;	// 0x3666c791
- (id)init;	// 0x3666c7c9
- (BOOL)_loadLeft;	// 0x3666d7c1
- (BOOL)_loadRight;	// 0x3666ddb9
- (CGPoint)_nextNextPos;	// 0x3666e709
- (CGPoint)_nextPos;	// 0x3666e66d
- (CGPoint)_prevPos;	// 0x3666e559
- (CGPoint)_prevPrevPos;	// 0x3666e4b5
- (void)_removeNextNext:(id)next;	// 0x3666e7a9
- (void)_removePrevPrev:(id)prev;	// 0x3666e7e9
- (CGPoint)_selectedPos;	// 0x3666e5f5
- (void)_setPagesTargetBounds;	// 0x3666d149
- (float)_xPosOffset;	// 0x3666e3b9
- (float)_yPosOffset;	// 0x3666e45d
- (BOOL)brEventAction:(id)action;	// 0x3666cbdd
// declared property getter: - (id)dataSource;	// 0x3666d0e9
- (void)dealloc;	// 0x3666c901
// declared property getter: - (id)delegate;	// 0x3666d0f9
// declared property getter: - (id)dotControl;	// 0x3666d139
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x3666cb29
// declared property getter: - (id)headerImage;	// 0x3666cb09
- (void)layoutSubcontrols;	// 0x3666cfd1
// declared property getter: - (id)overlayImage;	// 0x3666ca41
- (void)reload;	// 0x3666cd15
// declared property getter: - (int)selectedIndex;	// 0x3666d119
// declared property setter: - (void)setDataSource:(id)source;	// 0x3666ca01
// declared property setter: - (void)setDelegate:(id)delegate;	// 0x3666d109
// declared property setter: - (void)setHeaderImage:(id)image;	// 0x3666caa1
// declared property setter: - (void)setOverlayImage:(id)image;	// 0x3666ca21
// declared property setter: - (void)setSelectedIndex:(int)index;	// 0x3666d129
// declared property setter: - (void)setTitle:(id)title;	// 0x3666ca61
// declared property getter: - (id)title;	// 0x3666ca81
@end

