/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRPhotoDataStoreProvider.h"
#import "BRPhotoProviderForCollection.h"


@interface BRPhotoDataStoreProviderForCollection : BRPhotoDataStoreProvider <BRPhotoProviderForCollection> {
}
@property(assign) BOOL vendPhotoDataOnly;	// G=0x366fce11; S=0x366fce0d; converted property
+ (id)providerWithDataStore:(id)dataStore controlFactory:(id)factory;	// 0x366fcd91
- (BOOL)canHaveZeroData;	// 0x366fcde1
- (id)collection;	// 0x366fcde5
// converted property setter: - (void)setVendPhotoDataOnly:(BOOL)only;	// 0x366fce0d
// converted property getter: - (BOOL)vendPhotoDataOnly;	// 0x366fce11
@end

