/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBaseMediaCollection.h"

@class NSArray, BRMediaCollectionType, NSString;

@interface BRPhotoMediaCollection : BRBaseMediaCollection {
@private
	NSString *_collectionName;	// 8 = 0x8
	NSString *_keyAssetID;	// 12 = 0xc
	NSString *_description;	// 16 = 0x10
	NSArray *_mediaAssets;	// 20 = 0x14
	NSString *_collectionID;	// 24 = 0x18
	BRMediaCollectionType *_collectionType;	// 28 = 0x1c
	double _date;	// 32 = 0x20
	BOOL _dateCalculated;	// 40 = 0x28
}
@property(retain) NSString *collectionID;	// G=0x36665ffd; S=0x366660c9; converted property
@property(retain) NSString *collectionName;	// G=0x366659ed; S=0x36665ab9; converted property
@property(retain) BRMediaCollectionType *collectionType;	// G=0x36666371; S=0x36666381; converted property
@property(retain) id date;	// G=0x36666391; S=0x366663fd; converted property
@property(retain) NSString *description;	// G=0x36665e61; S=0x36665f2d; converted property
@property(retain) NSString *keyAssetID;	// G=0x36665bc9; S=0x36665c95; converted property
@property(retain) NSArray *mediaAssets;	// G=0x36666199; S=0x36666265; converted property
+ (id)collectionWithCollectionInfo:(id)collectionInfo;	// 0x366657ed
- (id)initWithCollectionInfo:(id)collectionInfo;	// 0x36665829
- (void)_calculateMostRecentDate;	// 0x36666449
- (id)archivableCollectionInfo;	// 0x36666445
// converted property getter: - (id)collectionID;	// 0x36665ffd
// converted property getter: - (id)collectionName;	// 0x366659ed
// converted property getter: - (id)collectionType;	// 0x36666371
// converted property getter: - (id)date;	// 0x36666391
- (void)dealloc;	// 0x36665855
// converted property getter: - (id)description;	// 0x36665e61
- (unsigned)hash;	// 0x366658f1
- (BOOL)isEqual:(id)equal;	// 0x36665931
- (BOOL)isLibrary;	// 0x36666441
- (id)keyAsset;	// 0x36665d65
// converted property getter: - (id)keyAssetID;	// 0x36665bc9
// converted property getter: - (id)mediaAssets;	// 0x36666199
- (id)photoAssets;	// 0x36666361
- (id)playbackOptions;	// 0x36665bc5
// converted property setter: - (void)setCollectionID:(id)anId;	// 0x366660c9
// converted property setter: - (void)setCollectionName:(id)name;	// 0x36665ab9
// converted property setter: - (void)setCollectionType:(id)type;	// 0x36666381
// converted property setter: - (void)setDate:(id)date;	// 0x366663fd
// converted property setter: - (void)setDescription:(id)description;	// 0x36665f2d
// converted property setter: - (void)setKeyAssetID:(id)anId;	// 0x36665c95
// converted property setter: - (void)setMediaAssets:(id)assets;	// 0x36666265
- (id)title;	// 0x366659dd
@end

