/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControlHeightFactory.h"
#import <NSObject.h> // Unknown library
#import "BRControlFactory.h"

@class NSDateFormatter;
@protocol BRSelectionHandler;

@interface BRPhotoControlFactory : NSObject <BRControlFactory, BRControlHeightFactory> {
@private
	id<BRSelectionHandler> _selectionHandler;	// 4 = 0x4
	NSDateFormatter *_formatter;	// 8 = 0x8
	BOOL _useMinimumImages;	// 12 = 0xc
	BOOL _useLocalProviders;	// 13 = 0xd
}
@property(readonly, retain) NSDateFormatter *formatter;	// G=0x366fb33d; converted property
@property(retain) id selectionHandler;	// G=0x366fb06d; S=0x366fb07d; converted property
+ (id)mainMenuFactory;	// 0x366fadbd
+ (id)standardFactory;	// 0x366fad71
- (id)initForMainMenu:(BOOL)mainMenu;	// 0x366fae09
- (id)_cyclerForData:(id)data;	// 0x366fb701
- (id)_cyclerItemForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x366fb9f1
- (void)_decorateControlWithPlayIcon:(id)playIcon forMediaObject:(id)mediaObject;	// 0x366fc0f1
- (id)_gridItemForData:(id)data;	// 0x366fb539
- (id)_menuItemForData:(id)data;	// 0x366fb3d1
- (id)_previewControlForData:(id)data;	// 0x366fc019
- (id)_shelfItemForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x366fc3b9
- (id)_subtitleForCollection:(id)collection;	// 0x366fc5b1
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x366faf05
- (void)dealloc;	// 0x366faea5
// converted property getter: - (id)formatter;	// 0x366fb33d
- (float)heightForControlForData:(id)data requestedBy:(id)by;	// 0x366fb0bd
// converted property getter: - (id)selectionHandler;	// 0x366fb06d
// converted property setter: - (void)setSelectionHandler:(id)handler;	// 0x366fb07d
- (void)setUseMinimumImages:(BOOL)images;	// 0x366fb31d
- (BOOL)useMinumumImages;	// 0x366fb32d
@end

