//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRController.h>

#import "BRFullScreenPhotoControllerDelegate.h"

@class BRCursorControl, BRGridControl, BRPanelControl, BRPhotoBrowserBannerButton, BRPhotoBrowserHeaderControl, BRScrollControl, BRTextControl, BRWaitSpinnerControl, NSDateFormatter, NSString, NSTimer;

@interface BRPhotoBrowserController : BRController <BRFullScreenPhotoControllerDelegate>
{
    id <BRProvider> _provider;
    int _style;
    NSString *_subtitleKey;
    NSDateFormatter *_formatter;
    long _providerDataCount;
    BRPhotoBrowserHeaderControl *_header;
    BRGridControl *_grid;
    BRWaitSpinnerControl *_spinner;
    BRCursorControl *_cursorControl;
    BRScrollControl *_scroller;
    BRPanelControl *_bannerControl;
    BRTextControl *_noContentMessageControl;
    NSTimer *_noContentMessageTimer;
    BOOL _isNetworkDependent;
    BOOL _isValidWithZeroData;
    BOOL _useCorkBoardBackground;
    BRPhotoBrowserBannerButton *_slideshowButton;
    BRPhotoBrowserBannerButton *_settingsButton;
    CDUnknownBlockType _screenSaverSetCollectionBlock;
    double noContentErrorDisplayDelay;
}

+ (id)controllerForProvider:(id)arg1;
+ (id)controllerForProvider:(id)arg1 style:(int)arg2;
- (id)_containerCollection;
- (void)_focusChanged:(id)arg1;
- (void)_handleDeletePhotoStreamItemSelection:(id)arg1;
- (void)_handleProviderDataCountChange;
- (void)_handleSelection:(id)arg1;
- (void)_handleSettingsSelection:(id)arg1;
- (void)_handleSlideshowSelection:(id)arg1;
- (void)_hideNoContentMessage;
- (void)_initiateSlideshowPlaybackAtIndex:(long)arg1 inCollection:(id)arg2 withOptions:(id)arg3;
- (struct __ATVMediaItem *)_mediaItemInContainingControl:(id)arg1;
- (void)_noContentTimerFired:(id)arg1;
- (void)_playerStateChanged:(id)arg1;
- (void)_providerUpdated:(id)arg1;
- (void)_setupControls;
- (void)_showNoContentMessage;
- (void)_slideshowPlayerAssetChanged:(id)arg1;
- (id)_subtitleStringForKey:(id)arg1;
- (id)accessibilityLabel;
- (void)addBannerControl:(id)arg1;
- (BOOL)brEventAction:(id)arg1;
- (int)columnCount;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (int)cursorStyle;
- (void)dealloc;
- (BOOL)displaysCount;
- (float)dividerBrightness;
- (CDStruct_1420b1e7)horizontalGap;
- (id)icon;
- (float)iconVerticalOffset;
- (id)initWithProvider:(id)arg1;
- (id)initWithProvider:(id)arg1 style:(int)arg2;
- (BOOL)isNetworkDependent;
- (BOOL)isValidAfterDataUpdate;
- (BOOL)isValidWithZeroData;
- (void)layoutSubcontrols;
@property(nonatomic) double noContentErrorDisplayDelay; // @synthesize noContentErrorDisplayDelay;
- (void)photoPlaybackWillStartForPlayer:(id)arg1;
- (id)providersForContextMenu;
@property(copy, nonatomic) NSString *rightJustifiedText;
@property(copy, nonatomic) CDUnknownBlockType screenSaverSetCollectionBlock; // @synthesize screenSaverSetCollectionBlock=_screenSaverSetCollectionBlock;
- (void)setColumnCount:(int)arg1;
- (void)setCursorStyle:(int)arg1;
- (void)setDisplaysCount:(BOOL)arg1;
- (void)setDividerBrightness:(float)arg1;
- (void)setHorizontalGap:(CDStruct_1420b1e7)arg1;
- (void)setIcon:(id)arg1;
- (void)setIconVerticalOffset:(float)arg1;
- (void)setIndex:(unsigned int)arg1;
- (void)setIsNetworkDependent:(BOOL)arg1;
- (void)setIsValidWithZeroData:(BOOL)arg1;
- (void)setLastViewedSlideIndex:(int)arg1;
- (void)setProvider:(id)arg1;
- (void)setStyle:(int)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setSubtitleKey:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setVerticalGap:(CDStruct_1420b1e7)arg1;
- (int)style;
- (id)subtitle;
- (id)subtitleKey;
- (id)title;
- (CDStruct_1420b1e7)verticalGap;
- (void)wasBuried;
- (void)wasExhumed;

@end

