/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRBaseMediaAsset.h"
#import "AppleTV-Structs.h"

@class BRImageManager, NSString;

@interface BRPhotoMediaAsset : BRBaseMediaAsset {
@private
	NSString *_thumbURL;	// 8 = 0x8
	NSString *_coverArtURL;	// 12 = 0xc
	NSString *_fullURL;	// 16 = 0x10
	NSString *_artID;	// 20 = 0x14
	double _dateTakenTimerInterval;	// 24 = 0x18
	BOOL _isLocal;	// 32 = 0x20
	NSString *_title;	// 36 = 0x24
}
@property(retain) NSString *artID;	// G=0x366656cd; S=0x366655fd; converted property
@property(retain) NSString *coverArtURL;	// G=0x36665251; S=0x3666531d; converted property
@property(retain) id dateTaken;	// G=0x366653ed; S=0x36665435; converted property
@property(retain) NSString *fullURL;	// G=0x36664f19; S=0x36664fe5; converted property
@property(assign) BOOL isLocal;	// G=0x36664a15; S=0x36664a05; converted property
@property(readonly, assign) BRImageManager *preferredImageManager;	// G=0x366657d1; 
@property(retain) NSString *thumbURL;	// G=0x366650b5; S=0x36665181; converted property
@property(retain) NSString *title;	// G=0x36665461; S=0x3666552d; converted property
- (id)init;	// 0x3666487d
// converted property getter: - (id)artID;	// 0x366656cd
- (id)assetID;	// 0x36664a45
- (id)coverArt;	// 0x36664dd9
- (id)coverArtID;	// 0x36664b69
// converted property getter: - (id)coverArtURL;	// 0x36665251
// converted property getter: - (id)dateTaken;	// 0x366653ed
- (void)dealloc;	// 0x366648c1
- (CGRect)faceRectForFaceCollectionID:(id)faceCollectionID;	// 0x36665799
- (id)faces;	// 0x366657bd
- (id)fullSizeArt;	// 0x36664e69
- (id)fullSizeArtID;	// 0x36664c59
// converted property getter: - (id)fullURL;	// 0x36664f19
- (unsigned)hash;	// 0x3666495d
- (id)imageProxy;	// 0x36664a25
- (BOOL)isEqual:(id)equal;	// 0x36664985
// converted property getter: - (BOOL)isLocal;	// 0x36664a15
- (id)mediaType;	// 0x36664ef9
// declared property getter: - (id)preferredImageManager;	// 0x366657d1
- (id)primaryCollection;	// 0x36664f15
// converted property setter: - (void)setArtID:(id)anId;	// 0x366655fd
// converted property setter: - (void)setCoverArtURL:(id)url;	// 0x3666531d
// converted property setter: - (void)setDateTaken:(id)taken;	// 0x36665435
// converted property setter: - (void)setFullURL:(id)url;	// 0x36664fe5
// converted property setter: - (void)setIsLocal:(BOOL)local;	// 0x36664a05
// converted property setter: - (void)setThumbURL:(id)url;	// 0x36665181
// converted property setter: - (void)setTitle:(id)title;	// 0x3666552d
- (id)subImageProxyWithRect:(CGRect)rect;	// 0x366657c1
// converted property getter: - (id)thumbURL;	// 0x366650b5
- (id)thumbnailArt;	// 0x36664d49
- (id)thumbnailArtID;	// 0x36664a79
// converted property getter: - (id)title;	// 0x36665461
@end

