/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, NSDictionary, BRImageControl, BRImage;

@interface BRPhotoBrowserBannerButton : BRControl {
@private
	BRControl *_focusControl;	// 48 = 0x30
	BRImageControl *_imageControl;	// 52 = 0x34
	BRImage *_focusedImage;	// 56 = 0x38
	BRImage *_unFocusedImage;	// 60 = 0x3c
	BRTextControl *_textControl;	// 64 = 0x40
	NSDictionary *_textAttributes;	// 68 = 0x44
}
@property(retain) BRImage *focusedImage;	// G=0x366fd439; S=0x366fd3e5; converted property
@property(retain) id text;	// G=0x366fd3ad; S=0x366fd329; converted property
@property(retain) BRImage *unFocusedImage;	// G=0x366fd49d; S=0x366fd449; converted property
+ (id)button;	// 0x366fce15
+ (id)removeSavedSearchButton;	// 0x366fcfdd
+ (id)saveSearchButton;	// 0x366fcf81
+ (id)settingsButton;	// 0x366fd039
+ (id)slideshowButton;	// 0x366fce4d
- (id)init;	// 0x366fd095
- (void)_updateContents;	// 0x366fd981
- (id)accessibilityLabel;	// 0x366fd945
- (id)accessibilityTraits;	// 0x366fd955
- (void)controlWasFocused;	// 0x366fd2a9
- (void)controlWasUnfocused;	// 0x366fd2e9
- (void)dealloc;	// 0x366fd1f9
// converted property getter: - (id)focusedImage;	// 0x366fd439
- (BOOL)isAccessibilityElement;	// 0x366fd941
- (void)layoutSubcontrols;	// 0x366fd655
// converted property setter: - (void)setFocusedImage:(id)image;	// 0x366fd3e5
// converted property setter: - (void)setText:(id)text;	// 0x366fd329
// converted property setter: - (void)setUnFocusedImage:(id)image;	// 0x366fd449
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x366fd4ad
// converted property getter: - (id)text;	// 0x366fd3ad
// converted property getter: - (id)unFocusedImage;	// 0x366fd49d
@end

