//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRDataStoreProvider.h"

@interface BRPhotoDataStoreProvider : BRDataStoreProvider
{
}

+ (id)providerWithDataStore:(id)arg1 controlFactory:(id)arg2;
- (void)_updateDataValidity:(id)arg1;
- (void)dealloc;
- (id)initWithDataStore:(id)arg1 controlFactory:(id)arg2;

@end

