//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

#import "BRProvider.h"

@class NSArray;

@interface BRPhotoProvider : NSObject <BRProvider>
{
    NSArray *_collections;
    id <BRControlFactory> _controlFactory;
}

+ (id)providerWithCollections:(id)arg1 controlFactory:(id)arg2;
- (id)controlFactory;
- (id)dataAtIndex:(long)arg1;
- (long)dataCount;
- (void)dealloc;
- (id)hashForDataAtIndex:(long)arg1;
- (id)initWithCollections:(id)arg1 controlFactory:(id)arg2;
- (void)setControlFactory:(id)arg1;

@end

