//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRPhotoProvider.h>

#import "BRPhotoProviderForCollection.h"

@class BRPhotoMediaCollection;

@interface BRPhotoProviderForCollection : BRPhotoProvider <BRPhotoProviderForCollection>
{
    BRPhotoMediaCollection *_collection;
    BOOL _vendPhotoDataOnly;
}

+ (id)providerForCollection:(id)arg1 controlFactory:(id)arg2;
- (id)_data;
- (BOOL)canHaveZeroData;
- (id)collection;
- (id)dataAtIndex:(long)arg1;
- (long)dataCount;
- (void)dealloc;
- (id)hashForDataAtIndex:(long)arg1;
- (id)initWithCollection:(id)arg1 controlFactory:(id)arg2;
- (void)setVendPhotoDataOnly:(BOOL)arg1;
- (BOOL)vendPhotoDataOnly;

@end

