/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRMediaMenuController.h"


__attribute__((visibility("hidden")))
@interface BRPlaylistItemsMenuConroller : BRMediaMenuController {
}
- (void)_handleContextMenuSelection:(id)selection;	// 0x36706145
- (id)providersForContextMenu;	// 0x36706045
@end

