/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "NSObject.h"


@protocol BRPlayerDelegate <NSObject>
@optional
- (void)menuActionForPlayer:(id)player;
- (BOOL)player:(id)player shouldHandleEvent:(id)event playerTime:(double)time;
- (double)player:(id)player willSeekToTime:(double)time;
- (void)playerEndedForPlayer:(id)player;
- (BOOL)retryPlaybackForPlayer:(id)player onError:(id)error;
@end

