/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControlHeightFactory.h"
#import <NSObject.h> // Unknown library
#import "BRControlFactory.h"

@class BRMediaType, NSSet;

__attribute__((visibility("hidden")))
@interface BRPlaylistsControlFactory : NSObject <BRControlFactory, BRControlHeightFactory> {
@private
	BOOL _showMetadata;	// 4 = 0x4
	BRMediaType *_missingType;	// 8 = 0x8
	NSSet *_mediaTypes;	// 12 = 0xc
	BOOL _useMultilineItems;	// 16 = 0x10
	BOOL _showIconForVideo;	// 17 = 0x11
	BOOL _resolveArtworkFromParent;	// 18 = 0x12
}
@property(readonly, retain) NSSet *mediaTypes;	// G=0x36705f11; converted property
@property(assign) BOOL shouldUseMultilineItems;	// G=0x36705f31; S=0x36705f21; converted property
@property(assign) BOOL showIconForVideo;	// G=0x36705f51; S=0x36705f41; converted property
+ (id)factoryWithMissingType:(id)missingType mediaTypes:(id)types showMetadata:(BOOL)metadata;	// 0x367056c1
+ (id)factoryWithMissingType:(id)missingType mediaTypes:(id)types showMetadata:(BOOL)metadata resolveArtworkFromParentCollections:(BOOL)parentCollections;	// 0x36705709
- (id)initWithMissingType:(id)missingType mediaTypes:(id)types showMetadata:(BOOL)metadata;	// 0x36705755
- (id)initWithMissingType:(id)missingType mediaTypes:(id)types showMetadata:(BOOL)metadata resolveArtworkFromParentCollections:(BOOL)parentCollections;	// 0x36705779
- (BOOL)_showUnplayedIconForAsset:(id)asset;	// 0x36705f61
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x36705879
- (void)dealloc;	// 0x36705819
- (float)heightForControlForData:(id)data requestedBy:(id)by;	// 0x36705df9
// converted property getter: - (id)mediaTypes;	// 0x36705f11
// converted property setter: - (void)setShouldUseMultilineItems:(BOOL)useMultilineItems;	// 0x36705f21
// converted property setter: - (void)setShowIconForVideo:(BOOL)video;	// 0x36705f41
// converted property getter: - (BOOL)shouldUseMultilineItems;	// 0x36705f31
// converted property getter: - (BOOL)showIconForVideo;	// 0x36705f51
@end

