//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

#import "BRControlFactory.h"
#import "BRControlHeightFactory.h"

@class BRImage;

@interface BRPosterControlFactory : NSObject <BRControlFactory, BRControlHeightFactory>
{
    BRImage *_defaultImage;
}

+ (id)factory;
- (id)_posterForGridFromAsset:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (id)_posterForShelfFromAsset:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (id)_posterFromAsset:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (id)controlForData:(id)arg1 currentControl:(id)arg2 requestedBy:(id)arg3;
- (void)dealloc;
- (float)heightForControlForData:(id)arg1 requestedBy:(id)arg2;
- (id)init;
- (void)setDefaultImage:(id)arg1;

@end

