/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRKeyboard.h"

@class BRPopupKeyboardControl;

__attribute__((visibility("hidden")))
@interface BRPopupKeyboardWithDeleteButton : BRKeyboard {
@private
	BRPopupKeyboardControl *_popupKeyboardControl;	// 48 = 0x30
}
- (id)_filterRawKeyboardData:(id)data;	// 0x366d1fbd
- (id)_keyboardDataFileName;	// 0x366d2595
- (int)_numberOfActionKeyColumns;	// 0x366d25ed
- (int)_numberOfActionKeyRows;	// 0x366d25e9
- (int)_numberOfMainKeyColumns;	// 0x366d25c1
- (int)_numberOfMainKeyRows;	// 0x366d25bd
- (void)dealloc;	// 0x366d1ccd
- (id)keyboardControl;	// 0x366d1d19
- (BOOL)popupKeyboardShouldRemainDisplayedAfterCharacterSelection;	// 0x366d1f69
@end

