/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSLock, NSTimer, NSMutableSet;

__attribute__((visibility("hidden")))
@interface BRPreferenceManager : NSObject {
@private
	NSLock *_preferencesLock;	// 4 = 0x4
	NSTimer *_prefsSyncTimer;	// 8 = 0x8
	NSMutableSet *_domains;	// 12 = 0xc
}
+ (id)sharedPreferences;	// 0x3676f5a9
- (id)init;	// 0x3676f5f1
- (void)_applicationTerminating:(id)terminating;	// 0x36770231
- (void)_backgroundTasksSuspending:(id)suspending;	// 0x367702e5
- (void)_diskWillBeFlushed:(id)_disk;	// 0x36770399
- (void)_flushPreferences:(id)preferences;	// 0x367700f9
- (void)_markPreferencesAsDirty;	// 0x3676ff4d
- (void)_setValue:(id)value forKey:(id)key forDomain:(id)domain;	// 0x3676fd05
- (void)_synchronizeDomains;	// 0x36770465
- (id)_valueForKey:(id)key forDomain:(id)domain;	// 0x3676fe45
- (BOOL)boolForKey:(id)key forDomain:(id)domain withValueForMissingPrefs:(BOOL)missingPrefs;	// 0x3676f9a1
- (BOOL)canSetPreferencesForKey:(id)key forDomain:(id)domain;	// 0x3676fa49
- (void)dealloc;	// 0x3676f735
- (id)descriptionForKey:(id)key forDomain:(id)domain;	// 0x3676fa21
- (double)doubleForKey:(id)key forDomain:(id)domain withValueForMissingPrefs:(double)missingPrefs;	// 0x3676f905
- (float)floatForKey:(id)key forDomain:(id)domain withValueForMissingPrefs:(float)missingPrefs;	// 0x3676f869
- (int)integerForKey:(id)key forDomain:(id)domain withValueForMissingPrefs:(int)missingPrefs;	// 0x3676f7d5
- (id)objectForKey:(id)key forDomain:(id)domain;	// 0x3676f7c5
- (BOOL)setBool:(BOOL)aBool forKey:(id)key forDomain:(id)domain;	// 0x3676fbd5
- (BOOL)setDouble:(double)aDouble forKey:(id)key forDomain:(id)domain;	// 0x3676fb55
- (BOOL)setFloat:(float)aFloat forKey:(id)key forDomain:(id)domain;	// 0x3676fad9
- (BOOL)setInteger:(int)integer forKey:(id)key forDomain:(id)domain;	// 0x3676fa61
- (BOOL)setObject:(id)object forKey:(id)key forDomain:(id)domain;	// 0x3676fc4d
- (id)stringForKey:(id)key forDomain:(id)domain;	// 0x3676f9c5
- (void)syncDomain:(id)domain;	// 0x3676fca5
@end

