/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSString;

@interface BRPreferences : NSObject {
@private
	NSString *_domain;	// 4 = 0x4
}
@property(readonly, retain) NSString *domain;	// G=0x367705a1; converted property
+ (id)sharedFrontRowPreferences;	// 0x36770bdd
- (id)initWithDomain:(id)domain;	// 0x367704fd
- (BOOL)boolForKey:(id)key;	// 0x36770825
- (BOOL)boolForKey:(id)key withValueForMissingPrefs:(BOOL)missingPrefs;	// 0x36770875
- (BOOL)canSetPreferencesForKey:(id)key;	// 0x36770955
- (void)dealloc;	// 0x36770555
- (id)descriptionForKey:(id)key;	// 0x3677090d
// converted property getter: - (id)domain;	// 0x367705a1
- (double)doubleForKey:(id)key;	// 0x3677077d
- (double)doubleForKey:(id)key withValueForMissingPrefs:(double)missingPrefs;	// 0x367707cd
- (float)floatForKey:(id)key;	// 0x367706dd
- (float)floatForKey:(id)key withValueForMissingPrefs:(float)missingPrefs;	// 0x3677072d
- (int)integerForKey:(id)key;	// 0x3677063d
- (int)integerForKey:(id)key withValueForMissingPrefs:(int)missingPrefs;	// 0x3677068d
- (BOOL)isLoggingEnabledForKey:(id)key;	// 0x36770b31
- (id)logFilePathsForKey:(id)key;	// 0x36770b61
- (id)objectForKey:(id)key;	// 0x367705f5
- (BOOL)setBool:(BOOL)aBool forKey:(id)key;	// 0x36770a91
- (BOOL)setDouble:(double)aDouble forKey:(id)key;	// 0x36770a3d
- (BOOL)setFloat:(float)aFloat forKey:(id)key;	// 0x367709ed
- (BOOL)setInteger:(int)integer forKey:(id)key;	// 0x3677099d
- (BOOL)setObject:(id)object forKey:(id)key;	// 0x36770ae1
- (id)stringForKey:(id)key;	// 0x367708c5
- (void)syncNow;	// 0x367705b1
@end

