/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSingleton.h"
#import "MCProfileConnectionObserver.h"


@interface BRProfileManager : BRSingleton <MCProfileConnectionObserver> {
@private
	unsigned _installedProfileCount;	// 4 = 0x4
}
@property(assign, nonatomic) unsigned installedProfileCount;	// G=0x36770cc1; S=0x36770d25; @synthesize=_installedProfileCount
+ (void)setSingleton:(id)singleton;	// 0x36770c41
+ (id)singleton;	// 0x36770c31
// declared property getter: - (unsigned)installedProfileCount;	// 0x36770cc1
- (void)profileConnectionDidReceiveProfileListChangedNotification:(id)profileConnection userInfo:(id)info;	// 0x36770cd1
// declared property setter: - (void)setInstalledProfileCount:(unsigned)count;	// 0x36770d25
- (void)startWatchingForConfigurationChanges;	// 0x36770c51
@end

