//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRSingleton.h"

#import "MCProfileConnectionObserver.h"

@interface BRProfileManager : BRSingleton <MCProfileConnectionObserver>
{
    unsigned int _installedProfileCount;
}

+ (void)setSingleton:(id)arg1;
+ (id)singleton;
@property(nonatomic) unsigned int installedProfileCount; // @synthesize installedProfileCount=_installedProfileCount;
- (void)profileConnectionDidReceiveProfileListChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)startWatchingForConfigurationChanges;

@end

