//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableSet, NSTimer;

__attribute__((visibility("hidden")))
@interface BRPreferenceManager : NSObject
{
    NSLock *_preferencesLock;
    NSTimer *_prefsSyncTimer;
    NSMutableSet *_domains;
}

+ (id)sharedPreferences;
- (void)_applicationTerminating:(id)arg1;
- (void)_backgroundTasksSuspending:(id)arg1;
- (void)_diskWillBeFlushed:(id)arg1;
- (void)_flushPreferences:(id)arg1;
- (void)_markPreferencesAsDirty;
- (void)_setValue:(id)arg1 forKey:(id)arg2 forDomain:(id)arg3;
- (void)_synchronizeDomains;
- (id)_valueForKey:(id)arg1 forDomain:(id)arg2;
- (BOOL)boolForKey:(id)arg1 forDomain:(id)arg2 withValueForMissingPrefs:(BOOL)arg3;
- (BOOL)canSetPreferencesForKey:(id)arg1 forDomain:(id)arg2;
- (void)dealloc;
- (id)descriptionForKey:(id)arg1 forDomain:(id)arg2;
- (double)doubleForKey:(id)arg1 forDomain:(id)arg2 withValueForMissingPrefs:(double)arg3;
- (float)floatForKey:(id)arg1 forDomain:(id)arg2 withValueForMissingPrefs:(float)arg3;
- (id)init;
- (int)integerForKey:(id)arg1 forDomain:(id)arg2 withValueForMissingPrefs:(int)arg3;
- (id)objectForKey:(id)arg1 forDomain:(id)arg2;
- (BOOL)setBool:(BOOL)arg1 forKey:(id)arg2 forDomain:(id)arg3;
- (BOOL)setDouble:(double)arg1 forKey:(id)arg2 forDomain:(id)arg3;
- (BOOL)setFloat:(float)arg1 forKey:(id)arg2 forDomain:(id)arg3;
- (BOOL)setInteger:(int)arg1 forKey:(id)arg2 forDomain:(id)arg3;
- (BOOL)setObject:(id)arg1 forKey:(id)arg2 forDomain:(id)arg3;
- (id)stringForKey:(id)arg1 forDomain:(id)arg2;
- (void)syncDomain:(id)arg1;

@end

