/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRType.h"


@interface BRResolution : BRType {
}
+ (id)ED480p;	// 0x3666b5a5
+ (id)ED576p;	// 0x3666b5f5
+ (id)HD1080i;	// 0x3666b695
+ (id)HD720p;	// 0x3666b645
+ (id)SD480i;	// 0x3666b505
+ (id)SD576i;	// 0x3666b555
+ (int)compareResolution:(id)resolution toResolution:(id)resolution2;	// 0x3666b6e5
+ (void)initialize;	// 0x3666b46d
@end

