//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

@interface BRReflectionControl : BRControl
{
    float _reflectionAmount;
    float _reflectionOffset;
    BOOL _flipped;
}

- (id)_generateFiltersFrom:(float)arg1 to:(float)arg2;
- (id)_reflectionFilters;
- (id)_unflippedReflectionFilters;
- (BOOL)flipped;
- (id)init;
- (float)reflectionAmount;
- (float)reflectionOffset;
- (void)setFlipped:(BOOL)arg1;
- (void)setImage:(id)arg1;
- (void)setReflectionAmount:(float)arg1;
- (void)setReflectionOffset:(float)arg1;

@end

