//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class NSAttributedString;

__attribute__((visibility("hidden")))
@interface BRScrollingTextPlane : BRControl
{
    NSAttributedString *_string;
    float _pursuitGap;
    struct CGSize _cachedNaturalTextSize;
}

+ (Class)layerClass;
- (id)attributedString;
- (void)dealloc;
- (void)drawInContext:(struct CGContext *)arg1;
- (struct CGSize)naturalTextSize;
- (void)setAttributedString:(id)arg1;
- (void)setPursuitGap:(float)arg1;
- (void)setTileSize:(struct CGSize)arg1;

@end

