/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library

@class BRSeriesProvider, NSMutableArray, NSSet;
@protocol BRControlFactory;

@interface BRSeriesMostRecentNoStoreProvider : NSObject <BRProvider> {
@private
	NSSet *_mediaTypes;	// 4 = 0x4
	BRSeriesProvider *_seriesProvider;	// 8 = 0x8
	id<BRControlFactory> _controlFactory;	// 12 = 0xc
	BRSeriesProvider *_unwatchedProvider;	// 16 = 0x10
	NSMutableArray *_data;	// 20 = 0x14
	BOOL _storeAvailable;	// 24 = 0x18
	BOOL _needsUpdate;	// 25 = 0x19
	BOOL _initialized;	// 26 = 0x1a
}
+ (id)providerForMediaTypes:(id)mediaTypes controlFactory:(id)factory filteringOutProvider:(id)provider;	// 0x3671843d
- (void)_checkStore;	// 0x367187b5
- (id)_data;	// 0x36718afd
- (id)_filteredDataFrom:(id)from;	// 0x36718d41
- (id)_filteredSeriesNames;	// 0x36718c45
- (id)_initForMediaTypes:(id)mediaTypes controlFactory:(id)factory filteringOutProvider:(id)provider;	// 0x3671864d
- (void)_reloadData;	// 0x36718b55
- (void)_setStoreAvailable:(BOOL)available;	// 0x367188ad
- (BOOL)_storeAvailable;	// 0x36718aed
- (id)controlFactory;	// 0x36718561
- (id)dataAtIndex:(long)index;	// 0x36718599
- (long)dataCount;	// 0x36718571
- (void)dealloc;	// 0x36718495
- (id)hashForDataAtIndex:(long)index;	// 0x367185c5
@end

