//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



#import "BRProvider-Protocol.h"

@class BRSeriesProvider, NSMutableArray, NSSet;

@interface BRSeriesMostRecentNoStoreProvider : NSObject <BRProvider>
{
    NSSet *_mediaTypes;
    BRSeriesProvider *_seriesProvider;
    id <BRControlFactory> _controlFactory;
    BRSeriesProvider *_unwatchedProvider;
    NSMutableArray *_data;
    BOOL _storeAvailable;
    BOOL _needsUpdate;
    BOOL _initialized;
}

+ (id)providerForMediaTypes:(id)arg1 controlFactory:(id)arg2 filteringOutProvider:(id)arg3;
- (void)_checkStore;
- (id)_data;
- (id)_filteredDataFrom:(id)arg1;
- (id)_filteredSeriesNames;
- (id)_initForMediaTypes:(id)arg1 controlFactory:(id)arg2 filteringOutProvider:(id)arg3;
- (void)_reloadData;
- (void)_setStoreAvailable:(BOOL)arg1;
- (BOOL)_storeAvailable;
- (id)controlFactory;
- (id)dataAtIndex:(long)arg1;
- (long)dataCount;
- (void)dealloc;
- (id)hashForDataAtIndex:(long)arg1;

@end

