//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRImageControl;

__attribute__((visibility("hidden")))
@interface BRShimmerControl : BRControl
{
    BRControl *_base;
    BRImageControl *_shimmer;
    float _offset;
}

+ (id)shimmerWithOffset:(float)arg1;
- (id)_calculateKeyTimes;
- (id)_calculatePositionValues;
- (void)dealloc;
- (id)init;
- (id)initWithOffset:(float)arg1;
- (void)layoutSubcontrols;
- (float)offset;
- (void)setOffset:(float)arg1;

@end

