//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



@class NSString;

@interface BRSimpleMenuItem : NSObject
{
    NSString *_title;
    NSString *_rightJustifiedText;
    int _titlePosition;
    int _menuItemType;
}

+ (id)simpleMenuItemWithTitle:(id)arg1 rightJustifiedText:(id)arg2 titlePosition:(int)arg3 menuItemType:(int)arg4;
+ (id)simpleMenuItemWithTitle:(id)arg1 titlePosition:(int)arg2 menuItemType:(int)arg3;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 rightJustifiedText:(id)arg2 titlePosition:(int)arg3 menuItemType:(int)arg4;
- (id)initWithTitle:(id)arg1 titlePosition:(int)arg2 menuItemType:(int)arg3;
- (int)menuItemType;
- (id)rightJustifiedText;
- (id)title;
- (int)titlePosition;

@end

