/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "AppleTV-Structs.h"


@interface BRSingleton : NSObject {
}
+ (id)allocWithZone:(NSZone *)zone;	// 0x36770e39
+ (id)sharedInstance;	// 0x36770d35
- (id)autorelease;	// 0x36770f15
- (id)copyWithZone:(NSZone *)zone;	// 0x36770f09
- (oneway void)release;	// 0x36770f11
- (id)retain;	// 0x36770f0d
- (unsigned)retainCount;	// 0x36770f19
@end

