//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

@interface BRSingleton : NSObject
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (id)autorelease;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (oneway void)release;
- (id)retain;
- (unsigned int)retainCount;

@end

