/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRViewController.h"

@class NSMutableArray, NSTimer, NSArray, BRMarimbaMenuView;

@interface BRSlideshowSettingsController : BRViewController {
@private
	BRMarimbaMenuView *_marimbaMenuView;	// 88 = 0x58
	NSMutableArray *_menuHistory;	// 92 = 0x5c
	NSArray *_musicServers;	// 96 = 0x60
	NSArray *_musicPlaylists;	// 100 = 0x64
	ATVDataServerRef _defaultMusicServer;	// 104 = 0x68
	ATVMediaQueryRef _playlistsQuery;	// 108 = 0x6c
	NSTimer *_randomThemeSwappingTimer;	// 112 = 0x70
	int _currentMenuType;	// 116 = 0x74
	BOOL _ignoreFocusMessages;	// 120 = 0x78
	BOOL _playlistQueryInProgress;	// 121 = 0x79
	BOOL _updateDefaultMusicMenuAfterPlaylistQueryCompletes;	// 122 = 0x7a
	BOOL _memoryWarningAlreadyReceived;	// 123 = 0x7b
}
+ (id)randomTransitionIDs;	// 0x36701bcd
+ (id)randomlySelectedSlideshowThemeIdentifier;	// 0x36701a25
+ (id)slideshowIdentifierForTitle:(id)title;	// 0x36701949
+ (id)slideshowThemeTitles;	// 0x3670185d
+ (id)slideshowTransitionTitles;	// 0x36701ab9
+ (id)timePerSlideValues;	// 0x36701da1
+ (id)transitionIdentifierForTitle:(id)title;	// 0x36701b59
- (id)init;	// 0x36701e5d
- (id)initWithMediaCollection:(id)mediaCollection;	// 0x36701e71
- (id)_allSharedComputers;	// 0x367049b5
- (id)_currentPlaylistName;	// 0x36703405
- (ATVDataClientRef)_dataClient;	// 0x36705365
- (void)_dataClientStatusChanged:(id)changed;	// 0x3670501d
- (int)_indexOfStringItem:(id)stringItem inArray:(id *)array itemCount:(int)count;	// 0x367024f9
- (void)_initiatePlaylistsQuery;	// 0x36704e85
- (BOOL)_isCloudEnabled;	// 0x3670490d
- (void)_lowMemoryNotification:(id)notification;	// 0x36702f49
- (void)_mainSettingsMenuList:(id)list didFocusItemAtIndexPath:(id)indexPath;	// 0x367035dd
- (void)_mainSettingsMenuList:(id)list didSelectItemAtIndexPath:(id)indexPath;	// 0x36703779
- (id)_mainSettingsMenuList:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x36702fc5
- (long)_mainSettingsMenuList:(id)list numberOfRowsInSection:(long)section;	// 0x36703541
- (id)_mainSettingsMenuList:(id)list sectionHeaderForSection:(long)section;	// 0x3670358d
- (long)_mainSettingsMenuNumberOfSectionsInList:(id)list;	// 0x3670353d
- (void)_musicLibraryMenuList:(id)list didFocusItemAtIndexPath:(id)indexPath;	// 0x367044f5
- (void)_musicLibraryMenuList:(id)list didSelectItemAtIndexPath:(id)indexPath;	// 0x367044f9
- (id)_musicLibraryMenuList:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x36704261
- (long)_musicLibraryMenuList:(id)list numberOfRowsInSection:(long)section;	// 0x3670444d
- (id)_musicLibraryMenuList:(id)list sectionHeaderForSection:(long)section;	// 0x367044a5
- (long)_musicLibraryMenuNumberOfSectionsInList:(id)list;	// 0x36704449
- (id)_musicServerSettingForIndexPath:(id)indexPath musicServer:(ATVDataServerRef *)server;	// 0x3670471d
- (void)_playlistMenuList:(id)list didFocusItemAtIndexPath:(id)indexPath;	// 0x36704c91
- (void)_playlistMenuList:(id)list didSelectItemAtIndexPath:(id)indexPath;	// 0x36704c95
- (id)_playlistMenuList:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x36704a15
- (long)_playlistMenuList:(id)list numberOfRowsInSection:(long)section;	// 0x36704c0d
- (id)_playlistMenuList:(id)list sectionHeaderForSection:(long)section;	// 0x36704c41
- (long)_playlistMenuNumberOfSectionsInList:(id)list;	// 0x36704bcd
- (void)_playlistsQueryComplete;	// 0x367053c9
- (void)_returnToPreviousMenu;	// 0x36702821
- (void)_runPlaylistsQuery;	// 0x36705149
- (void)_setDefaultMusicServerSetting:(id)setting defaultMusicServer:(ATVDataServerRef)server;	// 0x367048a1
- (void)_setPlaylistsQuery:(ATVMediaQueryRef)query;	// 0x36705331
- (void)_swapSlideshowTheme:(id)theme;	// 0x3670372d
- (void)_switchToMenuType:(int)menuType rememberCurrentMenu:(BOOL)menu;	// 0x3670253d
- (void)_themeDetailsMenuList:(id)list didFocusItemAtIndexPath:(id)indexPath;	// 0x36703d95
- (void)_themeDetailsMenuList:(id)list didSelectItemAtIndexPath:(id)indexPath;	// 0x36703e1d
- (id)_themeDetailsMenuList:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x36703b9d
- (long)_themeDetailsMenuList:(id)list numberOfRowsInSection:(long)section;	// 0x36703d39
- (id)_themeDetailsMenuList:(id)list sectionHeaderForSection:(long)section;	// 0x36703d45
- (long)_themeDetailsMenuNumberOfSectionsInList:(id)list;	// 0x36703d35
- (void)_toggleTimePerSlide;	// 0x36703fe9
- (void)_updateListFocusOnMenuSwitch;	// 0x36702af1
- (BOOL)brEventAction:(id)action;	// 0x36702181
- (void)dealloc;	// 0x36702085
- (void)list:(id)list didFocusItemAtIndexPath:(id)indexPath;	// 0x36702441
- (void)list:(id)list didSelectItemAtIndexPath:(id)indexPath;	// 0x3670249d
- (float)list:(id)list heightForItemAtIndexPath:(id)indexPath;	// 0x36702435
- (float)list:(id)list heightForSectionHeader:(long)sectionHeader;	// 0x367023ed
- (id)list:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x36702271
- (long)list:(id)list numberOfRowsInSection:(long)section;	// 0x3670232d
- (id)list:(id)list sectionHeaderForSection:(long)section;	// 0x3670238d
- (long)numberOfSectionsInList:(id)list;	// 0x367022d1
@end

