/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSAttributedString;

@interface BRStrokeAndFillTextControl : BRControl {
@private
	NSAttributedString *_attributedString;	// 48 = 0x30
	float _strokeWidth;	// 52 = 0x34
	CGColorRef _strokeColor;	// 56 = 0x38
}
@property(copy) NSAttributedString *attributedString;	// G=0x366c461d; S=0x366c462d; @synthesize=_attributedString
@property(retain) CGColorRef strokeColor;	// G=0x366c4955; S=0x366c4969; @synthesize=_strokeColor
@property(assign) float strokeWidth;	// G=0x366c4935; S=0x366c4945; @synthesize=_strokeWidth
// declared property getter: - (id)attributedString;	// 0x366c461d
- (void)dealloc;	// 0x366c45bd
- (void)drawInContext:(CGContextRef)context;	// 0x366c4685
// declared property setter: - (void)setAttributedString:(id)string;	// 0x366c462d
// declared property setter: - (void)setStrokeColor:(CGColorRef)color;	// 0x366c4969
// declared property setter: - (void)setStrokeWidth:(float)width;	// 0x366c4945
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x366c44ad
// declared property getter: - (CGColorRef)strokeColor;	// 0x366c4955
// declared property getter: - (float)strokeWidth;	// 0x366c4935
@end

