//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSRunLoop, NSString, NSTimer;

@interface BRStateMachine : NSObject
{
    NSRunLoop *_runloop;
    NSTimer *_timer;
    NSMutableArray *_events;
    NSMutableDictionary *_handlers;
    NSMutableDictionary *_defaultHandlers;
    BOOL shouldProcessEvents;
    NSString *_currentState;
    NSString *_name;
    BOOL _immediate;
    BOOL _ignoreRecursiveEvents;
}

+ (void)deregisterStateMachine:(id)arg1;
+ (void)initialize;
+ (void)registerStateMachine:(id)arg1;
+ (id)stateMachineWithName:(id)arg1;
- (CDUnknownBlockType)_eventHandlerForEvent:(id)arg1;
- (void)_processNextEvent;
@property(readonly) NSString *currentState; // @synthesize currentState=_currentState;
- (void)dealloc;
- (void)deregisterHandlers;
@property(nonatomic) BOOL ignoreRecursiveEvents; // @synthesize ignoreRecursiveEvents=_ignoreRecursiveEvents;
@property(readonly) BOOL immediate; // @synthesize immediate=_immediate;
- (id)initWithName:(id)arg1 initialState:(id)arg2 immediateMode:(BOOL)arg3;
- (void)logUnhandledEvents;
@property(readonly) NSString *name; // @synthesize name=_name;
- (void)postEvent:(id)arg1 withContext:(id)arg2;
- (void)postEvent:(id)arg1 withContext:(id)arg2 userInfo:(id)arg3;
- (void)purgeEventQueue;
- (void)registerDefaultHandlerForEvent:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)registerHandlerForEvent:(id)arg1 onState:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
@property(nonatomic) BOOL shouldProcessEvents; // @synthesize shouldProcessEvents;

@end

