//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRBaseMediaAsset.h>

#import "BRATVMediaItem.h"
#import "BRMediaAssetDerivesMediaURL.h"
#import "BRSecureResource.h"

@class NSMutableDictionary, NSString;

@interface BRStreamingMediaAsset : BRBaseMediaAsset <BRATVMediaItem, BRMediaAssetDerivesMediaURL, BRSecureResource>
{
    struct __ATVMediaItem *_mediaItem;
    NSMutableDictionary *_metadata;
    NSString *_assetID;
}

+ (void)setImplementationClass:(Class)arg1;
+ (id)streamingMediaAssetWithMediaItem:(struct __ATVMediaItem *)arg1;
- (BOOL)_supportsBookmarkProperty;
- (BOOL)alwaysRequiresAuthorization;
- (id)artist;
- (id)assetID;
- (unsigned int)bookmarkTimeInMS;
- (void)dealloc;
- (long)duration;
- (BOOL)hasVideoContent;
- (id)imageProxy;
- (void)incrementPerformanceCount;
- (void)incrementPerformanceOrSkipCount:(unsigned int)arg1;
- (id)initWithMediaItem:(struct __ATVMediaItem *)arg1;
- (BOOL)isHD;
- (id)mediaDescription;
- (id)mediaFlavor;
- (struct __ATVMediaItem *)mediaItemRef;
- (id)mediaSummary;
- (id)mediaType;
- (id)mediaURL;
- (id)playbackMetadata;
- (id)primaryCollectionTitle;
- (id)primaryGenre;
- (void)requiredScope:(unsigned int *)arg1 accountType:(id *)arg2;
- (void)resolveMediaURL:(CDUnknownBlockType)arg1;
- (void)setBookmarkTimeInMS:(unsigned int)arg1;
- (void)setPlaybackMetadataValue:(id)arg1 forKey:(id)arg2;
- (void)setWatched:(BOOL)arg1;
- (unsigned int)startTimeInMS;
- (id)title;

@end

