/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRCursorLayer.h"


__attribute__((visibility("hidden")))
@interface BRStandardCursorLayer : BRCursorLayer {
}
- (id)init;	// 0x36685d4d
- (void)applyMapForCornerRadius:(float)cornerRadius;	// 0x36685db5
@end

