//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRPhotoMediaAsset.h"

#import "BRATVMediaItem-Protocol.h"

@class BRImageManager;

@interface BRStreamingPhotoAsset : BRPhotoMediaAsset <BRATVMediaItem>
{
    BRImageManager *_preferredImageManager;
    struct __ATVDataClient *_dataClient;
    struct __ATVMediaItem *_mediaItem;
    struct __ATVMediaCollection *_mediaCollection;
    BOOL _useForScreenSaver;
}

+ (id)assetWithATVMediaItem:(struct __ATVMediaItem *)arg1 dataClient:(struct __ATVDataClient *)arg2;
- (struct CGRect)_paddedFaceRectFromFaceRect:(struct CGRect)arg1;
- (id)artID;
@property(retain, nonatomic) __attribute__((NSObject)) struct __ATVDataClient *dataClient; // @synthesize dataClient=_dataClient;
- (id)dateTaken;
- (void)dealloc;
- (struct CGRect)faceRectForFaceCollectionID:(id)arg1;
- (id)faces;
- (BOOL)hasVideoContent;
- (id)imageProxy;
- (id)initWithATVMediaCollection:(struct __ATVMediaCollection *)arg1 dataClient:(struct __ATVDataClient *)arg2;
- (id)initWithATVMediaItem:(struct __ATVMediaItem *)arg1 dataClient:(struct __ATVDataClient *)arg2;
- (BOOL)isLocal;
@property(retain, nonatomic) __attribute__((NSObject)) struct __ATVMediaCollection *mediaCollection; // @synthesize mediaCollection=_mediaCollection;
@property(retain, nonatomic) __attribute__((NSObject)) struct __ATVMediaItem *mediaItem; // @synthesize mediaItem=_mediaItem;
- (struct __ATVMediaItem *)mediaItemRef;
- (id)mediaType;
- (id)mediaURL;
- (id)preferredImageManager;
@property(nonatomic) BOOL useForScreenSaver; // @synthesize useForScreenSaver=_useForScreenSaver;
- (id)subImageProxyWithRect:(struct CGRect)arg1;

@end

