//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



#import "BRProvider-Protocol.h"

@interface BRSubsetProvider : NSObject <BRProvider>
{
    id _provider;
    int _dataLimit;
}

+ (id)providerWithProvider:(id)arg1;
+ (id)providerWithProvider:(id)arg1 dataLimit:(int)arg2;
- (void)_providerUpdated:(id)arg1;
- (id)controlFactory;
- (id)dataAtIndex:(long)arg1;
- (long)dataCount;
- (int)dataLimit;
- (void)dealloc;
- (id)hashForDataAtIndex:(long)arg1;
- (id)initWithProvider:(id)arg1 dataLimit:(int)arg2;
- (void)setDataLimit:(int)arg1;

@end

