/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRProvider.h"


@interface BRSubsetProvider : NSObject <BRProvider> {
@private
	id _provider;	// 4 = 0x4
	int _dataLimit;	// 8 = 0x8
}
@property(assign) int dataLimit;	// G=0x367196dd; S=0x367196b5; converted property
+ (id)providerWithProvider:(id)provider;	// 0x36719355
+ (id)providerWithProvider:(id)provider dataLimit:(int)limit;	// 0x36719369
- (id)initWithProvider:(id)provider dataLimit:(int)limit;	// 0x367191c9
- (void)_providerUpdated:(id)updated;	// 0x367196ed
- (id)controlFactory;	// 0x367193b9
- (id)dataAtIndex:(long)index;	// 0x367194ad
- (long)dataCount;	// 0x367193d9
// converted property getter: - (int)dataLimit;	// 0x367196dd
- (void)dealloc;	// 0x367192d9
- (id)hashForDataAtIndex:(long)index;	// 0x367195b1
// converted property setter: - (void)setDataLimit:(int)limit;	// 0x367196b5
@end

