//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRRemoteMediaHost.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface BRSyncingMediaHost : BRRemoteMediaHost
{
    NSString *_hostID;
}

+ (id)syncingMediaHostWithHostInfo:(id)arg1;
- (void)dealloc;
- (id)hostID;
- (id)hostname;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithHostInfo:(id)arg1;
- (void)setState:(id)arg1;

@end

