//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRProgressBarWidget, BRTextControl, NSString;

@interface BRSyncProgressControl : BRControl
{
    BRProgressBarWidget *_progressBar;
    BRTextControl *_sourceText;
    BRTextControl *_currentAssetText;
    NSString *_currentAssetTextFormat;
    unsigned int _numAssets;
}

- (void)_updateProgress:(id)arg1;
- (void)dealloc;
- (id)initWithSourceName:(id)arg1 notification:(id)arg2;
- (void)layoutSubcontrols;
- (void)setCurrentAssetName:(id)arg1 num:(unsigned int)arg2;
- (void)setPercentage:(float)arg1;

@end

