//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRPanelControl.h>

@class NSArray, NSDictionary;

@interface BRTabControl : BRPanelControl
{
    int _selectedTabIndex;
    float _scaledTextPadding;
    float _scaledPreferredHeight;
    int _tabBeingDeselected;
    id _tabControlDelegate;
    NSArray *_greyImages;
    NSArray *_blackImages;
    NSArray *_blueImages;
    NSDictionary *_tabItemLabelAttributes;
}

+ (id)fullSizeTabControl;
+ (id)menuTabControl;
- (id)_centerTabImagesFromImages:(id)arg1;
- (void)_focusChanged:(id)arg1;
- (id)_imagesForTabItem:(id)arg1;
- (id)_leftTabImagesFromImages:(id)arg1;
- (void)_loadTabImages;
- (id)_rightTabImagesFromImages:(id)arg1;
- (void)_updateFocusNotifications;
- (void)_updateTabItemNames:(int)arg1;
- (id)accessibilityControls;
- (void)addTabItem:(id)arg1;
- (void)addTabItems:(id)arg1;
- (BOOL)brEventAction:(id)arg1;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (void)dealloc;
- (id)focusedControlForEvent:(id)arg1 focusPoint:(struct CGPoint *)arg2;
- (id)init;
- (void)insertTabItem:(id)arg1 atIndex:(int)arg2;
- (void)removeAllTabItems;
- (void)removeTabItem:(id)arg1;
- (void)selectNextTabItem;
- (void)selectPreviousTabItem;
- (void)selectTabItem:(id)arg1;
- (void)selectTabItemAtIndex:(int)arg1;
- (id)selectedTabItem;
- (int)selectedTabItemIndex;
- (void)setScaledPreferredHeight:(float)arg1;
- (void)setScaledTextPadding:(float)arg1;
- (void)setTabControlDelegate:(id)arg1;
- (void)setTabItemLabelAttributes:(id)arg1;
- (void)setTabItemNonSelectedImages:(id)arg1;
- (void)setTabItemSelectedInFocusImages:(id)arg1;
- (void)setTabItemSelectedNonFocusedImages:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)tabControlDelegate;
- (int)tabItemCount;
- (id)tabItems;

@end

