//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRMenuController.h"

@class BRCursorControl, BRImageControl, BRTextControl, BRTextControlWithWiderFocusFrame, BRTextEntryControl, BRTextFieldBackgroundLayer, BRTextFieldControl;

@interface BRTextEntryController : BRMenuController
{
    BRTextEntryControl *_editor;
    BRTextFieldControl *_textField;
    BRImageControl *_verticalDividerImage;
    BRTextFieldBackgroundLayer *_textFieldBackground;
    BRTextControl *_textFieldLabel;
    BRTextControlWithWiderFocusFrame *_submitButton;
    BRTextControl *_footnoteText;
    BRCursorControl *_cursor;
    BOOL _cursorNavigatedFromEditor;
    CDStruct_1420b1e7 _maxFootnoteTextHeight;
}

- (void)_addCursor;
- (void)_historyItemSelected:(id)arg1;
- (void)_removeCursor;
- (void)_submitButtonClick:(id)arg1;
- (void)_switchFocusToSubmitButton;
- (BOOL)accessibilityOutputsRangeForChildren;
- (id)accessibilityScreenContent;
- (BOOL)brEventAction:(id)arg1;
- (void)dealloc;
- (void)displayTextEntryHistoryForClients:(id)arg1 textEntryBehaviors:(id)arg2;
- (id)editor;
- (id)init;
- (id)initWithTextEntryStyle:(int)arg1;
- (BOOL)isValidAfterDataUpdate;
- (void)layoutSubcontrols;
@property(nonatomic) CDStruct_1420b1e7 maxFootnoteTextHeight; // @synthesize maxFootnoteTextHeight=_maxFootnoteTextHeight;
- (void)reset;
- (void)setDisplayTextEntryHistory:(BOOL)arg1;
- (void)setFocusToGlyphNamed:(id)arg1;
- (void)setFootnoteText:(id)arg1 withAttributes:(id)arg2;
- (void)setInitialTextEntryText:(id)arg1;
- (void)setSecondaryInfoText:(id)arg1 withAttributes:(id)arg2;
- (void)setShowUserEnteredText:(BOOL)arg1;
- (void)setSupplementaryText:(id)arg1;
- (void)setTextEntryHistoryClient:(id)arg1 textEntryBehavior:(id)arg2;
- (void)setTextEntryStyle:(int)arg1;
- (void)setTextEntryTextFieldLabel:(id)arg1;
- (void)setTextFieldDelegate:(id)arg1;

@end

