/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRTextField.h"
#import "AppleTV-Structs.h"
#import "BRControl.h"

@class NSTimer, NSMutableString, NSDictionary, BRMarqueeTextControl;

@interface BRTextFieldControl : BRControl <BRTextField> {
@private
	id _delegate;	// 48 = 0x30
	id _characterDelegate;	// 52 = 0x34
	BRMarqueeTextControl *_displayString;	// 56 = 0x38
	NSMutableString *_clearString;	// 60 = 0x3c
	NSDictionary *_savedAttributes;	// 64 = 0x40
	BOOL _useSecureText;	// 68 = 0x44
	BOOL _processingDeleteChar;	// 69 = 0x45
	BOOL _showCursor;	// 70 = 0x46
	BOOL _cursorVisible;	// 71 = 0x47
	int _textLengthLimit;	// 72 = 0x48
	NSTimer *_textObscureTimer;	// 76 = 0x4c
	NSTimer *_cursorBlinkTimer;	// 80 = 0x50
}
@property(assign) id characterDelegate;	// G=0x366d7e31; S=0x366d7e41; converted property
@property(assign) id delegate;	// G=0x366d7e11; S=0x366d7e21; converted property
@property(assign) BOOL showCursor;	// G=0x366d7e51; S=0x366d7e61; converted property
@property(retain) id textAttributes;	// G=0x366d7f5d; S=0x366d7f6d; converted property
@property(assign) int textLengthLimit;	// G=0x366d7f3d; S=0x366d7f4d; converted property
@property(assign) BOOL useSecureText;	// G=0x366d7eed; S=0x366d7efd; converted property
- (id)init;	// 0x366d7c0d
- (void)_blinkCursorTimerFired:(id)fired;	// 0x366d8bf1
- (id)_secureTextFromClearText;	// 0x366d895d
- (void)_secureTextObscureTimerFired:(id)fired;	// 0x366d8b59
- (void)_startSecureTextObscureTimer;	// 0x366d8a71
- (void)_stopBlinkCursorTimer;	// 0x366d8bbd
- (void)_stopSecureTextObscureTimer;	// 0x366d8b25
- (id)accessibilityTraits;	// 0x366d8271
- (id)accessibilityValue;	// 0x366d8251
- (BOOL)brKeyEvent:(id)event;	// 0x366d8339
// converted property getter: - (id)characterDelegate;	// 0x366d7e31
- (void)controlWasDeactivated;	// 0x366d7dd1
- (void)dealloc;	// 0x366d7d49
// converted property getter: - (id)delegate;	// 0x366d7e11
- (float)maxScrollPosition;	// 0x366d8211
- (BOOL)needsScrollingInBounds:(CGRect)bounds;	// 0x366d81d5
// converted property setter: - (void)setCharacterDelegate:(id)delegate;	// 0x366d7e41
- (void)setClearString:(id)string;	// 0x366d80a9
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x366d7e21
- (void)setDisplayString:(id)string;	// 0x366d7ff5
- (void)setScrollPosition:(float)position;	// 0x366d8231
// converted property setter: - (void)setShowCursor:(BOOL)cursor;	// 0x366d7e61
- (void)setString:(id)string;	// 0x366d82d5
// converted property setter: - (void)setTextAttributes:(id)attributes;	// 0x366d7f6d
// converted property setter: - (void)setTextLengthLimit:(int)limit;	// 0x366d7f4d
// converted property setter: - (void)setUseSecureText:(BOOL)text;	// 0x366d7efd
// converted property getter: - (BOOL)showCursor;	// 0x366d7e51
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x366d8105
- (id)stringValue;	// 0x366d829d
// converted property getter: - (id)textAttributes;	// 0x366d7f5d
// converted property getter: - (int)textLengthLimit;	// 0x366d7f3d
// converted property getter: - (BOOL)useSecureText;	// 0x366d7eed
@end

