/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRMenuController.h"

@class BRTextFieldControl, BRCursorControl, BRTextControlWithWiderFocusFrame, BRTextEntryControl, BRTextFieldBackgroundLayer, BRTextControl, BRImageControl;

@interface BRTextEntryController : BRMenuController {
@private
	BRTextEntryControl *_editor;	// 128 = 0x80
	BRTextFieldControl *_textField;	// 132 = 0x84
	BRImageControl *_verticalDividerImage;	// 136 = 0x88
	BRTextFieldBackgroundLayer *_textFieldBackground;	// 140 = 0x8c
	BRTextControl *_textFieldLabel;	// 144 = 0x90
	BRTextControlWithWiderFocusFrame *_submitButton;	// 148 = 0x94
	BRTextControl *_footnoteText;	// 152 = 0x98
	BRCursorControl *_cursor;	// 156 = 0x9c
	BOOL _cursorNavigatedFromEditor;	// 160 = 0xa0
	XXStruct_qlg9jA _maxFootnoteTextHeight;	// 164 = 0xa4
}
@property(readonly, retain) BRTextEntryControl *editor;	// G=0x366f8a15; converted property
@property(assign, nonatomic) XXStruct_qlg9jA maxFootnoteTextHeight;	// G=0x366f9969; S=0x366f9985; @synthesize=_maxFootnoteTextHeight
- (id)init;	// 0x366f839d
- (id)initWithTextEntryStyle:(int)textEntryStyle;	// 0x366f83b1
- (void)_addCursor;	// 0x366f9a35
- (void)_historyItemSelected:(id)selected;	// 0x366f9995
- (void)_removeCursor;	// 0x366f9aad
- (void)_submitButtonClick:(id)click;	// 0x366f9a15
- (void)_switchFocusToSubmitButton;	// 0x366f99a5
- (BOOL)accessibilityOutputsRangeForChildren;	// 0x366f9809
- (id)accessibilityScreenContent;	// 0x366f97e9
- (BOOL)brEventAction:(id)action;	// 0x366f8a29
- (void)dealloc;	// 0x366f88ad
- (void)displayTextEntryHistoryForClients:(id)clients textEntryBehaviors:(id)behaviors;	// 0x366f89d5
// converted property getter: - (id)editor;	// 0x366f8a15
- (BOOL)isValidAfterDataUpdate;	// 0x366f8a25
- (void)layoutSubcontrols;	// 0x366f8c29
// declared property getter: - (XXStruct_qlg9jA)maxFootnoteTextHeight;	// 0x366f9969
- (void)reset;	// 0x366f97c9
- (void)setDisplayTextEntryHistory:(BOOL)history;	// 0x366f89b5
- (void)setFocusToGlyphNamed:(id)glyphNamed;	// 0x366f9745
- (void)setFootnoteText:(id)text withAttributes:(id)attributes;	// 0x366f980d
- (void)setInitialTextEntryText:(id)text;	// 0x366f96f1
// declared property setter: - (void)setMaxFootnoteTextHeight:(XXStruct_qlg9jA)height;	// 0x366f9985
- (void)setSecondaryInfoText:(id)text withAttributes:(id)attributes;	// 0x366f94ad
- (void)setShowUserEnteredText:(BOOL)text;	// 0x366f97a9
- (void)setSupplementaryText:(id)text;	// 0x366f9575
- (void)setTextEntryHistoryClient:(id)client textEntryBehavior:(id)behavior;	// 0x366f89f5
- (void)setTextEntryStyle:(int)style;	// 0x366f946d
- (void)setTextEntryTextFieldLabel:(id)label;	// 0x366f9585
- (void)setTextFieldDelegate:(id)delegate;	// 0x366f96d1
@end

