//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

#import "BRTabControlDelegate.h"
#import "BRTextFieldCharacterInputDelegate.h"

@class BRCursorControl, BRDeviceKeyboardMessage, BRInputMethod, BRKeyboard, BRKeyboardControl, BRScrollControl, BRTabControl, BRTextControl, BRTextEntryPlayPauseMessage, BRTextFieldBackgroundLayer, BRTextFieldControl, NSArray, NSAttributedString, NSMutableSet, NSString;

@interface BRTextEntryControl : BRControl <BRTabControlDelegate, BRTextFieldCharacterInputDelegate>
{
    int _textEntryStyle;
    BRInputMethod *_inputMethod;
    BRKeyboard *_activeKeyboard;
    NSMutableSet *_validInputCharacterSet;
    BOOL _displayTextEntryHistory;
    NSString *_textEntryHistoryClient;
    NSString *_textEntryHistoryBehavior;
    BRTextEntryPlayPauseMessage *_playPauseMessage;
    BRControl *_candidatesBackground;
    BRScrollControl *_candidatesKeysContainer;
    BRKeyboardControl *_keyboardControl;
    BRScrollControl *_keyboardContainer;
    BRControl *_actionKeysContainer;
    BRTextFieldBackgroundLayer *_textFieldBackground;
    BRTextControl *_textFieldLabel;
    NSAttributedString *_textFieldLabelString;
    BRTextFieldControl *_textField;
    BRTabControl *_tabControl;
    BRCursorControl *_cursor;
    BOOL _providesOwnCursor;
    NSArray *_customizedTextFieldControls;
    BRDeviceKeyboardMessage *_deviceKeyboardMessage;
    BRKeyboard *_popupKeyboard;
    struct CGPoint _focusedMainKeyRemembery;
    BOOL _displayPopupKeyboardAfterKeyboardSwitch;
    struct CGColor *_popupBackgroundColor;
    struct CGColor *_popupBorderColor;
    int _popupShadowStyle;
    BOOL _constrainCursorToPopupKeyboard;
    BRKeyboardControl *_popupKeyboardControl;
    struct CGPoint _previousKeyboardFocus;
    int _textLengthLimit;
    BOOL _showUserEnteredText;
    BOOL _textFieldIsInternal;
    BOOL _shouldRestoreTextFieldCursor;
    BOOL _shouldWrapHorizontally;
    BOOL _shouldWrapVertically;
    BOOL _clientHasSpecifiedHorizontalWrapping;
    BOOL _clientHasSpecifiedVerticalWrapping;
    BOOL _displayPlayPauseMessage;
    NSString *_uniqueIDForPlayPauseRegistration;
    NSString *_lastStringSetIntoTextField;
}

- (void)_addCursor;
- (void)_addCustomizedTextFieldControls;
- (void)_addMainKeyboardContainerForKeyboard:(id)arg1;
- (void)_addOrRemoveCandidatesContainer:(id)arg1;
- (void)_addOrRemoveTabControl;
- (id)_bestKeyboardLanguage:(int)arg1;
- (id)_currentTextEntryStyleName;
- (void)_customizeTextEntryControls;
- (void)_finalizeControlWasFocused;
- (void)_generateKeyEventWithCharacters:(id)arg1 immediatelyObscureCharacters:(BOOL)arg2;
- (void)_handleDisplayPopupKeyboardEvent:(BOOL)arg1;
- (void)_inputActionAppendCandidate:(id)arg1;
- (void)_inputActionAppendText:(id)arg1;
- (void)_inputActionClearText:(id)arg1;
- (void)_inputActionDeleteText:(id)arg1;
- (void)_inputActionEscape:(id)arg1;
- (void)_inputActionSwitchInputMethod:(id)arg1;
- (void)_inputActionSwitchKeyboard:(id)arg1;
- (void)_invokeInputActionWithDictionary:(id)arg1;
- (id)_keyboardMappingData;
- (void)_registerAsTextFieldCharacterInputDelegate;
- (void)_removeActionKeysRow;
- (void)_removeCursor;
- (void)_removeCustomizedTextFieldControls;
- (void)_removePopupKeyboard;
- (void)_saveTextEntryHistory;
- (void)_setActiveKeyboard:(id)arg1;
- (BOOL)_shouldIgnoreKey:(id)arg1 forTextField:(id)arg2;
- (id)_stringFromRect:(struct CGRect)arg1;
- (void)_stripTrailingDotIfNecessary:(id)arg1;
- (void)_swapPopupkeyboard;
- (void)_textDidChangeNotification:(id)arg1;
- (void)_textDidEndEditingNotification:(id)arg1;
- (void)_unregisterAsTextFieldCharacterInputDelegate;
- (void)_wrapAroundEdge:(int)arg1;
- (id)accessibilityLabel;
- (id)accessibilityScreenContent;
- (id)accessibilityTraits;
- (id)accessibilityValue;
- (BOOL)brEventAction:(id)arg1;
- (BOOL)canWrapHorizontally;
- (BOOL)canWrapVertically;
- (void)completeTextEntry;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)controlWasFocused;
- (void)controlWasUnfocused;
- (void)dealloc;
- (void)deleteAllHistoryItemsForClients:(id)arg1;
- (void)deleteTextEntryHistoryItem:(id)arg1 forTextEntryHistoryClients:(id)arg2 textEntryBehaviors:(id)arg3;
- (void)deviceKeyboardClose;
- (void)deviceKeyboardMessageHandler:(id)arg1;
- (void)deviceKeyboardUpdate:(BOOL)arg1;
- (void)dismissPopupKeyboard;
- (void)displayTextEntryHistoryForClients:(id)arg1 textEntryBehaviors:(id)arg2;
- (BOOL)focusIsAtRightEdge;
- (id)init;
- (id)initWithTextEntryStyle:(int)arg1;
- (void)invokeInputActionWithDictionary:(id)arg1;
- (struct CGPoint)keyboardFocus;
- (void)layoutSubcontrols;
- (BOOL)providesOwnFocusCursor;
- (void)reset;
- (void)saveTextEntryHistory;
- (void)saveTextEntryHistoryUsingClient:(id)arg1 textEntryBehavior:(id)arg2;
- (void)setCanWrapHorizontally:(BOOL)arg1;
- (void)setCanWrapVertically:(BOOL)arg1;
- (void)setConstrainCursorToPopupKeyboard:(BOOL)arg1;
- (void)setDeviceKeyboardTitle:(id)arg1 subText:(id)arg2;
- (void)setDisplayPlayPauseMessage:(BOOL)arg1;
- (void)setDisplayTextEntryHistory:(BOOL)arg1;
- (void)setFocusToGlyphNamed:(id)arg1;
- (void)setInitialText:(id)arg1;
- (void)setKeyboardFocus:(struct CGPoint)arg1;
- (void)setPopupBackgroundColor:(struct CGColor *)arg1;
- (void)setPopupOutlineColor:(struct CGColor *)arg1;
- (void)setPopupShadowStyle:(int)arg1;
- (void)setProvidesOwnFocusCursor:(BOOL)arg1;
- (void)setShowUserEnteredText:(BOOL)arg1;
- (void)setTabControl:(id)arg1;
- (void)setTextEntryHistoryClient:(id)arg1 textEntryBehavior:(id)arg2;
- (void)setTextEntryStyle:(int)arg1;
- (void)setTextField:(id)arg1;
- (void)setTextFieldDelegate:(id)arg1;
- (void)setTextFieldLabel:(id)arg1;
- (void)setTextLengthLimit:(int)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)startSpinning;
- (void)stopSpinning;
- (void)switchToKeyboardNamed:(id)arg1 focusOnKeyboardAfterSwitch:(BOOL)arg2;
- (id)tabControl;
- (void)tabControl:(id)arg1 didSelectTabItem:(id)arg2;
- (void)tabControl:(id)arg1 willSelectTabItem:(id)arg2;
- (void)tabControlDidChangeNumberOfTabItems:(id)arg1;
- (int)textEntryStyle;
- (id)textField;
- (id)textFieldDelegate;
- (int)textLengthLimit;

@end

