/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <CALayer.h> // Unknown library


__attribute__((visibility("hidden")))
@interface BRTileLayer : CALayer {
}
+ (id)defaultActionForKey:(id)key;	// 0x367104d5
@end

