//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRStrokeAndFillTextControl, BRTextControl, BRTransportLayer, NSArray, NSDateFormatter, NSTimer;

__attribute__((visibility("hidden")))
@interface BRTransportControl : BRControl
{
    long _duration;
    long _elapsedTime;
    id <BRTransportDataProvider> _dataProvider;
    BRTransportLayer *_layer;
    BRTextControl *_durationLayer;
    BRStrokeAndFillTextControl *_elapsedTimeLayer;
    BRTextControl *_leftSideTextLayer;
    BRStrokeAndFillTextControl *_chapterLayer;
    NSArray *_chapterMarkers;
    NSArray *_interstitialMarkers;
    NSDateFormatter *_timeFormatter;
    NSTimer *_fadeTimer;
    NSTimer *_transportBarTimer;
}

- (id)_chapterAttributes;
- (id)_chapterMarkerLocations;
- (void)_fadeTransport:(id)arg1;
- (void)_handleBufferChanged:(id)arg1;
- (void)_handlePlayerAssetChanged:(id)arg1;
- (void)_handlePlayerTimeChanged:(id)arg1;
- (void)_handleStateChange:(id)arg1;
- (void)_handleTimeSkip:(id)arg1;
- (void)_handleVolumeChange:(id)arg1;
- (void)_hideTransport;
- (id)_interstitialMarkerLocations;
- (BOOL)_shouldShowChapterGroupName;
- (BOOL)_shouldShowChapterMarks;
- (void)_showTransport;
- (void)_showTransportTimerFired:(id)arg1;
- (void)_showTransportWithTimeout;
- (void)_showTransportWithTimeoutInSeconds:(float)arg1;
- (id)_trackTimeAttributes;
- (void)_updateAll;
- (void)_updateBufferingProgressForNonLiveContent;
- (void)_updateTimeAndBufferingForLiveContent;
- (void)_updateTimeForNonLiveContent;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)dealloc;
- (void)hideTransport;
- (id)initWithSpinner:(BOOL)arg1;
- (BOOL)isHidden;
- (void)layoutSubcontrols;
- (void)setDataProvider:(id)arg1 eventSource:(id)arg2;
- (void)setShowChapterMarks:(BOOL)arg1;
- (void)showTransport;
- (void)showTransportWithLongTimeout;
- (void)showTransportWithMediumTimeout;
- (void)showTransportWithShortTimeout;

@end

