//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



@protocol BRTransportDataProvider <NSObject>
- (struct BRTimeRange)bufferedRange;
- (float)bufferingProgress;
- (id)chapterAtIndex:(long)arg1;
- (id)chapterGroupAtIndex:(long)arg1;
- (long)chapterGroupCount;
- (long)chapterGroupIndex;
- (id)chapters;
- (long)currentChapterIndex;
- (long)currentInterstitialIndex;
- (double)duration;
- (double)elapsedTime;
- (id)interstitialTimes;
- (BOOL)isAssetReadyToPlay:(id)arg1;
- (id)playbackDate;
- (int)playerState;
- (BOOL)supportsBufferedRange;
- (double)virtualChapterMark;
@end

