/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTrackInfoLayer, NSString, BRMediaPlayer;

__attribute__((visibility("hidden")))
@interface BRTrackInfoControl : BRControl {
@private
	BRTrackInfoLayer *_layer;	// 48 = 0x30
	BRMediaPlayer *_player;	// 52 = 0x34
	NSString *_lastAssetID;	// 56 = 0x38
}
@property(retain) BRMediaPlayer *player;	// G=0x366d9081; S=0x366d8f79; converted property
- (id)init;	// 0x366d8cd9
- (id)_fetchCoverArt;	// 0x366d9271
- (void)_playbackAssetChanged:(id)changed;	// 0x366d935d
- (void)_playerStateChanged:(id)changed;	// 0x366d931d
- (BOOL)_supportsShowingArtist:(id)artist;	// 0x366d9439
- (BOOL)_supportsShowingPrimaryCollectionTitle:(id)title;	// 0x366d94d5
- (void)_updateCoverArt:(id)art;	// 0x366d936d
- (void)_updateTrackInfo;	// 0x366d90b1
- (id)accessibilityLabel;	// 0x366d9091
- (void)controlWasActivated;	// 0x366d8e0d
- (void)controlWasDeactivated;	// 0x366d8edd
- (void)dealloc;	// 0x366d8d69
// converted property getter: - (id)player;	// 0x366d9081
// converted property setter: - (void)setPlayer:(id)player;	// 0x366d8f79
@end

