//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

@class BRMediaPlayer, BRTrackInfoLayer, NSString;

__attribute__((visibility("hidden")))
@interface BRTrackInfoControl : BRControl
{
    BRTrackInfoLayer *_layer;
    BRMediaPlayer *_player;
    NSString *_lastAssetID;
}

- (id)_fetchCoverArt;
- (void)_playbackAssetChanged:(id)arg1;
- (void)_playerStateChanged:(id)arg1;
- (BOOL)_supportsShowingArtist:(id)arg1;
- (BOOL)_supportsShowingPrimaryCollectionTitle:(id)arg1;
- (void)_updateCoverArt:(id)arg1;
- (void)_updateTrackInfo;
- (id)accessibilityLabel;
- (void)controlWasActivated;
- (void)controlWasDeactivated;
- (void)dealloc;
- (id)init;
- (id)player;
- (void)setPlayer:(id)arg1;

@end

