//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRControl.h>

@class BRImageControl;

@interface BRTumblerControl : BRControl
{
    id <BRTumblerDataSource> _dataSource;
    id <BRTumblerDelegate> _delegate;
    unsigned int _currentIndex;
    unsigned int _itemCount;
    BRControl *_currentItem;
    BRControl *_nextItem;
    BRControl *_prevItem;
    BRControl *_nextNextItem;
    BRControl *_prevPrevItem;
    int _tumbleState;
    BRControl *_nextFade;
    BRControl *_prevFade;
    BRControl *_nextBlackout;
    BRControl *_prevBlackout;
    BRImageControl *_nextArrow;
    BRImageControl *_prevArrow;
    struct CGSize _sizeThatFits;
}

- (id)_arrowAnimations;
- (id)_controlFromDataSourceAtIndex:(unsigned int)arg1;
- (struct CGPoint)_currentPos;
- (id)_nextFadeFilters;
- (struct CGPoint)_nextNextPos;
- (struct CGPoint)_nextPos;
- (id)_prevFadeFilters;
- (struct CGPoint)_prevPos;
- (struct CGPoint)_prevPrevPos;
- (BOOL)_tumbleNextShouldAnimate:(BOOL)arg1;
- (BOOL)_tumblePrevShouldAnimate:(BOOL)arg1;
- (id)accessibilityLabel;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (BOOL)brEventAction:(id)arg1;
@property(readonly, nonatomic) BRControl *currentItem; // @synthesize currentItem=_currentItem;
@property(nonatomic) unsigned int currentItemIndex;
@property(nonatomic) id <BRTumblerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)dealloc;
@property(nonatomic) id <BRTumblerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
@property(readonly) float itemPadding; // @dynamic itemPadding;
- (void)layoutSubcontrols;
- (void)reload;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

