/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */



@protocol BRTumblerDataSource
- (unsigned)itemCountForTumbler:(id)tumbler;
- (id)tumblerControl:(id)control itemAtIndex:(unsigned)index;
@end

