//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface BRTypesetLine : NSObject
{
    struct __CTLine *_line;
    struct CGSize _shadowOffset;
    float _shadowBlurAmount;
    float _flushFactor;
}

- (void)dealloc;
- (void)drawLineAtPoint:(struct CGPoint)arg1 withWidth:(float)arg2 inContext:(struct CGContext *)arg3;
- (id)initWithCTLineRef:(struct __CTLine *)arg1 shadowOffset:(struct CGSize)arg2 shadowBlurAmount:(float)arg3 flushFactor:(float)arg4;
- (void)typographicBounds:(float *)arg1 descent:(float *)arg2 leading:(float *)arg3;

@end

