/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <NSObject.h> // Unknown library

@class NSAttributedString, NSMutableArray;

@interface BRTypesetter : NSObject {
@private
	NSAttributedString *_resolvedString;	// 4 = 0x4
	CTTypesetterRef _setter;	// 8 = 0x8
	NSMutableArray *_lines;	// 12 = 0xc
	CGSize _boxSize;	// 16 = 0x10
	CGSize _shadowOffset;	// 24 = 0x18
	CGColorRef _shadowColor;	// 32 = 0x20
	float _shadowBlurAmount;	// 36 = 0x24
	float _flushFactor;	// 40 = 0x28
	BOOL _renderingAttributesFetched;	// 44 = 0x2c
}
+ (float)pointSizeForBoxHeight:(float)boxHeight fontName:(id)name;	// 0x36775731
- (id)initWithAttributedString:(id)attributedString textBoxSize:(CGSize)size;	// 0x36774f3d
- (id)_boxLines:(BOOL *)lines;	// 0x3677597d
- (void)_justifyLines:(id)lines;	// 0x36775b39
- (CTLineRef)_truncateLine:(CTLineRef)line withSetting:(unsigned char)setting;	// 0x36775bc9
- (CTLineRef)_truncationToken;	// 0x36775c61
- (void)_updateRenderingAttributes;	// 0x36775791
- (void)dealloc;	// 0x36775249
- (void)drawTextAtPoint:(CGPoint)point inContext:(CGContextRef)context;	// 0x36775409
- (id)lineAtIndex:(long)index;	// 0x36775639
- (long)numLines;	// 0x36775619
- (CGSize)typographicBounds;	// 0x367752d5
@end

