/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSString;

@interface BRType : NSObject {
@private
	NSString *_typeString;	// 4 = 0x4
}
@property(readonly, retain) NSString *typeString;	// G=0x367748e5; converted property
+ (id)_typeCache;	// 0x367748f5
+ (id)_unknownTypes;	// 0x367749f5
+ (id)typeEnumerator;	// 0x367743a1
+ (id)typeForString:(id)string;	// 0x367744c1
+ (id)unknown;	// 0x36774251
- (id)initWithString:(id)string;	// 0x36774645
- (void)dealloc;	// 0x36774899
// converted property getter: - (id)typeString;	// 0x367748e5
@end

