/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSelectionLozengeLayer.h"
#import "AppleTV-Structs.h"

@class BRImage;

__attribute__((visibility("hidden")))
@interface BRUnboundedSelectionLozengeLayer : BRSelectionLozengeLayer {
@private
	BRImage *_topImage;	// 48 = 0x30
	BRImage *_bottomImage;	// 52 = 0x34
	BOOL _brighterImage;	// 56 = 0x38
	BOOL _focusedImage;	// 57 = 0x39
}
@property(assign) BOOL useBrighterUnselectedImage;	// G=0x366a17c9; S=0x366a1799; converted property
- (id)init;	// 0x366a16dd
- (void)_updateImages;	// 0x366a18dd
- (void)dealloc;	// 0x366a1739
- (void)drawInContext:(CGContextRef)context;	// 0x366a180d
- (void)layoutSubcontrols;	// 0x366a1809
- (void)setFocused:(BOOL)focused;	// 0x366a17d9
// converted property setter: - (void)setUseBrighterUnselectedImage:(BOOL)image;	// 0x366a1799
// converted property getter: - (BOOL)useBrighterUnselectedImage;	// 0x366a17c9
@end

