/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRMercantile.h"

@class NSThread, NSURLConnection, BRURLDocumentManager, NSError, BRMerchant, NSURLRequest, NSURLResponse, NSMutableDictionary, NSMutableData, NSDate;

@interface BRURLDocument : NSObject <BRMercantile> {
@private
	NSURLRequest *_request;	// 4 = 0x4
	NSURLResponse *_response;	// 8 = 0x8
	NSError *_error;	// 12 = 0xc
	NSMutableData *_content;	// 16 = 0x10
	BRURLDocumentManager *_manager;	// 20 = 0x14
	NSURLConnection *_connection;	// 24 = 0x18
	NSThread *_callingThread;	// 28 = 0x1c
	NSMutableDictionary *_metadata;	// 32 = 0x20
	unsigned _documentNumber;	// 36 = 0x24
	NSDate *_requestDate;	// 40 = 0x28
	NSDate *_loadedDate;	// 44 = 0x2c
	BOOL _wasRedirected;	// 48 = 0x30
	BOOL _cancelled;	// 49 = 0x31
	BOOL _loaded;	// 50 = 0x32
}
@property(retain) id URLRequest;	// G=0x36778271; S=0x36778131; converted property
@property(readonly, retain) NSThread *callingThread;	// G=0x367782fd; converted property
@property(readonly, assign) BOOL cancelled;	// G=0x367784a9; converted property
@property(retain) NSMutableData *content;	// G=0x3677835d; S=0x36779ebd; converted property
@property(retain) NSError *error;	// G=0x3677834d; S=0x3677830d; converted property
@property(readonly, assign) BOOL loaded;	// G=0x3677836d; converted property
@property(readonly, retain) NSDate *loadedDate;	// G=0x36778499; converted property
@property(readonly, retain) BRURLDocumentManager *manager;	// G=0x36779ead; converted property
@property(retain, nonatomic) BRMerchant *merchant;	// G=0x367784c9; S=0x36778595; 
@property(readonly, retain) NSDate *requestDate;	// G=0x36778489; converted property
@property(readonly, assign) BOOL wasRedirected;	// G=0x367784b9; converted property
+ (id)documentWithURLRequest:(id)urlrequest;	// 0x36777d59
+ (id)documentWithURLRequest:(id)urlrequest forMerchant:(id)merchant;	// 0x36777d95
- (id)init;	// 0x36777f09
- (id)initWithURLRequest:(id)urlrequest;	// 0x36777dd5
- (id)initWithURLRequest:(id)urlrequest forMerchant:(id)merchant;	// 0x36777de9
// converted property getter: - (id)URLRequest;	// 0x36778271
- (id)URLResponse;	// 0x36778281
- (void)_cancel;	// 0x36778655
- (void)_documentDidLoad;	// 0x367785d5
- (unsigned)_documentNumber;	// 0x367787e1
- (void)_extractCookies;	// 0x36778e85
- (id)_manager;	// 0x36778645
- (void)_setConnection:(id)connection;	// 0x36778761
- (void)_setDocumentNumber:(unsigned)number;	// 0x367787d1
- (void)_setManager:(id)manager;	// 0x36778635
- (void)_setRequestDate:(id)date;	// 0x367787f1
- (void)_threadDeath:(id)death;	// 0x367787a1
- (void)_verifyDocument;	// 0x36778831
- (void)_verifyTypesInFeed:(id)feed parentKeys:(id)keys learnTypes:(BOOL)types;	// 0x36778b31
// converted property getter: - (id)callingThread;	// 0x367782fd
- (void)cancel;	// 0x367783f1
// converted property getter: - (BOOL)cancelled;	// 0x367784a9
- (void)clearError;	// 0x3677845d
- (BOOL)connection:(id)connection canAuthenticateAgainstProtectionSpace:(id)space;	// 0x36779a75
- (void)connection:(id)connection didFailWithError:(id)error;	// 0x36778f99
- (void)connection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;	// 0x36779c09
- (void)connection:(id)connection didReceiveData:(id)data;	// 0x367793c9
- (void)connection:(id)connection didReceiveResponse:(id)response;	// 0x36779241
- (id)connection:(id)connection willCacheResponse:(id)response;	// 0x36779e69
- (id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;	// 0x367794c9
- (void)connectionDidFinishLoading:(id)connection;	// 0x36779795
// converted property getter: - (id)content;	// 0x3677835d
- (id)copyForLoading;	// 0x36777f0d
- (void)dealloc;	// 0x36778029
- (void)documentDidLoad;	// 0x3677837d
- (void)documentLoaded;	// 0x3677838d
// converted property getter: - (id)error;	// 0x3677834d
// converted property getter: - (BOOL)loaded;	// 0x3677836d
// converted property getter: - (id)loadedDate;	// 0x36778499
// converted property getter: - (id)manager;	// 0x36779ead
// declared property getter: - (id)merchant;	// 0x367784c9
- (id)metadataForKey:(id)key;	// 0x367783b1
// converted property getter: - (id)requestDate;	// 0x36778489
// converted property setter: - (void)setContent:(id)content;	// 0x36779ebd
// converted property setter: - (void)setError:(id)error;	// 0x3677830d
// declared property setter: - (void)setMerchant:(id)merchant;	// 0x36778595
- (void)setMetadata:(id)metadata forKey:(id)key;	// 0x36778391
// converted property setter: - (void)setURLRequest:(id)request;	// 0x36778131
- (void)setValue:(id)value forUndefinedKey:(id)undefinedKey;	// 0x367783e1
- (int)statusCode;	// 0x36778291
- (id)valueForUndefinedKey:(id)undefinedKey;	// 0x367783d1
// converted property getter: - (BOOL)wasRedirected;	// 0x367784b9
@end

