//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//



#import "BRMercantile-Protocol.h"

@class BRMerchant, BRURLDocumentManager, NSDate, NSError, NSMutableData, NSMutableDictionary, NSThread, NSURLConnection, NSURLRequest, NSURLResponse;

@interface BRURLDocument : NSObject <BRMercantile>
{
    NSURLRequest *_request;
    NSURLResponse *_response;
    NSError *_error;
    NSMutableData *_content;
    BRURLDocumentManager *_manager;
    NSURLConnection *_connection;
    NSThread *_callingThread;
    NSMutableDictionary *_metadata;
    unsigned int _documentNumber;
    NSDate *_requestDate;
    NSDate *_loadedDate;
    BOOL _wasRedirected;
    BOOL _cancelled;
    BOOL _loaded;
}

+ (id)documentWithURLRequest:(id)arg1;
+ (id)documentWithURLRequest:(id)arg1 forMerchant:(id)arg2;
- (id)URLRequest;
- (id)URLResponse;
- (void)_cancel;
- (void)_documentDidLoad;
- (unsigned int)_documentNumber;
- (void)_extractCookies;
- (id)_manager;
- (void)_setConnection:(id)arg1;
- (void)_setDocumentNumber:(unsigned int)arg1;
- (void)_setManager:(id)arg1;
- (void)_setRequestDate:(id)arg1;
- (void)_threadDeath:(id)arg1;
- (void)_verifyDocument;
- (void)_verifyTypesInFeed:(id)arg1 parentKeys:(id)arg2 learnTypes:(BOOL)arg3;
- (id)callingThread;
- (void)cancel;
- (BOOL)cancelled;
- (void)clearError;
- (BOOL)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connectionDidFinishLoading:(id)arg1;
- (id)content;
- (id)copyForLoading;
- (void)dealloc;
- (void)documentDidLoad;
- (void)documentLoaded;
- (id)error;
- (id)init;
- (id)initWithURLRequest:(id)arg1;
- (id)initWithURLRequest:(id)arg1 forMerchant:(id)arg2;
- (BOOL)loaded;
- (id)loadedDate;
- (id)manager;
@property(retain, nonatomic) BRMerchant *merchant;
- (id)metadataForKey:(id)arg1;
- (id)requestDate;
- (void)setContent:(id)arg1;
- (void)setError:(id)arg1;
- (void)setMetadata:(id)arg1 forKey:(id)arg2;
- (void)setURLRequest:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (int)statusCode;
- (id)valueForUndefinedKey:(id)arg1;
- (BOOL)wasRedirected;

@end

