//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class BRAsyncTaskContext, NSMutableArray;

@interface BRURLDocumentManager : NSObject
{
    NSMutableArray *_activeDocuments;
    NSMutableArray *_queue;
    BRAsyncTaskContext *_taskContext;
}

+ (void)_processCompleteDocuments:(id)arg1;
+ (void)initialize;
+ (id)textDocumentManager;
- (void)_documentComplete:(id)arg1;
- (void)_processLoadDocument:(id)arg1;
- (void)_removeActiveDocument:(id)arg1;
- (id)_synchronizationObject;
- (void)cancelLoad:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)loadDocument:(id)arg1;
- (void)loadDocument:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)loadDocuments:(id)arg1 documentReadyHandler:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)purgeDocuments;

@end

