//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@interface BRUserPasswordAuthenticationResources : NSObject
{
}

+ (id)resources;
- (id)accountNameFootnote;
- (id)accountNameInstructions;
- (id)accountNameLabel;
- (id)accountNameTitle;
- (id)accountPasswordInstructions;
- (id)accountPasswordLabel;
- (id)accountPasswordTitle;
- (id)authenticationCancellationTitle;
- (id)authenticationFailureInstructions;
- (id)authenticationFailureTitle;
- (double)authenticationTimeout;
- (id)authenticationTimeoutMessage;
- (id)behaviorIdentifierForTextHistoryStorage;
- (id)behaviorsForTextHistoryDisplay;
- (id)clientIdentifierForTextHistoryStorage;
- (id)clientsForTextHistoryDisplay;
- (id)connectionString;
- (id)defaultPasswordKey;
- (id)defaultUserName;
- (id)defaultUserNameKey;
- (id)titleImage;

@end

