/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRUserPasswordAuthenticator.h"


@interface BRUserPasswordCollectingAuthenticator : BRUserPasswordAuthenticator {
}
- (void)_sendAuthenticationRequest;	// 0x36733a61
- (BOOL)requiresUser:(id *)user;	// 0x367339b1
@end

