/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


@interface BRUsageReporter : NSObject {
}
+ (void)clearDistributionKey:(id)key;	// 0x3677c25d
+ (void)clearScalarKey:(id)key;	// 0x3677c179
+ (void)decrementScalarKey:(id)key;	// 0x3677c1e9
+ (void)incrementScalarKey:(id)key;	// 0x3677c1b1
+ (void)pushValue:(double)value forDistributionKey:(id)distributionKey;	// 0x3677c295
+ (void)setValue:(long long)value forScalarKey:(id)scalarKey;	// 0x3677c221
@end

