/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRAuthenticationController.h"

@class BRWaitPromptControl, NSTimer, BRBoxControl, NSString;

@interface BRUserPasswordAuthenticationController : BRAuthenticationController {
@private
	NSString *_userName;	// 100 = 0x64
	NSTimer *_authTimeoutTimer;	// 104 = 0x68
	NSTimer *_promptTimer;	// 108 = 0x6c
	BOOL _hasTimedOut;	// 112 = 0x70
	BRBoxControl *_contentWrapper;	// 116 = 0x74
	BRWaitPromptControl *_waitPrompt;	// 120 = 0x78
}
- (id)initWithAuthenticator:(id)authenticator resources:(id)resources;	// 0x36645f59
- (void)_askUserForPassword:(id)password userName:(id)name completionHandler:(id)handler;	// 0x36646c1d
- (void)_askUserForUserName:(id)userName completionHandler:(id)handler;	// 0x36646701
- (void)_authSucceededComplete:(BOOL)complete;	// 0x36646695
- (void)_authenticate;	// 0x36647691
- (void)_authenticationTimedOut:(id)anOut;	// 0x366474bd
- (void)_setContent:(id)content;	// 0x3664653d
- (void)_setUserName:(id)name;	// 0x366466c1
- (BOOL)_shouldAttemptAuthorizationAgainForUser:(id)user error:(id)error;	// 0x366470e1
- (void)_showCancellationMessage:(id)message;	// 0x366472a5
- (void)_showPrompt:(id)prompt;	// 0x366473ad
- (void)authenticationCancelled:(id)cancelled;	// 0x366461cd
- (void)authenticationFailed:(id)failed;	// 0x366462d1
- (void)authenticationSucceeded:(BOOL)succeeded;	// 0x36646129
- (BOOL)configurePostUserPasswordOptionsWithUser:(id)user;	// 0x36647bf5
- (BOOL)configurePreUserPasswordOptions;	// 0x36647bf1
- (void)dealloc;	// 0x366460dd
- (BOOL)handleDisplayForAuthCancelledError:(id)authCancelledError;	// 0x36647bfd
- (BOOL)handleDisplayForAuthFailureError:(id)authFailureError userName:(id)name attempAuthorizationAgain:(BOOL *)again;	// 0x36647c01
- (void)layoutSubcontrols;	// 0x366464a9
- (BOOL)performPostAuthenticationOperationsWithUser:(id)user accountOptionsPreviouslySet:(BOOL)set;	// 0x36647bf9
- (void)wasPopped;	// 0x36646421
- (void)wasPushed;	// 0x366463bd
@end

