//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRAuthenticationController.h"

@class BRBoxControl, BRWaitPromptControl, NSString, NSTimer;

@interface BRUserPasswordAuthenticationController : BRAuthenticationController
{
    NSString *_userName;
    NSTimer *_authTimeoutTimer;
    NSTimer *_promptTimer;
    BOOL _hasTimedOut;
    BRBoxControl *_contentWrapper;
    BRWaitPromptControl *_waitPrompt;
}

- (void)_askUserForPassword:(id)arg1 userName:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_askUserForUserName:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_authSucceededComplete:(BOOL)arg1;
- (void)_authenticate;
- (void)_authenticationTimedOut:(id)arg1;
- (void)_setContent:(id)arg1;
- (void)_setUserName:(id)arg1;
- (BOOL)_shouldAttemptAuthorizationAgainForUser:(id)arg1 error:(id)arg2;
- (void)_showCancellationMessage:(id)arg1;
- (void)_showPrompt:(id)arg1;
- (void)authenticationCancelled:(id)arg1;
- (void)authenticationFailed:(id)arg1;
- (void)authenticationSucceeded:(BOOL)arg1;
- (BOOL)configurePostUserPasswordOptionsWithUser:(id)arg1;
- (BOOL)configurePreUserPasswordOptions;
- (void)dealloc;
- (BOOL)handleDisplayForAuthCancelledError:(id)arg1;
- (BOOL)handleDisplayForAuthFailureError:(id)arg1 userName:(id)arg2 attempAuthorizationAgain:(char *)arg3;
- (id)initWithAuthenticator:(id)arg1 resources:(id)arg2;
- (void)layoutSubcontrols;
- (BOOL)performPostAuthenticationOperationsWithUser:(id)arg1 accountOptionsPreviouslySet:(BOOL)arg2;
- (void)wasPopped;
- (void)wasPushed;

@end

