//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "BRControl.h"

@class BRImageControl;

__attribute__((visibility("hidden")))
@interface BRVerticalScrollBarControl : BRControl
{
    BRImageControl *_image;
    float _position;
}

- (void)dealloc;
- (id)image;
- (id)init;
- (void)layoutSubcontrols;
- (void)setImage:(id)arg1;
- (void)setScrollPosition:(float)arg1;

@end

