//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRController.h>

@class BRControl;

@interface BRViewController : BRController
{
    BRControl *_view;
}

- (void)_handleWindowMaxBoundsChanged;
- (void)dealloc;
- (void)layoutSubcontrols;
- (void)setView:(id)arg1;
- (id)view;

@end

