//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface BRVOSpeechAction : NSObject
{
    NSString *_string;
    NSString *_pitch;
    NSString *_language;
    BOOL _shouldQueue;
    BOOL _cannotInterrupt;
    CDUnknownBlockType _completionCallback;
}

+ (id)actionWithString:(id)arg1 shouldQueue:(BOOL)arg2;
@property(nonatomic) BOOL cannotInterrupt; // @synthesize cannotInterrupt=_cannotInterrupt;
@property(copy, nonatomic) CDUnknownBlockType completionCallback; // @synthesize completionCallback=_completionCallback;
- (void)dealloc;
- (id)description;
@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
@property(retain, nonatomic) NSString *pitch; // @synthesize pitch=_pitch;
@property(nonatomic) BOOL shouldQueue; // @synthesize shouldQueue=_shouldQueue;
@property(copy, nonatomic) NSString *string; // @synthesize string=_string;

@end

