/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRPercentageIndicatorLayer, BRImageControl;

__attribute__((visibility("hidden")))
@interface BRVolumeControl : BRControl {
@private
	BRImageControl *_speakerOnLayer;	// 48 = 0x30
	BRImageControl *_speakerOffLayer;	// 52 = 0x34
	BRPercentageIndicatorLayer *_percentageIndicatorLayer;	// 56 = 0x38
}
@property(assign) float volume;	// G=0x366fa381; S=0x366fa281; converted property
- (id)init;	// 0x366f9e19
- (void)dealloc;	// 0x366fa0f1
- (void)layoutSubcontrols;	// 0x366fa165
// converted property setter: - (void)setVolume:(float)volume;	// 0x366fa281
// converted property getter: - (float)volume;	// 0x366fa381
@end

