/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface BRVOSpeechAction : NSObject {
@private
	NSString *_string;	// 4 = 0x4
	NSString *_pitch;	// 8 = 0x8
	NSString *_language;	// 12 = 0xc
	BOOL _shouldQueue;	// 16 = 0x10
	BOOL _cannotInterrupt;	// 17 = 0x11
	id _completionCallback;	// 20 = 0x14
}
@property(assign, nonatomic) BOOL cannotInterrupt;	// G=0x366425e1; S=0x366425f1; @synthesize=_cannotInterrupt
@property(copy, nonatomic) id completionCallback;	// G=0x36642635; S=0x36642645; @synthesize=_completionCallback
@property(retain, nonatomic) NSString *language;	// G=0x36642601; S=0x36642611; @synthesize=_language
@property(retain, nonatomic) NSString *pitch;	// G=0x3664258d; S=0x3664259d; @synthesize=_pitch
@property(assign, nonatomic) BOOL shouldQueue;	// G=0x366425c1; S=0x366425d1; @synthesize=_shouldQueue
@property(copy, nonatomic) NSString *string;	// G=0x36642559; S=0x36642569; @synthesize=_string
+ (id)actionWithString:(id)string shouldQueue:(BOOL)queue;	// 0x36642405
// declared property getter: - (BOOL)cannotInterrupt;	// 0x366425e1
// declared property getter: - (id)completionCallback;	// 0x36642635
- (void)dealloc;	// 0x36642479
- (id)description;	// 0x36642501
// declared property getter: - (id)language;	// 0x36642601
// declared property getter: - (id)pitch;	// 0x3664258d
// declared property setter: - (void)setCannotInterrupt:(BOOL)interrupt;	// 0x366425f1
// declared property setter: - (void)setCompletionCallback:(id)callback;	// 0x36642645
// declared property setter: - (void)setLanguage:(id)language;	// 0x36642611
// declared property setter: - (void)setPitch:(id)pitch;	// 0x3664259d
// declared property setter: - (void)setShouldQueue:(BOOL)queue;	// 0x366425d1
// declared property setter: - (void)setString:(id)string;	// 0x36642569
// declared property getter: - (BOOL)shouldQueue;	// 0x366425c1
// declared property getter: - (id)string;	// 0x36642559
@end

