/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <NSObject.h> // Unknown library

@class NSThread, NSMutableArray, NSDictionary, NSString;
@protocol VSSpeechHiddenProtocol;

__attribute__((visibility("hidden")))
@interface BRVoiceOverSpeechManager : NSObject {
@private
	NSMutableArray *_speechQueue;	// 4 = 0x4
	NSObject<VSSpeechHiddenProtocol> *_synthesizer;	// 8 = 0x8
	NSThread *_runThread;	// 12 = 0xc
	NSDictionary *_pronunciationGuide;	// 16 = 0x10
	NSString *_systemLanguage;	// 20 = 0x14
	BOOL _runLoopEnabled;	// 24 = 0x18
	BOOL _didInitialize;	// 25 = 0x19
	BOOL _isSpeaking;	// 26 = 0x1a
	BOOL _speechEnabled;	// 27 = 0x1b
}
@property(readonly, assign) BOOL isSpeaking;	// G=0x36643881; converted property
@property(assign, nonatomic) BOOL speechEnabled;	// G=0x36643a8d; S=0x36643495; @synthesize=_speechEnabled
@property(assign, nonatomic) float speechRate;	// G=0x366438f1; S=0x366439a1; @dynamic
@property(copy, nonatomic) NSString *systemLanguage;	// G=0x36643a9d; S=0x36643aad; @synthesize=_systemLanguage
+ (URegularExpression *)createRegularExpressionFromString:(id)string;	// 0x36642a0d
+ (id)matchedRangesForString:(id)string withRegularExpression:(URegularExpression *)regularExpression;	// 0x36642a75
- (id)init;	// 0x36642669
- (void)_clearSpeechQueue;	// 0x36643611
- (void)_continueSpeaking;	// 0x3664376d
- (void)_dispatchSpeechAction:(id)action;	// 0x366434c5
- (void)_initialize;	// 0x366428ad
- (void)_isSpeaking:(id)speaking;	// 0x3664382d
- (void)_pauseSpeaking;	// 0x3664370d
- (id)_preprocessString:(id)string language:(id)language;	// 0x36643299
- (id)_processDurationStrings:(id)strings;	// 0x36642ed9
- (id)_processPronunciationChanges:(id)changes language:(id)language;	// 0x3664312d
- (void)_setSpeechRate:(id)rate;	// 0x36643935
- (void)_speechJobFinished:(BOOL)finished;	// 0x36642b95
- (void)_startNextSpeechJob;	// 0x36642d0d
- (void)_stopSpeaking;	// 0x366437cd
- (void)clearSpeechQueue;	// 0x36643631
- (void)continueSpeaking;	// 0x3664378d
- (void)dealloc;	// 0x366427cd
- (void)dispatchSpeechAction:(id)action;	// 0x36643671
// converted property getter: - (BOOL)isSpeaking;	// 0x36643881
- (void)pauseSpeaking;	// 0x3664372d
- (void)setMaintainConnection:(BOOL)connection;	// 0x36642b75
- (void)setPitch:(id)pitch;	// 0x36642c55
// declared property setter: - (void)setSpeechEnabled:(BOOL)enabled;	// 0x36643495
// declared property setter: - (void)setSpeechRate:(float)rate;	// 0x366439a1
// declared property setter: - (void)setSystemLanguage:(id)language;	// 0x36643aad
// declared property getter: - (BOOL)speechEnabled;	// 0x36643a8d
// declared property getter: - (float)speechRate;	// 0x366438f1
- (void)speechSynthesizer:(id)synthesizer didFinishSpeaking:(BOOL)speaking withError:(id)error;	// 0x36643a5d
- (void)stopSpeaking;	// 0x366437ed
// declared property getter: - (id)systemLanguage;	// 0x36643a9d
@end

