/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRControl.h"

@class BRTextControl, BRWaitSpinnerControl;

@interface BRWaitPromptControl : BRControl {
@private
	BRWaitSpinnerControl *_spinner;	// 48 = 0x30
	BRTextControl *_prompt;	// 52 = 0x34
}
@property(retain) BRTextControl *prompt;	// G=0x366e2f11; S=0x366e2ed5; converted property
@property(retain) id promptText;	// G=0x366e2fc1; S=0x366e2f31; converted property
+ (id)themeAttributes;	// 0x366e2ea1
- (id)init;	// 0x366e2d71
- (id)accessibilityLabel;	// 0x366e3205
- (void)controlWasActivated;	// 0x366e324d
- (void)dealloc;	// 0x366e2e41
- (BOOL)isAccessibilityElement;	// 0x366e3249
- (void)layoutSubcontrols;	// 0x366e2ff9
// converted property getter: - (id)prompt;	// 0x366e2f11
// converted property getter: - (id)promptText;	// 0x366e2fc1
// converted property setter: - (void)setPrompt:(id)prompt;	// 0x366e2ed5
// converted property setter: - (void)setPromptText:(id)text;	// 0x366e2f31
@end

