//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class BRControl;

@interface BRWindow : NSObject
{
    BRControl *_content;
    BRControl *_plane;
    int _level;
    BOOL _orderedIn;
    BOOL _opaque;
}

+ (void)_controlWasFocused:(id)arg1;
+ (void)_establishRootContext;
+ (void)_establishRootLayerBounds;
+ (void)adjustToDisplayChange;
+ (BOOL)dispatchEvent:(id)arg1;
+ (id)focusedControl;
+ (id)focusedLeafControl;
+ (void)initialize;
+ (struct CGRect)interfaceFrame;
+ (BOOL)makeFocusedControl:(id)arg1;
+ (struct CGSize)maxBounds;
+ (id)rootLayer;
+ (void)setMaxBounds:(struct CGSize)arg1;
+ (id)window;
+ (id)windowList;
- (void)_addWindow:(id)arg1 atIndex:(long)arg2;
- (id)_controlPlane;
- (void)_orderWindow:(id)arg1 above:(id)arg2;
- (void)_orderWindow:(id)arg1 below:(id)arg2;
- (void)_orderWindowBack:(id)arg1;
- (void)_orderWindowFront:(id)arg1;
- (void)_orderWindowOut:(id)arg1;
- (void)_updateContent;
- (void)_updateRenderedWindows;
- (BOOL)acceptsFocus;
- (id)content;
- (void)dealloc;
- (BOOL)dispatchEvent:(id)arg1;
- (id)init;
- (BOOL)isOpaque;
- (BOOL)isOrderedIn;
- (int)level;
- (void)orderAbove:(id)arg1;
- (void)orderBack;
- (void)orderBelow:(id)arg1;
- (void)orderFront;
- (void)orderOut;
- (void)setAcceptsFocus:(BOOL)arg1;
- (void)setContent:(id)arg1;
- (void)setIsOpaque:(BOOL)arg1;
- (void)setLevel:(int)arg1;

@end

