/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRXMLNode.h"

@class BRXMLElement;

@interface BRXMLDocument : BRXMLNode {
@private
	BRXMLElement *_rootElement;	// 8 = 0x8
}
@property(retain, nonatomic) BRXMLElement *rootElement;	// G=0x3674dcb1; S=0x3674de31; 
- (id)init;	// 0x3674da4d
- (id)initWithData:(id)data options:(unsigned)options error:(id *)error;	// 0x3674d63d
- (id)initWithRootElement:(id)rootElement;	// 0x3674da79
- (id)initWithXMLString:(id)xmlstring options:(unsigned)options error:(id *)error;	// 0x3674dc2d
- (id)XMLData;	// 0x3674dff5
- (id)XMLDataWithOptions:(unsigned)options;	// 0x3674e179
- (void)dealloc;	// 0x3674dc65
- (id)elementById:(id)anId;	// 0x367a1835
- (id)makeElementNamed:(id)named;	// 0x3674e189
// declared property getter: - (id)rootElement;	// 0x3674dcb1
// declared property setter: - (void)setRootElement:(id)element;	// 0x3674de31
@end

