//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <AppleTV/BRTransitionControl.h>

@class BRControl;

__attribute__((visibility("hidden")))
@interface BRZoomTransitionControl : BRTransitionControl
{
    BRControl *_prerender;
    BOOL _prerenderAnimation;
}

- (void)_addPrerender;
- (void)_removePrerender;
- (void)_takePrerenderSnapshot;
- (void)_updateContentForTransitionState;
- (void)_zoomInCompleted:(id)arg1;
- (void)_zoomOutCompleted:(id)arg1;
- (void)dealloc;
- (void)layoutSubcontrols;
- (BOOL)prerenderAnimation;
- (void)setContent:(id)arg1;
- (void)setPrerenderAnimation:(BOOL)arg1;
- (void)setTransitionedIn:(BOOL)arg1;

@end

