/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "BRTransitionControl.h"


__attribute__((visibility("hidden")))
@interface BRZoomTransitionControl : BRTransitionControl {
@private
	BRControl *_prerender;	// 56 = 0x38
	BOOL _prerenderAnimation;	// 60 = 0x3c
}
@property(assign) BOOL prerenderAnimation;	// G=0x366da18d; S=0x366da17d; converted property
- (void)_addPrerender;	// 0x366da2d1
- (void)_removePrerender;	// 0x366da359
- (void)_takePrerenderSnapshot;	// 0x366da3c5
- (void)_updateContentForTransitionState;	// 0x366da5fd
- (void)_zoomInCompleted:(id)completed;	// 0x366dad19
- (void)_zoomOutCompleted:(id)completed;	// 0x366dad89
- (void)dealloc;	// 0x366da0c9
- (void)layoutSubcontrols;	// 0x366da1fd
// converted property getter: - (BOOL)prerenderAnimation;	// 0x366da18d
- (void)setContent:(id)content;	// 0x366da115
// converted property setter: - (void)setPrerenderAnimation:(BOOL)animation;	// 0x366da17d
- (void)setTransitionedIn:(BOOL)anIn;	// 0x366da19d
@end

