/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSArray.h> // Unknown library


@interface NSArray (Unique)
- (id)uniqueObjectsForKey:(id)key;	// 0x36754b91
@end

@interface NSArray (FirstRest)
- (id)first;	// 0x36754d49
- (id)firstObject;	// 0x36754d11
- (id)head;	// 0x36754dad
- (id)rest;	// 0x36754d59
- (id)tail;	// 0x36754dbd
@end

@interface NSArray (Map)
- (id)map:(id)map;	// 0x36754dcd
@end

@interface NSArray (Filter)
- (id)objectsPassingTest:(id)test;	// 0x36754f05
@end

@interface NSArray (Modification)
- (id)arrayByRemovingObject:(id)object;	// 0x36754f35
@end

@interface NSArray (Serialization)
- (BOOL)writeToFile:(id)file atomically:(BOOL)atomically format:(unsigned)format;	// 0x36754fb5
@end

@interface NSArray (Randomization)
+ (id)randomizedArrayFromArray:(id)array;	// 0x36755055
+ (id)shuffleArray:(id)array;	// 0x3675501d
@end

