//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Mar  6 2013 16:24:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSBundle.h"

@interface NSBundle (BRBundleAdditions)
- (id)pathForImage:(id)arg1 ofType:(id)arg2;
- (id)pathForImage:(id)arg1 ofType:(id)arg2 inDirectory:(id)arg3;
- (id)urlForImage:(id)arg1 ofType:(id)arg2;
@end

