/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSData.h> // Unknown library


@interface NSData (BRDataUtilities)
- (id)AES256DecryptWithKey:(id)key;	// 0x3675a7cd
- (id)AES256EncryptWithKey:(id)key;	// 0x3675a709
@end

@interface NSData (MimeDataEncoding)
+ (unsigned)quotedPrintableLengthOfHeaderBytes:(const char *)headerBytes length:(unsigned)length;	// 0x3677c031
- (id)decodeBase64;	// 0x3677b431
- (id)decodeModifiedBase64;	// 0x3677c011
- (id)decodeQuotedPrintableForText:(BOOL)text;	// 0x3677adc9
- (id)encodeBase64;	// 0x3677bff9
- (id)encodeBase64AllowCancel:(BOOL)cancel;	// 0x3677c005
- (id)encodeBase64HeaderData;	// 0x3677c025
- (id)encodeBase64WithoutLineBreaks;	// 0x3677ba01
- (id)encodeBase64WithoutLineBreaksOrPadding;	// 0x3677bfed
- (id)encodeModifiedBase64;	// 0x3677c019
- (id)encodeQuotedPrintableForText:(BOOL)text;	// 0x3677b101
- (id)encodeQuotedPrintableForText:(BOOL)text allowCancel:(BOOL)cancel;	// 0x3677b115
- (BOOL)isValidBase64Data;	// 0x3677b951
@end

