/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSError.h> // Unknown library
#import "AppleTV-Structs.h"


@interface NSError (BRError)
+ (id)errorWithBRError:(int)brerror;	// 0x3675dd65
+ (id)errorWithBRError:(int)brerror withDescription:(id)description withReason:(id)reason andSuggestion:(id)suggestion;	// 0x3675df19
+ (id)errorWithBRError:(int)brerror withDescription:(id)description withReason:(id)reason andSuggestion:(id)suggestion userInfo:(id)info;	// 0x3675df45
- (void)postBRErrorNotificationFromObject:(id)object;	// 0x3675e049
@end

@interface NSError (JSAdditions)
- (OpaqueJSValue *)jsCopyObjectWithContext:(OpaqueJSContext *)context withException:(const OpaqueJSValue **)exception;	// 0x367c9eb9
@end

@interface NSError (ISAdditions)
- (id)errorBySettingFatalError:(BOOL)error;	// 0x3681b9e1
- (BOOL)isEqual:(id)equal compareUserInfo:(BOOL)info;	// 0x3681ba19
- (BOOL)isFatalError;	// 0x3681bbe5
@end

