/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSHTTPURLResponse.h> // Unknown library


@interface NSHTTPURLResponse (ISAdditions)
- (id)_dateFromExpires;	// 0x3682fe89
- (BOOL)_getCacheControlMaxAge:(double *)age;	// 0x3682fd21
- (id)_iTunesStore_valueForHTTPHeader:(id)httpheader;	// 0x36830005
- (id)expirationDate;	// 0x3682fed1
- (double)expirationInterval;	// 0x3682ff25
- (BOOL)getAppleMaxAge:(double *)age;	// 0x3682ffb1
- (long long)maxExpectedContentLength;	// 0x36830055
@end

