/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <NSLocale.h> // Unknown library
#import "ATVJSCopyObject.h"
#import "ATVJSConfigurable.h"


@interface NSLocale (JSAdditions) <ATVJSCopyObject, ATVJSConfigurable>
+ (void)setupForJavaScript:(OpaqueJSContext *)javaScript object:(OpaqueJSValue *)object;	// 0x3683a149
- (OpaqueJSValue *)jsCopyObjectWithContext:(OpaqueJSContext *)context withException:(const OpaqueJSValue **)exception;	// 0x3683a3b5
@end

