/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSMutableArray.h> // Unknown library


@interface NSMutableArray (BRMutableArrayAdditions)
- (void)addObjectIfNotNil:(id)aNil;	// 0x367551ad
- (void)shuffle;	// 0x367551c9
@end

