/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSMutableDictionary.h> // Unknown library


@interface NSMutableDictionary (BRMutableDictionaryAdditions)
- (void)setObjectIfNotNil:(id)aNil forKey:(id)key;	// 0x3675c721
@end

