/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSNull.h> // Unknown library


@interface NSNull (BRDisplayString)
- (id)displayString;	// 0x3675c751
@end

